### ISSUE TITLE
Prepare for new package

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#111]
- [x] Test branch feature/0.0.9 fully on Windows
- [x] Update https://obsidian-html.github.io/ to have better explanation of configuration options/modes/features.
- [x] Compile changelog
- [x] Push new package to pypi
- [x] Update pypi readme 
- [x] Push new package to pypi :laughing:

**Comment by dwrolvink** [comment]
Revamped https://obsidian-html.github.io/

**Comment by dwrolvink** [comment]
Tested on Windows, some path errors, somehow I get deprecation warnings on there that showed me that I was using normal strings for regex, where that should be raw strings. Those are fixed, and it all seems fine now.

**Comment by dwrolvink** [comment]
@jcolson I'm ready to push the new package, want to do your own testing round beforehand? Your vault always seem to have nice edge cases :rofl:

**Comment by jcolson** [comment]
Ha!  Yes will run through quick

**Comment by jcolson** [comment]
looks good!  published the new site: http://www.karma.net/DragonHearts ;-)

**Comment by dwrolvink** [comment]
Nice, those backlinks are really usefull on your notes!
I just added a feature I was in dire need of: https://obsidian-html.github.io/General%20Information/HTML%20tweaks.html#!scrolling-notes 

Navigating forward and backward was kind of annoying, now way easier :)

**Comment by dwrolvink** [comment]
@jcolson momentous occasion!

https://pypi.org/project/obsidianhtml/

:tada: :tada: :tada:
