### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by paulcaillard** [obsidian-html/obsidian-html#209]
Hi

When I run obsidianhtml (`obsidianhtml -i config.yaml`), it output an error : 

```
PS C:\Users\paul\Mon Drive\06_obsidian\website> obsidianhtml -i config.yaml
> COPYING VAULT C:\Users\paul\Mon Drive\06_obsidian\website\obsidianwebtest TO C:\Users\paul\AppData\Local\Temp\tmpdw50lql7
< COPYING VAULT: Done
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (C:\Users\paul\AppData\Local\Temp\tmpdw50lql7\index.md)
> COMPILING HTML FROM MARKDOWN CODE (output\md\index.md)
Traceback (most recent call last):
  File "C:\Users\paul\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\paul\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\paul\AppData\Local\Programs\Python\Python39\Scripts\obsidianhtml.exe\__main__.py", line 7, in <module>
  File "C:\Users\paul\AppData\Local\Programs\Python\Python39\lib\site-packages\obsidianhtml\__init__.py", line 715, in main
    recurseTagList(pb.tagtree, '', pb, level=0)
  File "C:\Users\paul\AppData\Local\Programs\Python\Python39\lib\site-packages\obsidianhtml\__init__.py", line 346, in recurseTagList
    rel_dst_path_as_posix = tag_dst_path.relative_to(pb.paths['html_output_folder']).as_posix()
  File "C:\Users\paul\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 939, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: 'C:\\Users\\paul\\Mon Drive\\06_obsidian\\website\\output\\html\\obs.html\\tags\\index.html' is not in the subpath of 'output\\html' OR one path is relative and the other is absolute.
```

I'm new to programming, so I didn't understand the error, can you help me ?

Thank you

**Comment by paulcaillard** [comment]
Here's is my config file : 

```
# The first folder that contains all obsidian files
# Can be absent when toggles/compile_md == False
# Use full path or relative path, but don't use ~/
obsidian_folder_path_str: 'C:/Users/paul/Mon Drive/06_obsidian/website/obsidianwebtest'

# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Can be absent when toggles/compile_md == False
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: 'C:/Users/paul/Mon Drive/06_obsidian/website/obsidianwebtest/index.md'
```

**Comment by dwrolvink** [comment]
The program tries to delete the previous output, to ensure that if you remove notes, that they will be gone in the newly compiled output too.

On Windows, some programs have a blocking behavior, meaning that you can't delete a file if it is opened. 
Do you have the file `C:\Users\paul\Mon Drive\06_obsidian\website\output\html\obs.html\tags\\index.html` open in notepad or any other program? If you close it, then it should run.

By the way, if you output directly into your vault you're also going to have another issue. (DuplicateFileName error).
I just found out this week that more people are doing this, so I'm going to have to update the documentation.

It's best to have this folder structure:
``` plaintext
C:/Users/paul/Mon Drive/06_obsidian/website/obsidianwebtest/             # folder containing everything
├─ C:/Users/paul/Mon Drive/06_obsidian/website/obsidianwebtest/vault/    # folder containing all of your notes
│     └─ C:/Users/paul/Mon Drive/06_obsidian/website/obsidianwebtest/vault/index.md
├─ C:/Users/paul/Mon Drive/06_obsidian/website/obsidianwebtest/output/   # folder containing the md and html output
└─ C:/Users/paul/Mon Drive/06_obsidian/website/obsidianwebtest/config.yml
```

If you restructure your folder like that, (so putting your vault in a subfolder called vault), and you remove the output folder from the vault folder and then run again, it probably will work. Let me know if it does!

**Comment by dwrolvink** [comment]
Updated the instructions, for your reference: https://obsidian-html.github.io/Instructions/Quickstart.html#!run

**Comment by paulcaillard** [comment]
I have the same error. 
I moved everything to my desktop to make sure Google Drive Sync doesn't cause errors (I also tried to do it with Google Drive Sync closed). 
I also tried to manually delete the output folder before running the script.

```
PS C:\Users\paul\Desktop\obsidianhtmltest> obsidianhtml -i config.yaml
> COPYING VAULT C:\Users\paul\Desktop\obsidianhtmltest\vault TO C:\Users\paul\AppData\Local\Temp\tmpd476kmwl
< COPYING VAULT: Done
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (C:\Users\paul\AppData\Local\Temp\tmpd476kmwl\index.md)
> COMPILING HTML FROM MARKDOWN CODE (output\md\index.md)
Traceback (most recent call last):
  File "C:\Users\paul\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\paul\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\paul\AppData\Local\Programs\Python\Python39\Scripts\obsidianhtml.exe\__main__.py", line 7, in <module>
  File "C:\Users\paul\AppData\Local\Programs\Python\Python39\lib\site-packages\obsidianhtml\__init__.py", line 715, in main
    recurseTagList(pb.tagtree, '', pb, level=0)
  File "C:\Users\paul\AppData\Local\Programs\Python\Python39\lib\site-packages\obsidianhtml\__init__.py", line 346, in recurseTagList
    rel_dst_path_as_posix = tag_dst_path.relative_to(pb.paths['html_output_folder']).as_posix()
  File "C:\Users\paul\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 939, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: 'C:\\Users\\paul\\Desktop\\obsidianhtmltest\\output\\html\\obs.html\\tags\\index.html' is not in the subpath of 'output\\html' OR one path is relative and the other is absolute.
```

What is strange is that I never saw the obs.html folder. Is this folder created automatically ?

**Comment by dwrolvink** [comment]
Yes, that folder is created in your html output folder for all the css/js files and other stuff that the website needs.

You are getting a different error now though. I think this is because I didn't test enough with relative paths on Windows...

Adding the following settings might fix this:
``` yaml
html_output_folder_path_str: 'C:\Users\paul\Desktop\obsidianhtmltest\output\html'
```

If it doesn't, you could disable the [tags feature](https://obsidian-html.github.io/Configurations/Create%20index%20from%20tags.html), if you don't care about it:
``` yaml
toggles
  features:
    create_index_from_tags:
      enabled: False
```

If not I'll need to push a bugfix, but for that I'll first need to find out what exactly is going wrong with the paths here, not sure why the `html_output_folder` is not being resolved as it should be according to the code... :thinking:

**Comment by dwrolvink** [comment]
Okay... I found the issue. Path.resolve() should make an absolute path out of a relative path, which just works on Linux, but on Windows, if the path doesn't exist yet it just doesn't do anything, very nice.

That means that using the absolute path like I said above should fix it, but for completeness sake / if it is a problem somewhere else in the code, then you can fetch the most recent code in which I added a fix for this.

To fetch the new code, run these commands:
``` bash
pip uninstall obsidianhtml
pip install git+https://github.com/obsidian-html/obsidian-html
```

**Comment by paulcaillard** [comment]
It worked! (without even downloading the new version).

Thank you very much for your help !

**Comment by dwrolvink** [comment]
No problem, happy it works!
