### ISSUE TITLE
Fix graph view for process_all: True

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#22]
The new mode of setting https://github.com/obsidian-html/obsidian-html/blob/ff371c665a78d10a6658dbd8f04b759e0882a858/example_config.yml#L55 to true allows us to convert all notes, not just those that are reachable via the homepage.

But this breaks the backlink mechanism, as we can't guarantee that the recurse function is called by a linking page (it can be the main loop). Thus we need to flip it around. In the linking page, figure out what the dest_path is of each link of the note, and if a valid link, add the node and the link to the pb.network_tree object.

Then remove the code that is now the wrong way around.

Note: this will also fix another bug: 
- Links missing in graph view more than one note links to another (processed note does not get processed again).

**Comment by dwrolvink** [comment]
@jcolson I just woke up, so I won't be working on this for a few hours, might start on it today still if you don't have a go at it. 

Code of interest:
https://github.com/obsidian-html/obsidian-html/blob/10ee173dd5d17d1cd61281753b728b5a570dc34c/obsidianhtml/__init__.py#L76

https://github.com/obsidian-html/obsidian-html/blob/10ee173dd5d17d1cd61281753b728b5a570dc34c/obsidianhtml/__init__.py#L194-L217

What needs to be done, imo, is to move the link creation to this loop: https://github.com/obsidian-html/obsidian-html/blob/10ee173dd5d17d1cd61281753b728b5a570dc34c/obsidianhtml/__init__.py#L248

But that entails (re)creating a function or something to validate each link before adding a graph link.
Perhaps just seeing if the link ends in `.md`, but you've seen already how that kind of simple testing can be a breeding ground for bugs. 

Don't worry about adding links/nodes twice, this is fenced here:
https://github.com/obsidian-html/obsidian-html/blob/10ee173dd5d17d1cd61281753b728b5a570dc34c/obsidianhtml/NetworkTree.py#L17-L46

**Comment by dwrolvink** [comment]
working on this

**Comment by dwrolvink** [comment]
@jcolson see #46 a config yaml change is needed then this change should fix this issue

**Comment by jcolson** [comment]
works like a champ!  lovely!
