### ISSUE TITLE
[Feature Request] fuzzy searches

### ISSUE THREAD

**Issue by dr-code** [obsidian-html/obsidian-html#238]
Hello again,

I was wondering if we can get a search bar/search feature that fuzzy searches through all the notes? As I scale my notes, this may be an important feature to have.

Thanks

**Comment by dwrolvink** [comment]
I've never built a search system before, so not sure if it's possible / going to be usable.

At the moment you can make notes findable via the directory structure and tags view, as well as smart linking from other notes of course.

But if this is doable we should surely add it in.

**Comment by dr-code** [comment]
Yes the directory view and tags really makes this easy, thank you for that!

Thought I'd share this because I came across it. 
https://www.npmjs.com/package/flexsearch

I'm just thinking from a global perspective, if I need to search something within the notes, not the titles themselves then it would be a quick way to find what I'm looking for. Similar to Obsidian's search feature.

Thanks!

**Comment by dwrolvink** [comment]
a first search version is added to master.

It works pretty well for me. 
haven't gone bughunting yet, this is really bleeding edge, but I wanted this change out of the door because it is nice weather outside =]

might switch over to the flexsearch that you recommended, for now fuse was really easy to integrate and works quick enough for my vault. (but better performance is always nice of course).

I'm curious on what you think of the current search feature.

**Comment by dr-code** [comment]
Couple of things (now that I can finally see the search feature!)

There is no way to exit the search for me. Once you search unless you click on an item, you can't just close out of the search.

Other thing is, it doesn't search words within the documents themselves, just the titles and headings

and lastly when I search an item like "asthma" It shows the documents that have asthma as a heading, but it pulls in all of the words on that document, not just a few. See below. 
![image](https://user-images.githubusercontent.com/8603561/167216371-229a0ee6-6f23-43f5-be88-78e6d52d28ff.png)

**Comment by dwrolvink** [comment]
- you should be able to click anywhere outside of the search field to exit it
  - I was wondering how clear this would be to people, apparently not very clear, will add an (x) button to close the search field.
-  it searches two things: the page names / graph names and a set of all unique words in a page. This is done to limit the size of the search. For example, the set of unique words for this post is: 
   ```
   'For', 'anywhere', 'limit', 'this', 'to', 'outside', 'it', 'apparently', 'size', 'not', 'a', 'will', 'post', 'example,', 'the', 'an', 'graph', 'is', 
   'unique', 'be', 'I', 'things:', 'search.', 'click', 'field', 'of', 'This', 'should', 'would', 'two', 'very', 'page', 'exit', 'clear,', 'for', 
   'words', 'done', 'in', 'all', 'was', 'it', 'searches', 'how', 'is', 'set', 'people', 'clear', 'names', 'and', 'field', 'able', 'close', 
   'you', 'wondering', 'search', '(x)', 'add', 'button', 'page'
   ``` 
  - One thing is that the word order is lost in this way, so it is mostly a keyword searcher. But a fullpage search will be pretty taxing for a static website. We could try it out, but it would require loading in the entire site every page load and then searching through that.
  - It shouldn't look like that, see my view: 
    
![image](https://user-images.githubusercontent.com/30291690/167217477-88a5595c-41e0-4c4c-8b96-1ca15300571e.png)

Will try out some other css tomorrow that might work better for safari. Good to know that this doesn't work.

**Comment by dwrolvink** [comment]
It also needs some other tweaks. For example, if I search for "graphs" then it finds "paragraphs" as a high level match, which is kind of smart but at the same time pretty lame.

The other system that I used before had even weirder rules, where is would score matches like '**P**oor **ARAG**orn **R**ode **A**lone **F**or" higher than matches that included just the word paragraph itself. So maybe just try your suggestion of flexsearch and if that one is idiotic too then maybe I'll need to layer some extra logic on top to make it behave a bit more sensibly.

**Comment by dwrolvink** [comment]
Alright, moved over to flexsearch, works pretty well. Added the escape button way of closing the search field and styled it a bit cleaner based on the Obsidian search field styling.

I think next would be to make the matched part bold like in Obsidian and try out if we can use a sanitized full-page search instead of the unique word set that we have now.

**Comment by dwrolvink** [comment]
![image](https://user-images.githubusercontent.com/30291690/167254941-b0fd8ef4-a070-4338-a805-2bfebb970dc7.png)
![image](https://user-images.githubusercontent.com/30291690/167255037-b75b44cc-c457-4044-ba02-25fb8ccb79f1.png)

**Comment by dr-code** [comment]
Tested it out. Works really well. Super fast, and works on Safari. The esc also works on Safari. Definitely agree to see if you can make the search item bolded in the results. Because the search definitely knows exactly where I am referring to but if I am unsure thats the right one then I wouldn't be able to "preview" it. 

And then when we click on the search result, it goes directly to the search item. Right now, when I search a specific term thats lower in that document, it just takes me to the document. In obsidian, if I was to search a specific header, it would take me to the header

Im glad flex search worked out!

![image](https://user-images.githubusercontent.com/8603561/167256093-5a212716-6c25-4714-bffc-b1a5716f9265.png)

**Comment by dwrolvink** [comment]
Okay, now there are some highlights from the full page content. The amount of chars before and after the match is configurable, thinking about adding it to the config yaml settings.

You can check it out here (and in master of course): https://obsidian-html.github.io/

![image](https://user-images.githubusercontent.com/30291690/167319954-b9d9ce04-27c6-4b3c-b8d4-bc4babcfef6c.png)

**Comment by dwrolvink** [comment]
escaped any html that might be present in the notes, in latest PR =]

**Comment by dr-code** [comment]
Yeah this works a lot better. Is there anyway the search result, once clicked can go to that part of the text instead the top of the page where that search item is?

**Comment by dwrolvink** [comment]
no that kind of information is not retained so that would be near impossible to implement

once on the page you could just ctrl+f repeatedly to find the string though right?

**Comment by dr-code** [comment]
oh yeah absolutely.
just wanted to see if it's possible. But this works just as well!

Thank you

**Comment by dwrolvink** [comment]
Alright, added the ability to fold open long matches in the search results. I think I'll leave it at that for now aside for bugfixes/cleanup/small styling tweaks.

Let me know if you find any issues using it, will probably create a new release this weekend to publish the new search in.

**Comment by dwrolvink** [comment]
Implemented in the master branch; will be packaged along with the new release when it arrives.
