### ISSUE TITLE
[Feature request] Rendering Latex

### ISSUE THREAD

**Issue by hgrw** [obsidian-html/obsidian-html#239]
One of the great things about obsidian is that it renders latex. When generate a site using obsidian-html, my latex isn't rendered. Is there some way to enable this? Either way, latex should be enabled in static site by default if at all possible.

**Comment by dwrolvink** [comment]
I agree, it hasn't been added yet though.

Latex is a pretty wide usecase, from what I can remember. Is there a specific set of Latex that you would want to see in the first addition? (Like, for example, mathemetical equations, or the like).

And would you have some example latex from notes that should absolutely work?

**Comment by dwrolvink** [comment]
If you install the master branch you should be able to run this example:

``` markdown
# Implementing Latex
At the moment only the math based latex is enabled. (It's hard to find what Obsidian supports other than the math based latex.)

## Inline Latex (single $)
$\int_0^{2\pi} d\theta x+e^{-i\theta}$

## Block latex (double $)
$$
\begin
{vmatrix}a & b \\ c & d
\end
{vmatrix}=ad-bc
$$
```

That gives me this output: 
![image](https://user-images.githubusercontent.com/30291690/166919408-e6506965-6bbf-41b9-9a62-4574ed1e0868.png)

Let me know what you think of this, and if this implementation is missing anything.

**Comment by hgrw** [comment]
Nice! Good to see it's already in master. My immediate usecase was some inline equations like you have above. Thanks for the comprehensive followup. Looking forward to seeing this in a release <3

**Comment by dwrolvink** [comment]
https://obsidian-html.github.io/Changelog/v2.2.0.html

Published. Good luck with it!
