### ISSUE TITLE
[Feature Request] Make toggle to switch from 2d to 3d graph

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#257]
The 2d is nice because it shows the node names but the 3d just looks more epic, also shows more structure. As they are both nice I'd like to give the ability to switch between the two versions.

**Comment by lgh06** [comment]
just do more tricks on show graph button / hide graph button, let yaml configured graph shows as default, then the other type of graph, then show or hide .

however this may cause big third party js load. 
may need find a way to load graph dependency js only when needed / clicked show graph button / switched graph type.

**Comment by lgh06** [comment]
just do more tricks on show graph button / hide graph button, let yaml configured graph shows as default, then the other type of graph, then show or hide .

however this may cause big third party js load. 
may need find a way to load graph dependency js only when needed / clicks show graph button / switched graph type.

**Comment by dwrolvink** [comment]
I went from (abbr):
``` js
<script defer src="{html_url_prefix}/obs.html/static/3d-force-graph.js"></script>
<script>
    function grapher(args) {
        window.Graph = ForceGraph3D()
    }
</script>
```

To: 
``` js
<script>
    function grapher(args) {
        // load dependency on demand, then call initGraph when the script is loaded
        load_script_on_demand(
            '/obs.html/static/3d-force-graph.js', 
            function(){
                initGraph(args)
            }
        )
    }

    function initGraph(args) {
        window.Graph = ForceGraph3D()
    }
</script>
```

With 
``` js
function load_script_on_demand(path, callback){
    // create script tag
    var elScript = document.createElement('script');
    elScript.setAttribute('type','text/javascript');
    elScript.setAttribute('charset', 'utf-8');

    // set path to load, and callback to be run when loaded
    elScript.setAttribute( 'src', path);
    elScript.onload = callback;

    // add script tag to the end of body
    document.getElementsByTagName("body")[0].appendChild( elScript );
}
```

And the grapher() function only gets called once per page load, the first time the user clicks the graph button.
This results in the 3d-force-graph.js file being loaded only when the show graph button is pressed.

What do you think of this solution?

Only downside is that now the graph div is opened and empty, and the graph only shows up half a second later. Edit: fixed that by opening the div in the onload function: https://github.com/dwrolvink/obsidian-html/commit/6b28c4f68eab6875eff8158cdc4b6f5107077be3

**Comment by dwrolvink** [comment]
Alright, added toggling of the graph between 2d and 3d.
This breaks the ability to add a custom grapher, so this will have to be reintroduced before releasing.

**Comment by dwrolvink** [comment]
Custom modules can now be loaded in. A quick look at the config will make it clear how that works.
Docs still need to be updated though.

As always, current master branch == https://obsidian-html.github.io/ 
So the graph toggle can be previewed there.

- On-demand loading of the dependencies is now also built in by default for each grapher. 
- I've started modularizing the javascript code in an attempt to clean up the global scope. The only code visible in the global scope of the graph system is the window.ObsHtmlGraph module object.

**Comment by dwrolvink** [comment]
Rewrote the docs 
https://obsidian-html.github.io/Configurations/Styling/Writing%20a%20custom%20graph%20view%20template.html
