### ISSUE TITLE
[Feature Request] Show its tag (or tags) on a specific page

### ISSUE THREAD

**Issue by lgh06** [obsidian-html/obsidian-html#261]
We have tag list index page already, however there is no tags showing on one specific page.
Maybe tags should append to Backlinks / graph area, at the end of one specific page.

**Comment by dwrolvink** [comment]
So you want to show the tags of the current page? 

Might be nice, then we can also make each tag a link to the corresponding tag page.

**Comment by lgh06** [comment]
yes, i think this is the only main feature missing now.

**Comment by dwrolvink** [comment]
Alright, this has been added to the current master branch.
See for example bottom of this page: https://obsidian-html.github.io/General%20Information/About%20ObsidianHtml.html

![image](https://user-images.githubusercontent.com/30291690/170602662-ee263df2-c999-4f1e-b4bf-2364274ac391.png)

Note that this is also the first time that inline tags do anything. Starting with this commit they are also added to the tagtree and thus also listed in that footer tagslist.

Please let me know what you think of this implementation.

**Comment by dwrolvink** [comment]
No feedback so closing
