### ISSUE TITLE
Add ability to show subdirectories in "Directory Contents"

### ISSUE THREAD

**Issue by EntilZha** [obsidian-html/obsidian-html#270]
I've noticed that I have this structure:
- Home.md
- Other.md
- MyFolder
  - Topic1.md
  - Topic2.md
 That the directory listing when at `Home.md` doesn't show `MyFolder` (sensible, since what would be displayed there), but also doesn't show `Topic1.md` or `Topic2.md` (it does show `Other.md`).

Would it be possible to list files one directory down or is there some other workaround for this? Thinking about the Obsidian UI, this is shown as a full collapsible directory tree, so that would be ideal. It looks like this code does that, so maybe a change there: https://github.com/obsidian-html/obsidian-html/blob/326a5f4c6b59d580149f347df90b70654817983b/obsidianhtml/src/js/load_dirtree_footer.js

**Comment by dwrolvink** [comment]
Yes that's currently not possible, but code technically it should be pretty easy to create.
The full index is already located here: https://obsidian-html.github.io/obs.html/dir_index.html

So maybe writing some code to fetch that html, then remove everything higher than the current folder, and using what remains could be a nice route to code this.

**Comment by dwrolvink** [comment]
Please take a look at https://obsidian-html.github.io/

This runs the latest master code, to which I've just added the folding dir tree. 
Please let me know what you think of it, and whether there are any tweaks that you'd like to see for it.

**Comment by EntilZha** [comment]
That looks great @dwrolvink! One thing I noticed is that when the screen window becomes narrow enough, the directory listing auto-hides. It would be great if both the directory listing and the table of contents could be toggled on/off manually

**Comment by dwrolvink** [comment]
Good idea, should be fairly easy also

**Comment by dwrolvink** [comment]
See https://obsidian-html.github.io/

With very narrow screen there is a button in the menu, otherwise there is a bar on the left or right to open the pane.

The whole of the left and right panes are collapsible to make more space for reading. The panes are folded open/closed based on screen width (at page (re)load) *until* a user toggles a pane, from that moment on the choice is persisted in localStorage and this choice is then used going forward.

**Comment by EntilZha** [comment]
That's awesome and is perfect! Thanks for such quick implementation of the feature requests :)!
