### ISSUE TITLE
Duplicate filenames error / rendering bug

### ISSUE THREAD

**Issue by EntilZha** [obsidian-html/obsidian-html#280]
In my vault I have files like `folder1/home.md` and `folder2/home.md`, which triggers an error here https://github.com/obsidian-html/obsidian-html/blob/master/obsidianhtml/__init__.py#L643. I can suppress the error, but then the file handling is a little broken with files overwriting each other. I noticed there was another issue here https://github.com/obsidian-html/obsidian-html/issues/8 that discusses this, so wondering if I'm just not using the right set of options to compile obsidian vault to HTML. Looks like the solution would be to use relative paths eventually, but the issue seems to suggest that already works?

**Comment by dwrolvink** [comment]
So how do you link to one or the other file in obsidian when you have two or more files with the same name? 

The way I use obsidian, there is no way you can get two files with the same name. That is one of the reasons why duplicate file names are not allowed.

**Comment by EntilZha** [comment]
I have one page where I link to multiple files with the same base name, for example the source of that page is:
```
# Index

Vault-wide manual index

## Folder 1
[[Folder1/Home]]

## Folder 2
[[Folder2/Home]]
```

Within obsidian, it seems to fuzzy match `Home` for me then I choose which instance.

**Comment by dwrolvink** [comment]
aha, okay, did not know that that was an option, to use a folder path in the link like that

I had been busy with using abs path as file keys instead of the name, as the code no longer relies on that, and that change will also remove the requirement that no two files exist with the same name in a vault.

we would have to decide which file to match when a link just says `[[Home]]` though. What does obsidian do in that case?

**Comment by dwrolvink** [comment]
Oke I just tried it out, and it seems to be pretty much random.
Obsidian is pretty good at inserting the full path when needed so this would normally not be a big issue.

Okay, we just need to make all file operations keyed to their path instead of their name, quite some work, but should be doable in a week or so if I get around to it.

**Comment by EntilZha** [comment]
On what file to match, I saw the same thing, it looks like either random or first match. I think in this case it would be fine to choose something arbitrary since its undefined behavior even in obsidian (and obsidian seems to really suggest picking one or the other).

It would be awesome to have this! I've been maintaining one larger vault and often structure something like: Project 1, Project 2, Project 3, where each project has a similar structure, hence duplicate names.

**Comment by dwrolvink** [comment]
@GiancarloAparicio @EntilZha 
alright, current master has a first version that works for me, but I expect a lot of bugs with this change, so any testing you guys could do would be greatly appreciated. 

I'll keep this open until it is properly tested and any bugs fixed.

**Comment by EntilZha** [comment]
I'll give it a try and report back on whether I find some bugs. Thanks for the quick impl!

**Comment by EntilZha** [comment]
I've been giving latest master a try for past day or two, and it's working great so far.

The only minor issue I've noticed is that if a file in a subdirectory isn't linked from somewhere, it doesn't get listed. The workaround is simple enough though, just link it from somewhere. I wonder if maybe rather than crawl links, you can crawl the directory tree to get all the available files.

**Comment by dwrolvink** [comment]
That is not an option yet. You can set the process all tag though, this will make sure every note in your vault is processed.

https://obsidian-html.github.io/Configurations/Configuration%20Options.html#!process-all

**Comment by EntilZha** [comment]
That's perfect actually, everything seems to populate with the process all option enabled, thanks!

**Comment by dwrolvink** [comment]
fixed in https://obsidian-html.github.io/Changelog/v3.0.0.html
