### ISSUE TITLE
relative linking to images not working with a urlprefix configured

### ISSUE THREAD

**Issue by jcolson** [obsidian-html/obsidian-html#29]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/2362647/152681790-95932594-a918-4669-856a-a1f096621ee3.png">

**Comment by dwrolvink** [comment]
working on this

**Comment by dwrolvink** [comment]
Can you check if this solves it for you? @jcolson

**Comment by jcolson** [comment]
yes - looks like that did the trick!  cheers
