### ISSUE TITLE
[Feature Request] Implement linking to blocks

### ISSUE THREAD

**Issue by GiancarloAparicio** [obsidian-html/obsidian-html#296]
Hello, I'm using github actions to compile my notes, but I always get an error with the references when they have spaces (nested)
![image](https://user-images.githubusercontent.com/61440825/181136330-d1d6a489-f659-478b-8d89-4b420ad9a74b.png)

This is the note that has the reference...
![image](https://user-images.githubusercontent.com/61440825/181135847-1953302a-2c01-403d-9a6d-95bea1d6b415.png)

**Comment by dwrolvink** [comment]
Yes this is correct. [Links to blocks](https://help.obsidian.md/How+to/Link+to+blocks) are not yet implemented in obsidianhtml. 

I'll regard this issue as a feature request for it and track any updates here.

A workaround at the moment would be to link to the nearest header. Though that might be more rework than a workaround.

**Comment by dwrolvink** [comment]
Alright a first version of block linking has been added in master. 

For instructions on how to install the master branch code instead of the pip version see here: https://obsidian-html.github.io/Instructions/Install%20a%20different%20version.html

Let me know if this works for you. 

I saw that it is possible to also reference code blocks, there are possibly more usecases, but what I've implemented here is just referencing a paragraph / codeblock atm.

The following code is tested to work for me:
``` md

\```
case 1 codeblock standard
\```

^888865

\```
case 2 codeblock direct behind 
\```
^64d285


Case 3: A paragraph 
with a newline but no empty lines ^9b13c9

Case 4: A paragraph with ^3493234 <-- these kind of codes in the text.  And a reference on a newline.

^d8f641
```

Note doing the referencing:
``` md

![[test_error#^888865]]

---

![[test_error#^64d285]]

---

![[test_error#^9b13c9]]

---

![[test_error#^d8f641]]
```

Resulting in: 
![image](https://user-images.githubusercontent.com/30291690/181244096-02ec8b05-bad4-4a23-90d9-0d914e14fb83.png)

**Comment by GiancarloAparicio** [comment]
@dwrolvink I also tried the example you put together with more use cases and they all work correctly.
But when it tried to build my notes it results in error. I am using the master branch version.
![image](https://user-images.githubusercontent.com/61440825/181272563-4a9a493c-4aaf-4196-ad62-d38bfbf41d5d.png)

**Comment by dwrolvink** [comment]
This is unrelated to the other point.

You issue is most likely a setup like this:
``` md
---
tags: sometag
---

also an #inlinetag
```

The frontmatter gets loaded and defines `tags` as a str,  then when an inline tag is found obsidianhtml tries to add this to the metadata['tags'] "list".

Changing tags value to a list will resolve this:
``` md
---
tags: 
  - sometag
---

also an #inlinetag
```

Other options are to remove the tags key from the frontmatter or to remove the inline tags from your note.

**Comment by GiancarloAparicio** [comment]
@dwrolvink Hello, it already worked perfectly for me 😀😀😀.
But I found some bugs in the links to blocks. For example using certain symbols will fail the build.
```md
%%% note1
# wifi 2.4 vs 5.0
---

# TCP/IP Model
---

# CI/CD && DevOps
---

%%% note2

Obsidian replaces these symbols with spaces
[[note1#wifi 2 4 vs 5 0]]  // fail
[[note1#TCP IP Model]] // fail
[[note1#CI CD DevOps]]  // fail
I had to change all those references for the build to work
```

**Comment by dwrolvink** [comment]
Nice that it works! (aside from the special chars thing, made a separate issue for that as you can see).

Will close this now. Just post here if there is anything else that pops up regarding linking to this feature.
