### ISSUE TITLE
Support for zoottelkeeper-obsidian-plugin

### ISSUE THREAD

**Issue by bhickta** [obsidian-html/obsidian-html#306]
[Zoottlekeeper](https://github.com/akosbalasko/zoottelkeeper-obsidian-plugin), a great plugin which listens for folder note inside a folder and automatically populate it with all the notes inside that folder.

I currently generate links like this: 
![image](https://user-images.githubusercontent.com/61617746/181740527-1eed4b01-6f71-44c2-8fd2-9d34beb526af.png)
But such links is not supported by **obsidian-html**.

Kindly add this support...

**Comment by dwrolvink** [comment]
These paths should already be supported.
I noticed there was a bug in it, and the default settings did not make much sense.

I have changed some things, can you [install the master branch instead of the pip version](https://obsidian-html.github.io/Instructions/Install%20a%20different%20version.html#!install-master-branch) and try again?

**Comment by bhickta** [comment]
Error

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\nisha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\obsidianhtml\__main__.py", line 3, in <module>
    main()
  File "C:\Users\nisha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\obsidianhtml\__init__.py", line 742, in main
    ConvertMarkdownPageToHtmlPage(ep, pb)
  File "C:\Users\nisha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\obsidianhtml\__init__.py", line 299, in ConvertMarkdownPageToHtmlPage
    html_body = markdown.markdown(md.page, extensions=extensions, extension_configs=extension_configs)
  File "C:\Users\nisha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\markdown\core.py", line 386, in markdown
    md = Markdown(**kwargs)
  File "C:\Users\nisha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\markdown\core.py", line 96, in __init__
    self.registerExtensions(extensions=kwargs.get('extensions', []),
  File "C:\Users\nisha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\markdown\core.py", line 123, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "C:\Users\nisha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\markdown\core.py", line 155, in build_extension
    ext = entry_points[0].load()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\importlib\metadata\__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'obsidianhtml.markdown_extensions'

**Comment by dwrolvink** [comment]
Alright I forgot to add a line somewhere, and the testing didn't catch this, and it doesn't affect me.

Anyways, please try again.

**Comment by bhickta** [comment]
> Error
> 
> Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "C:\Users\nisha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\obsidianhtml__main__.py", line 3, in main() File "C:\Users\nisha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\obsidianhtml__init__.py", line 742, in main ConvertMarkdownPageToHtmlPage(ep, pb) File "C:\Users\nisha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\obsidianhtml__init__.py", line 299, in ConvertMarkdownPageToHtmlPage html_body = markdown.markdown(md.page, extensions=extensions, extension_configs=extension_configs) File "C:\Users\nisha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\markdown\core.py", line 386, in markdown md = Markdown(**kwargs) File "C:\Users\nisha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\markdown\core.py", line 96, in **init** self.registerExtensions(extensions=kwargs.get('extensions', []), File "C:\Users\nisha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\markdown\core.py", line 123, in registerExtensions ext = self.build_extension(ext, configs.get(ext, {})) File "C:\Users\nisha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\markdown\core.py", line 155, in build_extension ext = entry_points[0].load() File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\importlib\metadata__init__.py", line 171, in load module = import_module(match.group('module')) File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\importlib__init__.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1050, in _gcd_import File "", line 1027, in _find_and_load File "", line 992, in _find_and_load_unlocked File "", line 241, in _call_with_frames_removed File "", line 1050, in _gcd_import File "", line 1027, in _find_and_load File "", line 1004, in _find_and_load_unlocked ModuleNotFoundError: No module named 'obsidianhtml.markdown_extensions'

Still the same problem

I am using **python -m obsidianhtml -i** command

**Comment by dwrolvink** [comment]
please use the following command to upgrade:
``` bash
pip install git+https://github.com/obsidian-html/obsidian-html.git --upgrade
```
And then this command to run:
``` bash
obsidianhtml -i <yourconfigfile>
```

**Comment by bhickta** [comment]
I have directly cloned the master branch, all latest feature are working like #308. But still #306 feature is not working..

**Comment by bhickta** [comment]
> please use the following command to upgrade:
> 
> ```shell
> pip install git+https://github.com/obsidian-html/obsidian-html.git --upgrade
> ```
> 
> And then this command to run:
> 
> ```shell
> obsidianhtml -i <yourconfigfile>
> ```

Yes now the error has gone.. but #306 still doesn't works..

i am not able to use `obsidian -i <config>` command, i am on windows hence i have to use `python -m` command

**Comment by dwrolvink** [comment]
Even if you directly clone the master branch code, you still have to do a pip install to advertise the markdown entrypoints. 
In the case of cloning the code,  you can go into the cloned repo and run `pip install . --upgrade`. That should load that in.

edit: okay do you get any error? what do you mean with "it doesn't work"? What do you get at this point, and what do you expect?

**Comment by bhickta** [comment]
No the above error has gone and the obsidianhtml is working fine now, i have used the `pip install git+https://github.com/obsidian-html/obsidian-html.git --upgrade` command. All is working fine now..

Regarding feature #306, zoottlekeeper links are still not working

This is how my md file look like - 
![image](https://user-images.githubusercontent.com/61617746/181959610-ed736d36-d03a-4c40-bc1b-0ca3a9c4b47f.png)

And this is the output i am getting - 
![image](https://user-images.githubusercontent.com/61617746/181959974-39cb8724-561e-44f8-9a89-a3e9e9b887b1.png)

Another added request - kindly also remove these 2(start and end) comments of Zootlekeeper-plugin

**Comment by dwrolvink** [comment]
Can you provide:
- the target of the links that don't work (from your last screenshot)
-your settings for the zoottelkeeper plugin
-the tree of your vault or the vault itself if possible

I've just installed the plugin myself and I'm trying to break it, but it all works for me

**Comment by dwrolvink** [comment]
also please share the url of the page that you are on when you made the last screenshot

**Comment by bhickta** [comment]
> Can you provide:
> 
> * the target of the links that don't work (from your last screenshot)
>   -your settings for the zoottelkeeper plugin
>   -the tree of your vault or the vault itself if possible
> 
> I've just installed the plugin myself and I'm trying to break it, but it all works for me

## Absolute path
C:\Users\nisha\My Drive\UPSC\Notes\Himachal Pradesh

## Vault Tree
![image](https://user-images.githubusercontent.com/61617746/181993141-7f4c5322-b612-4789-b66b-c7cf869cdb55.png)

## Zoottlekeeper plugin Setting
![image](https://user-images.githubusercontent.com/61617746/181994431-81b99482-799a-4cfa-a1c0-a4e181192147.png)

## Target links
![image](https://user-images.githubusercontent.com/61617746/181994452-c976249b-7df3-41ce-a597-9347989fec9a.png)

**Comment by dwrolvink** [comment]
Ah I think I see what the issue is.

``` yaml
# The first folder that contains all obsidian files
# Can be absent when toggles/compile_md == False
# Use full path or relative path, but don't use ~/
obsidian_folder_path_str: '<REQUIRED_INPUT>'
```

This should be:
``` yaml
obsidian_folder_path_str: 'C:/Users/nisha/My Drive/UPSC/Notes/'
```

I think if you use that path that the links will start working.
Just read the comments above that setting and the links in your markdown file, then it should be apparent why this change is neccessary.

**Comment by bhickta** [comment]
> Ah I think I see what the issue is.
> 
> ```yaml
> # The first folder that contains all obsidian files
> # Can be absent when toggles/compile_md == False
> # Use full path or relative path, but don't use ~/
> obsidian_folder_path_str: '<REQUIRED_INPUT>'
> ```
> 
> This should be:
> 
> ```yaml
> obsidian_folder_path_str: 'C:/Users/nisha/My Drive/UPSC/Notes/'
> ```
> 
> I think if you use that path that the links will start working. Just read the comments above that setting and the links in your markdown file, then it should be apparent why this change is neccessary.

# Now a different error
PS C:\Users\nisha\Desktop\obsidain-htmlo> python -m obsidianhtml -i .\config.yaml
> COPYING VAULT C:\Users\nisha\My Drive\UPSC\Notes TO C:\Users\nisha\AppData\Local\Temp\tmpswq1ujar
< COPYING VAULT: Done
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (C:\Users\nisha\AppData\Local\Temp\tmpswq1ujar\Himachal Pradesh\Himachal Pradesh.md)
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\nisha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\obsidianhtml\__main__.py", line 3, in <module>        
    main()
  File "C:\Users\nisha\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\obsidianhtml\__init__.py", line 702, in main
    ep = pb.files[paths['obsidian_entrypoint'].name]
KeyError: 'Himachal Pradesh.md'
PS C:\Users\nisha\Desktop\obsidain-htmlo>

**Comment by bhickta** [comment]
Finally solved...
## Sub Request - Removing these 2 comments
%% Zoottelkeeper: Beginning of the autogenerated index file list %%

%% Zoottelkeeper: End of the autogenerated index file list %%

**Comment by dwrolvink** [comment]
Good that is working finally! That was quite a curve ball.

For your subrequest, please see #316
