### ISSUE TITLE
[Feature Request] Clickable tags in the page

### ISSUE THREAD

**Issue by bhickta** [obsidian-html/obsidian-html#308]
Tags in the page are interpretated and put down in tag section. Kindly add a option to have tags clickable in the page also, so that when the tags is clicked, related notes list are opened.

**Comment by dwrolvink** [comment]
This has been infeasible for some time, but I'll reconsider whether the codebase is mature enough to add in-page tags :+1:

**Comment by dwrolvink** [comment]
Implemented in latest pull: https://obsidian-html.github.io/Demonstrations/Implementing%20inline%20tags.html

Note that version 3.1.0 is not published yet at time of writing
