### ISSUE TITLE
UnboundLocalError: local variable 'isMd' referenced before assignment

### ISSUE THREAD

**Issue by edgardSchi** [obsidian-html/obsidian-html#318]
I was having trouble using obsidian-html because I would always get the error message "UnboundLocalError: local variable 'isMd' referenced before assignment". 

Adding `idMd = False` before the if-statement in https://github.com/obsidian-html/obsidian-html/blob/3c477b39166a4024ac1fab71d89c49d56a34441e/obsidianhtml/MarkdownPage.py#L223 seems to fix the problem.

Python: 3.10.5
obsidian-html: build with latest commit 3c477b39166a4024ac1fab71d89c49d56a34441e

I can create a pull request and commit my change if that is welcomed.

**Comment by dwrolvink** [comment]
Yes that would be the correct solution. 
I can add it as well, but you are always welcome to send in PR of course.

I'm curious what kind of notes you have to even reach this bug, but I guess we will see

**Comment by edgardSchi** [comment]
Well I had one note where I inserted an image with `![Some text](link/to/image)` (I think I was testing something and forget to remove it). 
If I change that to the normal obsidian syntax `![[image]]` the code from above is never reached and the program runs successfully.

**Comment by dwrolvink** [comment]
Nice, and with the fix now, does it not give that bug anymore when you have that image? Cause then I can close this issue

**Comment by edgardSchi** [comment]
With the fix it now works as intended. So you can close the issue.

Thank you for the fast reply and quick fix!
