### ISSUE TITLE
[Feature Request] Adding personal Icon and Favicon

### ISSUE THREAD

**Issue by bhickta** [obsidian-html/obsidian-html#321]
# Adding a Icon and Favicon
* Having a personal icon on Right/Left side of each page to have personalized feeling
* Having a personal favicon to give a professional feeling

** I know I am demanding a not that important feature, but still if possible kindly add this feature too...

**Comment by dwrolvink** [comment]
You can just overwrite the favicon.ico that is placed in the root of your html output folder.

Weren't you already using a custom html template?

That would be the suggested route to go if you want to customize the look and feel of the output.

- Edit your custom html template to use your personal image / other html code
- Run obsidianhtml
- Add the favicon and image to the html output
- Serve website

**Comment by dwrolvink** [comment]
I will add the option to have files in `<your_vault>/obs.html/includes/` and then configure them to be copied over to any location inside of the html_output_folder. That way you will be able to add your favicon.ico in your vault and have it overwrite the default one.

**Comment by bhickta** [comment]
Thanks that will definitely work smoothly
