### ISSUE TITLE
Obsidian query integration

### ISSUE THREAD

**Issue by gpQ4utjefs** [obsidian-html/obsidian-html#324]
Obsidian allow for query to search and output any string..

## Syntax
![image](https://user-images.githubusercontent.com/110364751/182106997-4f8abd24-e28d-46fd-adf0-af50ebbed817.png)

## Regarding osidian
* Yes it is quite similar to Dataview but it is inbuilt and extremely quick

**Comment by dwrolvink** [comment]
You need to be a bit more specific than that. We are working on the dataview integration, is that something that you mean? #271

**Comment by dwrolvink** [comment]
Ooh that is pretty cool, didn't know that was a thing. 

Do you use complex queries, or just a combination of keywords to search on? if the former, could you share some?

Quite a big feature. We have fuzzy search already, but that is in javascript, and not really usable for precompilation. Perhaps I can find a Rust/Go based fuzzy search util and use that to start offloading cpu intensive work to subprograms written in quicker languages.

**Comment by gpQ4utjefs** [comment]
I mostly use simple queries like: 
  line:(foo bar)
  tag:#work
But query can be extremely complex too - 
* For further reference you can visit: https://help.obsidian.md/Plugins/Search

**Comment by gpQ4utjefs** [comment]
Any progress on this issue sir?

**Comment by dwrolvink** [comment]
I have not yet started, and when I do it will probably take some days before you get anything usable.
I have a busy weekend coming up and already not feeling that well so I think earliest that I start on this one is next weekend.

Editing existing features / bugfixes I often do in the evenings during the week, but for an entirely new one I want to really reserve some time to get a first setup going.

PR's always welcome of course.

**Comment by dwrolvink** [comment]
So I'm pretty busy at the moment, not much time for coding I am afraid. Like always: low hanging fruit and bugfixes have priority, so this feature will be put on the back burner for now. Don't expect any progress on this the coming months.

**Comment by dwrolvink** [comment]
A first mvp version was added:

https://obsidian-html.github.io/Demonstrations/Embedded%20search.html

Let me know if you still use obsidianhtml, and what kind of queries don't work / don't work as expected, or other usecases that you would want to see implemented.

Adding search results from within each matched note will be added next.

**Comment by dwrolvink** [comment]
alright, it's starting to come together

matches from the note content are processed fairly okay now
just the matches from tags, title, etc are missing

https://obsidian-html.github.io/Demonstrations/Embedded%20search.html

**Comment by bhickta** [comment]
Matches form tags are not working properly

# Example
if we search #tag/subtag, it gives output as if tag and subtags are different words. That is it gives output for search for individual  words "tag" and "subtag"

# Appreciation
* Great feature

**Comment by dwrolvink** [comment]
Alright, it should be possible to search for specific tags now, see

- https://obsidian-html.github.io/Demonstrations/Embedded%20search.html#!search-for-a-specific-tag

It does still have a bug that in a normal search, it will show tags twice sometimes, I'm working on that.

This was a bit harder to implement than that I had expected, so just happy to get this out already.

**Comment by bhickta** [comment]
Issue: Not giving integrated search i.e. search for specific pattern only
If i query for "#london/hotel" or "#london/hotel", it gives output as
* lor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt **_london/hotel_** lor sit amet, consectetur adipiscing elit
* voluptate velit esse cillum **_london/hotel_** dolore eu fugiat nulla pariatur
* idunt ut labore et dolore magna **_hotel_** aliqua. Ut enim ad minim veniam
* sunt in culpa **_hotel_** qui officia deserunt mollit anim id est laborum
* enim ad minim veniam, quis nostrud **_london_** exercitation ullamco laboris

What i think it would give
* lor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt **_london/hotel_** lor sit amet, consectetur adipiscing elit
* voluptate velit esse cillum **_london/hotel_** dolore eu fugiat nulla pariatur

**Comment by dwrolvink** [comment]
I've tried to implement this, but whoosh does not parse lookarounds properly, so my hands are tied at the moment.
A workaround would be to just use `tag:#london/hotel` instead of `#london/hotel`. Should give you the same results in Obsidian and the desired result in ObsidianHtml.

**Comment by bhickta** [comment]
```tag:#london/hotel```, this is not working too. It gives same result as ```#london/hotel```

**Comment by dwrolvink** [comment]
Works for me. See https://obsidian-html.github.io/Demonstrations/Embedded%20search.html#!search-for-a-specific-tag when searching for `tag:#babayaga` it only finds that tag, and not tag `bla/babayaga`. 

When is the last time you've pulled new code?

**Comment by dwrolvink** [comment]
Closing due to lack of feedback

**Comment by markfaine** [comment]
Is this feature dead?
