### ISSUE TITLE
[Bug]: add_dir_list: False showing error

### ISSUE THREAD

**Issue by gpQ4utjefs** [obsidian-html/obsidian-html#330]
# Error
![image](https://user-images.githubusercontent.com/110364751/183282026-6583e8f9-a997-4375-83e8-f4614672a351.png)

# What i am using
* Custom docmentation-template.html
* layout: documentation

Edit: 
Never mind one can turn it off via custom.html

**Comment by dwrolvink** [comment]
Thank you for the bug report, it should be fixed in the latest master now
