### ISSUE TITLE
complex md can be converted?

### ISSUE THREAD

**Issue by jiaka** [obsidian-html/obsidian-html#334]
![image](https://user-images.githubusercontent.com/56067017/184470424-a4bb14ee-263e-42f4-8ad2-3dd6728d937a.png)

complex md can't be converted?

**Comment by dwrolvink** [comment]
Can you share the frontmatter yaml from the note where it gives this error?
If you don't know on which note this occurs then you can add `-v` to the command to create verbose output.

This is an error that happens quite often, and is caused because Obsidian allows invalid yaml.

**Comment by dwrolvink** [comment]
Closing because of no feedback, just respond here if you get around to it later,  will reopen then
