### ISSUE TITLE
Unable to disable graph

### ISSUE THREAD

**Issue by hgrw** [obsidian-html/obsidian-html#335]
Obsidianhtml version 3.1.0

To reproduce
1. Create trivial obsidianhtml documentation structure, eg `mkdir docs && touch docs/Index.md`
2. Generate config file with `-gc` and point entrypoint to `docs/Index.md`
3. Disable graph

observe `FileNotFoundError: [Errno 2] No such file or directory: '<your filesystem path>/output/html/obs.html/data/search.json.gzip'`

**Comment by dwrolvink** [comment]
I repurposed the graph data for the search feature :face_with_spiral_eyes: 
Gonna fix this tonight somewhere, should be an easy fix.

**Comment by dwrolvink** [comment]
should be fixed now
