### ISSUE TITLE
incorrect conversion == ~~ ^[

### ISSUE THREAD

**Issue by paolomi** [obsidian-html/obsidian-html#339]
I'm testing obsidian-html, it's very good!  The only problem I encountered is the incorrect conversion of the following sentences:

`

Use two equal signs to ==highlight text==.

Any word wrapped with two tildes (like ~~this~~) will appear crossed out.

You can also use inline footnotes. ^[notice that the carat goes outside of the brackets on this one.]

`
Everything else looks perfect. Well done!

source: https://help.obsidian.md/How+to/Format+your+notes

**Comment by dwrolvink** [comment]
Hi Paolomi, thank you!

We can use this issue to add highlighting and strikethrough. 
Shouldn't be too difficult.

The inline footnotes is a different story, I'm using the built-in footnotes extension and that apparently has no support for inline footnotes, so I'll have to edit that extension, which can take a lot of time.

I'm pretty busy at the moment,  so I can't give any estimates on when I'll get around to these.

**Comment by dwrolvink** [comment]
Alright I've added a first version that implements the following testcases:
- https://obsidian-html.github.io/Demonstrations/Getting%20the%20basics%20right.html#!formatting
- https://obsidian-html.github.io/Demonstrations/Implementing%20Footnotes.html

Haven't done much of bughunting yet.
Should be enough for you to try out and see if it fills in your usecase.

Here are the instructions for installing the current master branch code: https://obsidian-html.github.io/Instructions/Install%20a%20different%20version.html

Let me know if you need further instructions for testing, and let me know what you think of this addition.

**Comment by paolomi** [comment]
It works, you're great!!! Thanks a lot!

There is only one little bug with `a particular code`, it easier to show you, I attach a file. Have a look on the last line.
[test.md](https://github.com/obsidian-html/obsidian-html/files/9438097/test.md)

**Comment by dwrolvink** [comment]
@github: "should fix" does not mean "fixes"

**Comment by dwrolvink** [comment]
> It works, you're great!!! Thanks a lot!
> 
> There is only one little bug with `a particular code`, it easier to show you, I attach a file. Have a look on the last line. [test.md](https://github.com/obsidian-html/obsidian-html/files/9438097/test.md)

Weird,  normally the markdown extensions work fine with codeblocks, here the footnotextension gets to the codeblocks first, which is not wanted. I've ported over some code that just removes the codeblocks temporarily, so that this cannot happen anymore. It would be better to fix the order of execution, but I do not possess such arcane knowledge.

This should fix your issue though!

**Comment by paolomi** [comment]
Many thanks! Now it works perfectly: great job!
