### ISSUE TITLE
CreateTemporaryCopy gives multiple '[Errno 21] Is a directory' errors on MacOS

### ISSUE THREAD

**Issue by wealthychef1** [obsidian-html/obsidian-html#355]
## The question
OK, maybe a tad misleading.  I have a large-ish vault, and wish to convert various files in it to html to put on my personal website.  Baby steps!  Let's try it out on a simple single file.  Of course, there are many other files floating around in the vault.  But I wanted to just convert one file as a test.  
When I try, I get this 'copyfile error'.   Not sure why obsidianhtml is trying to copy my entire assets/ subdirectory to a random tmp directory.  
Can anyone point out my problem, or direct me to a forum appropriate to the question?  
I'm sorry about the long lines... 
## The error
```bash
rcook@MacBook-Pro-2021 (Obsidian development ): obsidianhtml -i config.yaml 
> COPYING VAULT /Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault TO /var/folders/jx/xb_hb6h50f95qzrs00rqdkv80000gn/T/tmp16y_mnlh
[('/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/iOS/assets', '/var/folders/jx/xb_hb6h50f95qzrs00rqdkv80000gn/T/tmp16y_mnlh/Knowledge/Computers/iOS/assets', "[Errno 21] Is a directory: '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/iOS/assets'", 'copyfile error')]
[('/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/iOS/assets', '/var/folders/jx/xb_hb6h50f95qzrs00rqdkv80000gn/T/tmp16y_mnlh/Knowledge/Computers/iOS/assets', "[Errno 21] Is a directory: '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/iOS/assets'", 'copyfile error')]
[('/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/iOS/assets', '/var/folders/jx/xb_hb6h50f95qzrs00rqdkv80000gn/T/tmp16y_mnlh/Knowledge/Computers/iOS/assets', "[Errno 21] Is a directory: '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/iOS/assets'", 'copyfile error')]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/obsidianhtml/__init__.py", line 564, in main
    tmpdir = CreateTemporaryCopy(source_folder_path=paths['obsidian_folder'], pb=pb)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/obsidianhtml/lib.py", line 474, in CreateTemporaryCopy
    copytree(source_folder_path, tmpdir.name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/obsidianhtml/lib.py", line 532, in copytree
    raise Error(errors)
obsidianhtml.lib.Error: [('/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/.obsidian', '/var/folders/jx/xb_hb6h50f95qzrs00rqdkv80000gn/T/tmp16y_mnlh/.obsidian', "[Errno 21] Is a directory: '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/.obsidian'", 'copyfile error'), ('/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/iOS/assets', '/var/folders/jx/xb_hb6h50f95qzrs00rqdkv80000gn/T/tmp16y_mnlh/Knowledge/Computers/iOS/assets', "[Errno 21] Is a directory: '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/iOS/assets'", 'copyfile error')]
```
## config.yaml
Here is config.yaml
```yaml
##########################################################################
#                               PATHS                                    #
##########################################################################
# The first folder that contains all obsidian files
# Use full path or relative path, but don't use ~/
obsidian_folder_path_str: '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault' 

# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/iOS/Putting Apple Watch into Sleep mode for respiratory data.md'

```
## Source markdown
The markdown in question: 
```markdown
---
Aliases: [   ]
tags: 
created: 2022-08-31
# Note refactored from [Apple Watch is not collecting respiratory data for AutoSleep app](Apple%20Watch%20is%20not%20collecting%20respiratory%20data%20for%20AutoSleep%20app.md) 
---
#  Putting Apple Watch into Sleep mode for respiratory data
 - Apple appears to require that the watch be put into a special mode called "Sleep" which is of course different from "sleep" as applied to MacOS or iOS. 
1. First set up a sleep schedule in Health, which is just a declarative process; Apple does nothing much with it. 
	1. I suppose being conscious is perhaps the heart of measurement, so this does have a benefit for self discipline, whatever benefit Apple intends.  
2. On the watch, swipe up, select the moon icon
	1. ![200](4F9FC2B4-E310-40AF-AFA6-B9DDA9A3C10B_1_201_a.jpeg)
3. we see that now it presents a choice between "Sleep" and "Do Not Disturb." Choose "Sleep."
	1. ![200](B89FBF45-E83F-444A-B74F-371EB0DB8730.png)
4. Now the Moon has changed to a bed.  
	1. Meaning?  You are sort of "likely to be sleeping" as far as Apple is concerned.  Weird gray area here. 
		1.  ![200](E718F31D-4691-41B3-8D23-D48696EC3F28.png)
5.  The watch now is going to collect respiratory data (all the time? unknown)
6. Autosleep and Health now show the respiratory data. 
7. Support told me, before we were cut off due to poor reception in TJ, that sleep schedules and the Sleep function on the watch functioned as a hint from me to the OS. 
	1.  I didn't get clarity on this point. 
	2. I imagine perhaps taking respiratory measurements uses more power?  < -- speculation
8. Feels a bit like terrible design by Apple.  Needs improvement.  They keep getting the basic things wrong, LOL
```

Thank you!

**Comment by dwrolvink** [comment]
Very interesting error, I know there are other people using obsidianhtml on mac, and I've never seen this error before.

The package first copies the vault to a temp folder for safety reasons, if there are any bugs, then your personal vault is not affected. See for more info: https://obsidian-html.github.io/Configurations/Copy%20vault%20to%20temp%20dir.html

This behavior can be turned off by adding this to your config yaml: 
``` yaml
# Safety feature: make a copy of the provided vault, and operate on that, so that bugs are less likely to affect the vault data. 
# Should be fine to turn off if copying the vault takes too long / disk space is too limited.
# The tempdir is automatically removed on exit of the program.
copy_vault_to_tempdir: False
```

> Note: when you turn on [create index from tags](https://obsidian-html.github.io/Configurations/Create%20index%20from%20tags.html) this will write a note in your vault at `/index.md`. When the copy_vault_to_tempdir setting is enabled it will instead write a note to a temp dir and thus leave your vault unaffected. In your case, it is safe to disable copy_vault_to_tempdir.
 
---

I'd like to fix this bug though, if you have time to help me with that I'd appreciate it.

It looks like it tries to copy the same folder over 3 times. It probably tries to do it 4 times, with the first time succeeding and the other three times failing because the folder already exists. Not sure why it does this. Maybe python fails to read the file names within the folder incorrectly?

I know there are sometimes some errors on macos when copying from one type of filesystem to another. You might try putting your vault on your system disk and try again. If that doesn't fail then at least we know the reason that it is failing and that might help in finding a fix.

I also found that os.walk might work better in some cases. I've implented the copytree function to use this method, and uploaded it to branch shutil_test. You can install it as follows: 
``` bash
pip uninstall obsidianhtml
pip install git+https://github.com/obsidian-html/obsidian-html.git@shutil_test
```

I've added a test string for you to doublecheck whether you are running the updated code. Running `obsidianhtml --test` will give:
```
$ obsidianhtml --test                                                                                                                                   
test 3.2.0 shutil test
```

Let me know whether you can get this to work in that way.
If you just opt to disable the copying to the tempdir, that will be fine too.

**Comment by wealthychef1** [comment]
Thank you.  This gets past the copy stage, but it takes forever on my vault.  
Questions about this:  can I tell it not to copy certain directories, such as .git, which are large and not relevant? 
The copy is so slow I aborted it after a few solid minutes.  
```bash
rcook@MacBook-Pro-2021 (Obsidian development ): obsidianhtml -i config.yaml 
> COPYING VAULT /Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault TO /var/folders/jx/xb_hb6h50f95qzrs00rqdkv80000gn/T/tmpb2csm19c
/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault ['.obsidian', '.trash', '.DS_Store', '.git']
^CTraceback (most recent call last):
blah KeyboardInterrupt
```

**Comment by wealthychef1** [comment]
> This behavior can be turned off by adding this to your config yaml:
> 
> ```yaml
> # Safety feature: make a copy of the provided vault, and operate on that, so that bugs are less likely to affect the vault data. 
> # Should be fine to turn off if copying the vault takes too long / disk space is too limited.
> # The tempdir is automatically removed on exit of the program.
> copy_vault_to_tempdir: True
> ```
> 
>  > Note: when you turn on [create index from tags](https://obsidian-html.github.io/Configurations/Create%20index%20from%20tags.html) this will write a note in your vault at `/index.md`. When the copy_vault_to_tempdir setting is enabled it will instead write a note to a temp dir and thus leave your vault unaffected. In your case, it is safe to disable copy_vault_to_tempdir.

I'm sure you meant "False."  I have opened a new ticket about what happened when I set copy_vault_to_tempdir to False:  https://github.com/obsidian-html/obsidian-html/issues/358

**Comment by dwrolvink** [comment]
Yes my apologies,  that should say false indeed.

> Questions about this: can I tell it not to copy certain directories, such as .git, which are large and not relevant?
Yes you can. It excludes any file that is in a folder listed under `exclude_subfolders`.

This is what is the default setting:
``` yaml
# Exclude subfolders
# These are relative to obsidian_folder_path_str
# To exclude a folder two levels deep, use level1/level2
exclude_subfolders:
  - ".obsidian"
  - ".trash"
  - ".DS_Store"
  - ".git"
```
So .git should already be excluded. Do you see it being copied?
- **edit:** yes, this was a bug, see posts below.

Regarding it being slow: it's not the most efficient piece of code yet, I just wanted to see whether it works at all in the new way. But if it is **that** slow, I'd just disable the feature entirely. I can put the new code in a separate function and have it be configurable, then other mac users can test it at a later point.
- **edit:** this appears to be a common thing on macos when copying between filesystems/disks, this should be better now, see posts below.

**Comment by dwrolvink** [comment]
Alright, I looked into it, and some test code was still present negating the exclude setting.
This has now been fixed.

I've also coded yet another copy method, this should address slow copying times as it uses rsync which should be as close to native copying speeds as we can achieve. According to google, rsync should be present by default on macos and most linux distros.

Like said in the other issue, everything was merged into master. 
Add the following to your config yaml to opt-in to the custom copy method:
``` yaml
# Determines the function to use to copy your vault over to the tempdir.
# `default` will try to use rsync if it is installed, and otherwise use `shutil`
# `rsync` will do the same, but give a warning when it falls back to shutil
# `shutil` will just use shutil to copy. Use this when rsync is installed but is giving problems.
copy_vault_to_tempdir_method: rsync

# Enable to print the files being copied
copy_vault_to_tempdir_follow_copy: true
```

You can disable the second option to reduce spam of course, but might be useful for testing now.

And make sure you are on the master branch:
``` bash
pip uninstall obsidianhtml
pip install git+https://github.com/obsidian-html/obsidian-html.git    
```

```
$ obsidianhtml --test
test 3.2.0 c
```

This should give this output (or similar):
```
> COPYING VAULT /home/user/git/obsidian-html.github.io/__src/vault TO /tmp/tmp28bnb0uf
running: 
         rsync -av /home/user/git/obsidian-html.github.io/__src/vault/ /tmp/tmp28bnb0uf --exclude /.obsidian/ --exclude /testexclude/testexclude2/ --exclude /.trash/ --exclude /.DS_Store/ --exclude /.git/ --exclude /__src/ --exclude /md/ --exclude /obs.html/
Copy succeeded 0 sending incremental file list
./
News.md
ObsidianHtml.md
Automation/
(...)
Resources/mp4/chill_frog.mp4

sent 5,297,054 bytes  received 2,091 bytes  10,598,290.00 bytes/sec
total size is 5,286,985  speedup is 1.00
 b''
< COPYING VAULT: Done
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (/tmp/tmp28bnb0uf/ObsidianHtml.md)
> COMPILING HTML FROM MARKDOWN CODE (/home/user/git/obsidian-html.github.io/md/index.md)
index.md
        > COMPILING INDEX FROM DIR STRUCTURE (/home/user/git/obsidian-html.github.io/obs.html/dir_index.html)
        < COMPILING INDEX FROM DIR STRUCTURE: Done
        > SECOND PASS HTML
        < SECOND PASS HTML: Done
< COMPILING HTML FROM MARKDOWN CODE: Done
> COMPILING RSS FEED
< COMPILING RSS FEED: Done
```

**Comment by dwrolvink** [comment]
So to summarize:
- Install the master branch code
- Your config yaml should look like this:

``` yaml
##########################################################################
#                               PATHS                                    #
##########################################################################
# The first folder that contains all obsidian files
# Use full path or relative path, but don't use ~/
obsidian_folder_path_str: '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault' 

# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/iOS/Putting Apple Watch into Sleep mode for respiratory data.md'

# Determines the function to use to copy your vault over to the tempdir.
# `default` will try to use rsync if it is installed, and otherwise use `shutil`
# `rsync` will do the same, but give a warning when it falls back to shutil
# `shutil` will just use shutil to copy. Use this when rsync is installed but is giving problems.
copy_vault_to_tempdir_method: rsync

# Enable to print the files being copied
copy_vault_to_tempdir_follow_copy: true

# Exclude subfolders
# These are relative to obsidian_folder_path_str
# To exclude a folder two levels deep, use level1/level2
exclude_subfolders:
  - ".obsidian"
  - ".trash"
  - ".DS_Store"
  - ".git"
```

The `exclude_subfolders` value is the default value, so it could be ommitted, but if you want to add more subfolders then it is at least in your config yaml already.

**Comment by dwrolvink** [comment]
Yet another update.

Turns out that on my system the rsync option is way quicker as well. So I've decided to make it the default. Most unix systems should have this utility installed, if it is not present it will fallback to the shutil option.

I've updated the last posts with this in mind.

See https://obsidian-html.github.io/Configurations/Copy%20vault%20to%20temp%20dir.html for a full explanation of the current state.

**Comment by dwrolvink** [comment]
If you at some point get your vault to work, could you also try out `copy_vault_to_tempdir_method: rsync`? Pretty sure it should work now, but I don't have a mac system so no way to test for me. If it works you can just disable it again.

**Comment by wealthychef1** [comment]
> If you at some point get your vault to work, could you also try out `copy_vault_to_tempdir_method: rsync`? Pretty sure it should work now, but I don't have a mac system so no way to test for me. If it works you can just disable it again.

Yes, it's much faster!  Thanks!  I need it for the "create from tags" mode.

**Comment by dwrolvink** [comment]
Great! Getting there! The well of bugs must be nearly dry now :joy:

**Comment by wealthychef1** [comment]
> Great! Getting there! The well of bugs must be nearly dry now 😂

Haha yes but the well of my ignorance runs deep!  Stay tuned for some newbie DAQs (dumb-ass questions) in other issues!  👶

**Comment by wealthychef1** [comment]
> > If you at some point get your vault to work, could you also try out `copy_vault_to_tempdir_method: rsync`? Pretty sure it should work now, but I don't have a mac system so no way to test for me. If it works you can just disable it again.
> 
> Yes, it's much faster! Thanks! I need it for the "create from tags" mode.

Spoke too soon.  On my linux server, it is very slow to run rsync.  This will force me to do my web dev on my Mac, which I guess is fine, but thought you would like to know this data point.

**Comment by dwrolvink** [comment]
Very interesting, I'm running linux too. Do you simply have a HDD in there instead of an SSD. Is copying by hand much faster?
As the comments state, you could try `copy_vault_to_tempdir_method: shutil` and see if that works better on linux. That would entail two different config yamls between the two systems, but that is life I guess.

**Comment by wealthychef1** [comment]
> Very interesting, I'm running linux too. Do you simply have a HDD in there instead of an SSD. Is copying by hand much faster?
> As the comments state, you could try `copy_vault_to_tempdir_method: shutil` and see if that works better on linux. That would entail two different config yamls between the two systems, but that is life I guess.

I tried shutil and it is also slooow.  
Looks like it's a hard drive ATA mounted.  
I think it's OK to do my work on the mac and sync with git.  I'd be doing git syncs anyhow.

```bash
root@linode (html (master)): hdparm -I /dev/sda

/dev/sda:

ATA device, with non-removable media
Standards:
	Likely used: 1
Configuration:
	Logical		max	current
	cylinders	0	0
	heads		0	0
	sectors/track	0	0
	--
	Logical/Physical Sector size:           512 bytes
	device size with M = 1024*1024:           0 MBytes
	device size with M = 1000*1000:           0 MBytes 
	cache/buffer size  = unknown
Capabilities:
	IORDY not likely
	Cannot perform double-word IO
	R/W multiple sector transfer: not supported
	DMA: not supported
	PIO: pio0 
```
