### ISSUE TITLE
KeyError: 'Putting Apple Watch into Sleep mode for respiratory data.md'

### ISSUE THREAD

**Issue by wealthychef1** [obsidian-html/obsidian-html#358]
## Background
Using the same vault as in https://github.com/obsidian-html/obsidian-html/issues/355, but now my config.yaml includes

```yaml
copy_vault_to_tempdir: False
```

## The error
```bash
rcook@MacBook-Pro-2021 (Obsidian development ): obsidianhtml -i config.yaml 
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/iOS/Putting Apple Watch into Sleep mode for respiratory data.md)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/obsidianhtml/__init__.py", line 720, in main
    ep = pb.files[pb.paths['obsidian_entrypoint'].name]
KeyError: 'Putting Apple Watch into Sleep mode for respiratory data.md'
```

**Comment by dwrolvink** [comment]
Wow you have a knack for finding bugs that should've popped up already ages ago.

The code for loading in the first note was wrong, causing it to work only if that first note is in the root of the vault, which was not the case for you.

You can install the master branch again: 

``` bash
pip uninstall obsidianhtml
pip install git+https://github.com/obsidian-html/obsidian-html.git
```

That should fix this issue.

**Comment by wealthychef1** [comment]
> Wow you have a knack for finding bugs that should've popped up already ages ago.

Yes, I think that's true.  For me, though, this is the simplest use case -- just convert a file properly... 

> 
> The code for loading in the first note was wrong, causing it to work only if that first note is in the root of the vault, which was not the case for you.
> 
> You can install the master branch again:
> 
> ```shell
> pip uninstall obsidianhtml
> pip install git+https://github.com/obsidian-html/obsidian-html.git
> ```
> 
> That should fix this issue.

Not yet, I'm afraid... using 3.2.0 c

```bash 
rcook@MacBook-Pro-2021 (.obsidian.macos (master)): pip install git+https://github.com/obsidian-html/obsidian-html.git
...
Successfully installed lxml-4.9.1 obsidianhtml-3.2.0
rcook@MacBook-Pro-2021 (Obsidian development ): obsidianhtml --test
test 3.2.0 c
rcook@MacBook-Pro-2021 (Obsidian development ): obsidianhtml -i config.yaml 
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/iOS/Putting Apple Watch into Sleep mode for respiratory data.md)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/obsidianhtml/__init__.py", line 719, in main
    ep = pb.files[paths['rel_obsidian_entrypoint'].as_posix()]
KeyError: 'Knowledge/Computers/iOS/Putting Apple Watch into Sleep mode for respiratory data.md'
```

**Comment by dwrolvink** [comment]
Okay I have no clue what is going on. 

I've added a toggle so that we have the program print out every key that it knows of, maybe that will give some clues. 
Update the code like before and add this to your config:

``` yaml
toggles:
  debug_filetree_keys: True
```

And please share the output here when you run obsidianhtml.

**Comment by dwrolvink** [comment]
> Yes, I think that's true. For me, though, this is the simplest use case -- just convert a file properly...

Yeah this must not be a great experience

If at all possible,  you could also share your vault,  or at least the part of it to recreate this, and your config, and then I can try if it works on my system at least.

**Comment by dwrolvink** [comment]
Running:
``` bash
cat '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/iOS/Putting Apple Watch into Sleep mode for respiratory data.md'
```
Does give you the contents of the file back? (Just to double check, not the first time you get caught on something small)

**Comment by wealthychef1** [comment]
> Okay I have no clue what is going on.
> 
> I've added a toggle so that we have the program print out every key that it knows of, maybe that will give some clues. Update the code like before and add this to your config:
> 
> ```yaml
> toggles:
>   debug_filetree_keys: True
> ```
> 
> And please share the output here when you run obsidianhtml.

I would like to share privately as it lists every file in my vault.  Is there a way to PM you?  I'm new around here.  :-). Thanks

**Comment by wealthychef1** [comment]
> Running:
> 
> ```shell
> cat '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/iOS/Putting Apple Watch into Sleep mode for respiratory data.md'
> ```
> 
> Does give you the contents of the file back? (Just to double check, not the first time you get caught on something small)

Aha, this is the problem -- I had a glitch in the pathname. 
It now completes, but does not parse the images... perhaps this is another bug? I'll start another issue if it is supposed to include the images from the original markdown... :-)

**Comment by dwrolvink** [comment]
ah thank god, this was driving me crazy :smile: 

yes that would be a different bug most probably, a different issue is good.

>  Is there a way to PM you? I'm new around here. :-). Thanks

Not as far as I know on github.
You can reach me at github@dwrolvink.com

I guess the easiest would be to create a private repo here and add me as a collaborator.
But we can talk more via the mail probably.

**Comment by wealthychef1** [comment]
> ah thank god, this was driving me crazy 😄
> 

Apologies!  My bad

> yes that would be a different bug most probably, a different issue is good.
> 

Done, new issue created.  

> You can reach me at [github@dwrolvink.com](mailto:github@dwrolvink.com)

Nothing now to PM you about.  But thanks for the contact info and the quick responses and help.
