### ISSUE TITLE
No such file or directory: '/Users/jcolson/src/personal/DragonHearts/output/md/Personal/httpd.service'

### ISSUE THREAD

**Issue by jcolson** [obsidian-html/obsidian-html#36]
looks like the markdown made a link out of something that wasn't a link, which confused the html conversion

```
MarkdownLink(
        url = "httpd.service", 
        suffix = '.service', 
        isValid = True, 
        isExternal = False, 
        inRoot = True, 
        src_path = /Users/jcolson/src/personal/DragonHearts/output/md/Personal/httpd.service, 
        rel_src_path = Personal/httpd.service, 
        rel_src_path_posix = Personal/httpd.service, 
        page_path = /Users/jcolson/src/personal/DragonHearts/output/md/Personal/renew-certificates---lets-enc.md, 
        root_path = /Users/jcolson/src/personal/DragonHearts/output/md 
)
Traceback (most recent call last):
  File "/usr/local/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 529, in main
    ConvertMarkdownPageToHtmlPage(unparsed[k]['fullpath'], pb)
  File "/usr/local/lib/python3.9/site-packages/obsidianhtml/__init__.py", line 118, in ConvertMarkdownPageToHtmlPage
    shutil.copyfile(link.src_path, paths['html_output_folder'].joinpath(link.rel_src_path))
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jcolson/src/personal/DragonHearts/output/md/Personal/httpd.service'
```

**Comment by dwrolvink** [comment]
I see the PR. Did you just link to a file that doesn't exist, or is this a kind of workaround?

**Comment by jcolson** [comment]
> I see the PR. Did you just link to a file that doesn't exist, or is this a kind of workaround?

in this case, there is NO file ... the ORIGINAL markdown in Obsidian looked like this:

```
...
systemctl restart httpd.service
...
```

the markdown conversion made it look like this:
```
systemctl restart [httpd.service](httpd.service)
```

even though, it wasn't really a link, just text.

so I just 'worked around' the error in the html conversion; not sure if this would break other links?  but if the file doesn't exist, there really isn't much you can do except change how the md conversion works I think?

**Comment by dwrolvink** [comment]
Ahh yes, that is done here: 
https://github.com/obsidian-html/obsidian-html/blob/8383af761be76bd57561028ec5547b5d35bbc0b6/obsidianhtml/MarkdownPage.py#L263-L268

This was added because Obsidian does this too (kind of).
It's clear that the regex needs to be more specific.

Will start working on that fix

**Comment by dwrolvink** [comment]
Okay that should avoid this issue. Your PR on this issue is also nice to have for if anything else goes wrong in the future.
