### ISSUE TITLE
LaTeX implementation looks weird

### ISSUE THREAD

**Issue by camargomau** [obsidian-html/obsidian-html#370]
Hey!

After trying countless free Obsidian Publish alternatives, this is the only one that can render all of my LaTeX expressions flawlessly. So huge props for that. Not sure what the others are doing that seem to get it wrong with certain longer expressions.

However, the LaTeX rendering (which I see is using MathJax) looks rather... weird. It seems it's not using the "standard" font that's normally used to render LaTeX.

This is how it renders for me (this is a screenshot directly from the demo page):

![image](https://user-images.githubusercontent.com/52770775/188320420-bf780b1e-2ff7-4d7b-b212-ed4b8fa9532e.png)

…while this is how it should normally render like:

![image](https://user-images.githubusercontent.com/30291690/166919408-e6506965-6bbf-41b9-9a62-4574ed1e0868.png)

(I took this second image from @dwrolvink's response at issue #239)

Here's another example of how it renders for me, this time in a note of mine:

![image](https://user-images.githubusercontent.com/52770775/188320566-d462ad4c-bf8b-403b-9098-651787f6cdde.png)

…and how that same note looks on Obsidian:

![image](https://user-images.githubusercontent.com/52770775/188320601-5b852c01-c765-4c3b-9717-25527e91cf41.png)

Am I doing something wrong? Do I need to install a font? Do I need to modify some CSS/HTML?

Thanks!

**Comment by dwrolvink** [comment]
The css just uses the first font it finds on your system out of a defined list. For me it's a good font (Linux Manjaro with extra fonts installed) and for you it apparently uses a less good one. 

For me on android phone it looks like this for example

![Screenshot_2022-09-04-18-02-53-118_org mozilla firefox](https://user-images.githubusercontent.com/30291690/188322770-2065d607-b24d-4c86-82d7-a2e3d5e6a1a6.jpg)

The fix for this would be to package a font into the site and then configure mathjax to use it, then it would look more or less the same on every system. Would you know a font that is best for this purpose by chance?

**Comment by dwrolvink** [comment]
Also interesting, it seems mathjax has some built-in fonts somehow, I guess it's not as simple a story as I just stated, but I'm sure there is some tweaking we can do. 

https://docs.mathjax.org/en/latest/output/fonts.html

What system are you on? (OS and version)?

**Comment by dwrolvink** [comment]
Alright, turns out I was loading the mathjax not according to spec, and considering how much magic it pulls, that interfered with loading the fonts correctly.

For me it went from:
![image](https://user-images.githubusercontent.com/30291690/188327292-315109de-0392-4898-9094-691fe856ce82.png)

To:
![image](https://user-images.githubusercontent.com/30291690/188327253-35e60c86-2211-466e-83e5-9f085541d3dd.png)

You can see for yourself at https://obsidian-html.github.io/Demonstrations/Implementing%20Latex.html

I've pushed the changes to master in this pr: https://github.com/obsidian-html/obsidian-html/pull/371

**Comment by dwrolvink** [comment]
I see now that it breaks other stuff, working on it

**Comment by dwrolvink** [comment]
> After trying countless free Obsidian Publish alternatives, this is the only one that can render all of my LaTeX expressions flawlessly. So huge props for that. 

Funny, I just copy pasted mathjax code into this project and it worked, never looked more into it than that.

Now I have a working version though, with prettier fonts. But there are apparently a lot of features that can be turned on/off, so if you have more usecases that now stopped working, share some examples and I'll add them to the page so I can assure they work.

**Comment by dwrolvink** [comment]
Now updated:  https://obsidian-html.github.io/Demonstrations/Implementing%20Latex.html (ctrl+shift+r if it doesn't reload correctly, at least on firefox for me)

**Comment by camargomau** [comment]
Alright, just installed the latest build, deployed my site locally and yep, it's now rendering nicely just like on that page, both on Windows (11, build 22622.590, Firefox 104.0.1) and Android (12L, Firefox 105.0b4). 

Going through my notes, I haven't found anything that looks broken yet. The only issue I see is when there are two centered blocks one after the other, like so:

```
$$\text{block 1}$$
$$\text{block 2}$$
```

A screenshot of how that renders:

![image](https://user-images.githubusercontent.com/52770775/188330159-28fa8025-d7a4-406c-a027-f3abedef6eeb.png)

This was happening previously already and it's an easy fix in my notes (I just need to add an empty line between them) though, so no worries if you can't find a way to fix it.

I'll going through my notes to see if I find anything else that is still broken. Thanks for the quick fix!

**Comment by dwrolvink** [comment]
Yeah I'm not big on mathjax, so if it doesn't work on Obsidian I don't really have any positive example of where it does work. I'd like to keep the behavior between the two systems as similar as possible.

Happy it works for you! Will close this issue, if you find anything don't hesitate to post it here and I'll open it again.

**Comment by camargomau** [comment]
Just found that `$\centernot$` isn't being recognised at all:

![image](https://user-images.githubusercontent.com/52770775/188330456-815853eb-77ce-4be3-8a19-19bec2969060.png)

It does work on Obsidian, but since it's a rather obscure expression it's probably fair that it doesn't work (it also didn't work in any of the other Publish-alternatives I tried). 

`$\not$` does seem to be working fine and I can just use that instead:

![image](https://user-images.githubusercontent.com/52770775/188330574-18fd7000-04ef-41c7-93a1-7affe72f5e2d.png)

Edit: I forgot to put the LaTeX between \` and even GitHub couldn't render `$\centernot$`, so yeah, it's probably too obscure

**Comment by dwrolvink** [comment]
that was quick lol
this update adds that for me

**Comment by camargomau** [comment]
I can confirm it is working:

![image](https://user-images.githubusercontent.com/52770775/188331060-635bf9d0-4be8-4a1b-9d0e-d12735ccf2cc.png)

Thanks once again for the quick fix! 

I have also noticed that when viewing the site in tabs mode, LaTeX expressions aren't being rendered in any pane but the first one:

![image](https://user-images.githubusercontent.com/52770775/188331226-9db9dd4c-67bb-4c5b-a253-9ffa91bc10f7.png)

This is probably an entirely different issue so I can open another one, if you wish.

**Comment by dwrolvink** [comment]
No that's fine in this one, known issue with tabs mode

**Comment by dwrolvink** [comment]
Happy to learn someone uses the tabs layout by the way. It was the whole inspiration for this project (when I found this website https://notes.andymatuschak.org/Evergreen_notes), and it was the default for this project for quite some time until feature after feature request made it clear that documentation layout was a more sensible default :smile: 

But yeah nowadays I mostly use my own package to compile the documentation site for the package itself, so the tabs layout is not tested as much as the documentation layout anymore.

The fix should be in the latest commit, you can try it out.

**Comment by camargomau** [comment]
Seems to be working great, thanks! 

By the way, non-related, but is there a way to make the note title (either the filename or the title field in the YAML metadata) show up at the top of the note? I used to add a level 1 heading at the top of the note, but then opted to use the Embedded Note Title plugin in Obsidian to not "waste" a heading level.

Sorry if I'm being too picky lol, just trying to publish my notes and make them look nice while not having to modify the actual notes too much before publishing.

**Comment by dwrolvink** [comment]
Not yet, but shouldn't be too hard to add. Just make a separate issue for it, as it will take some work to get right.

Closing this until other latex issues are found.

**Comment by dwrolvink** [comment]
Doublecentered blocks worked for me in Obsidian, so I added the fix to obsidianhtml too.

https://obsidian-html.github.io/Demonstrations/Implementing%20Latex.html#!double-centered-block
