### ISSUE TITLE
Integrate embedded note title plugin

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#376]
As discussed in #370 

@Psycake

**Comment by dwrolvink** [comment]
It is currently enabled by default, but in the future adding this setting to your yaml might be necessary:

``` yaml
toggles:
  features:
    embedded_note_titles:
      enabled: True
```
When this feature is enabled it will look whether folder `{obsidian_folder_path_str}/.obsidian/plugins/obsidian-embedded-note-titles` exists. If it does not the feature is disabled anyways, otherwise it will try to load in the data.json in that folder to load in the plugin settings. It will then add `<embeddedtitle>{title.capitalize()}</embeddedtitle>` at the top of each note, unless the settings tell it not to.

At time of writing all the settings should be implemented except for "daily note title format".

![image](https://user-images.githubusercontent.com/30291690/188447561-47ef9dc9-e31d-4efc-9729-6e4586d70943.png)

Latest code in master, let me know if it works for you.

**Comment by camargomau** [comment]
Can confirm this is working great! You can check out my site [here](https://psycake.github.io/notkesto), btw.

**Comment by dwrolvink** [comment]
Very cool to see, can I list it among the examples (once I have a list of them)?

**Comment by camargomau** [comment]
Sure! Would love to see it used as an example :)
