### ISSUE TITLE
whike processing callouts, the "minus" (-) is treated properly, but the "plus" (+) is ignored

### ISSUE THREAD

**Issue by jcolson** [obsidian-html/obsidian-html#394]
```
> [!quote]+ Parchment Scroll with Seal
> Hail to thee of might and valor.
```

is not 'foldable' (should start un-folded) once in html format.  however

```
> [!quote]- Parchment Scroll with Seal
Hail to thee of might and valor.
```

is foldable. (starts folded)

**Comment by dwrolvink** [comment]
Totally missed this when implementing callouts, will add it soon

**Comment by dwrolvink** [comment]
fixed https://obsidian-html.github.io/Demonstrations/Implementing%20Call-outs.html#!folded-note

because I found a serious bug, it is already in a new version (3.2.1)
