### ISSUE TITLE
Adding material UI

### ISSUE THREAD

**Issue by bhickta** [obsidian-html/obsidian-html#411]
# No a functionality but it will look much much better
* Options
 * Material UI
 * Bootstraps

**Comment by dwrolvink** [comment]
Could you eleborate? The request is not clear to me.

**Comment by bhickta** [comment]
Changing the css code to incorporate elements of "Material UI" or "Bootsrap"
* Example - mkdocs https://blacksmithgu.github.io/obsidian-dataview/

Elements like - header, footer, search bar

Just want UI enhancement not in functionality ..

**Comment by dwrolvink** [comment]
You can add your own css to make your site as pretty as you want, and when needed, you can even export one of the standard layouts and edit it to how you want it. See for both this page: https://obsidian-html.github.io/Configurations/Styling/Edit%20HTML,%20CSS,%20JS.html

My aim is to get output that is similar to what one gets in Obsidian. 
Getting exactly the look and feel that you like is out of scope for this project. As that seems to be your request here I am closing this.

**Comment by dwrolvink** [comment]
(you can implement exactly the look and feel that you want yourself, and if we lack functionality in that regard we can look at it of course)
