### ISSUE TITLE
Nested header code-inclusion doesn't work

### ISSUE THREAD

**Issue by Programmerino** [obsidian-html/obsidian-html#416]
For example, ``![[Callaghan '22#Extracts#1]]`` displays nothing (in fact, it seems to prevent the rest of the section from displaying as well) while ``![[Callaghan '22#1]]`` works as expected. Both forms are allowable in Obsidian.

**Comment by dwrolvink** [comment]
Yes this is not implemented yet because I did not know it was a thing.
Will pick this up.

**Comment by dwrolvink** [comment]
Should be fixed with the latest PR. I don't have any usecases other than a demonstration example, so further testing might be required.

**Comment by Programmerino** [comment]
That change seemed to work for my files, thanks!
