### ISSUE TITLE
Embedded PDF documents and unhandled filetypes

### ISSUE THREAD

**Issue by Programmerino** [obsidian-html/obsidian-html#421]
Currently, it doesn't seem like obsidian-html supports using the `![[file.ext]]` syntax for embedded PDF documents or unhandled filetypes (e.g. HTML files).

In Obsidian, PDF files seem to just be wrapped in an iframe, and unhandled filetypes embeds are just converted into buttons which open the files with the default app handler. I think the best way to handle this for the web is just to open the file in a new tab. I think this is preferable to the current way it is handled with "Error including file or not a markdown file"

**Comment by dwrolvink** [comment]
https://obsidian-html.github.io/Demonstrations/Parsing%20Images,%20videos,%20and%20audio.html#!pdfs

> Certain suffixes can now be added to the embeddable_file_suffixes list in the config yaml. This will cause the ![file] record to be altered to <embed src="file" width=90%" height:700px">.
The default suffix is pdf, though it would also be possible to include html inline this way.

Adding a button for any other included files that are not recognized must still be implemented.

**Comment by dwrolvink** [comment]
Alright change of plans. 

Obsidian has a nice (and surprisingly short) list of supported file types: 
https://help.obsidian.md/Advanced+topics/Accepted+file+formats

I've made sure to implement all of these in the latest PR.
So any file that can be included in a page in Obsidian will be includable in obsidianhtml websites.

Any other filetype can be linked to using markdown links, which is also the only way that will work in Obsidian.

So no more "this file type is not a md file" errors, and if you do get it, add the suffix to `embeddable_file_suffixes` and then it will be wrapped in an embed tag and then it is the browsers challenge to render it.

I think this fills in this US, so closing. 
Let me know if there is anything else to be said, then I'll open it again.
