### ISSUE TITLE
Pandoc citation support

### ISSUE THREAD

**Issue by Programmerino** [obsidian-html/obsidian-html#422]
I think this could be a feature toggle which would run an additional processing pass during the markdown compilation to resolve pandoc-style citations. I imagine the easiest way to do this would be to directly run `pandoc` on the markdown files when citation support is enabled. After some testing, I found that
```
pandoc -s in.md --wrap=preserve -f markdown-blank_before_header-smart  --citeproc -t markdown-citations-smart-escaped_line_breaks
```
made the least amount of changes to the generated markdown while resolving the citations. It should be noted, however, that it does break some things. For example, code blocks without preceding newlines are turned into normal text, and the same goes for some unordered lists. As long as it's opt-in, I think this is a fair price to pay

**Comment by dwrolvink** [comment]
I've been thinking a bit about this.

It would be nice to be able to do, but it feels too specific, a little bit out of scope.

Perhaps I should introduce extensions, where we can call an external extension at certain points in the code, like after the markdown has been processed and before the html will be generated, passing in information such as the output folder, list of files, etc.

Then that extension can do whatever it wants, and when it is ready, obsidianhtml can continue.

Obviously a pretty big project. To get that working.

An alternative is to write a script where you compile only the markdown from your vault, then you invoke your pandoc oneliner on the md output, and then you run obsidianhtml again on your markdown folder to generate the html.

See for these:
- [toggles/compile_md](https://obsidian-html.github.io/Configurations/Configuration%20Options.html#!compile-md)
- [toggles/compile_html](https://obsidian-html.github.io/Configurations/Configuration%20Options.html#!compile-html)
