### ISSUE TITLE
Inclusions are not shown in graph views

### ISSUE THREAD

**Issue by Programmerino** [obsidian-html/obsidian-html#425]
If you use the `![[note]]` syntax in a note, the reference to the other document is not shown in any graph view. This is not the case in Obsidian

**Comment by dwrolvink** [comment]
![image](https://user-images.githubusercontent.com/30291690/208245368-5921aaa7-6b7c-4436-90c9-481e84c574aa.png)

Inclusions now show up as dotted edges in the graph view.
If not desired, then this can be turned off using:

``` yaml
    graph:
      show_inclusions_in_graph: False
```

**Comment by Programmerino** [comment]
Seems like it works as expected! Thanks!
