### ISSUE TITLE
Support "Strict Line Breaks"

### ISSUE THREAD

**Issue by Jachimo** [obsidian-html/obsidian-html#428]
Although Obsidian defaults to preserving intra-paragraph newlines, it has an option called "Strict Line Breaks" which makes it behave more like stock Markdown (or LaTeX, or HTML, etc.), where newlines in the input are ignored (and new paragraphs are signified by a blank line, i.e. `\n\n`).

It seemed like it'd be nice if obsidian-html supported vaults and notes created with this option, which would require _not_ adding `<br/>` tags inside paragraphs at the end of physical lines in the input.

From looking at the code it doesn't appear this is currently configurable, and as I need it for my vault anyway, I will work on putting together a PR to add it.

**Comment by Jachimo** [comment]
See commit 1401c49e1b0fc785d55a71141abc01a71cb2f7ea in Jachimo:feature/428-strict-line-breaks and associated PR #429.

**Comment by dwrolvink** [comment]
Thank you for your pr! I've merged it and applied the code convention.
