### ISSUE TITLE
Image names with both parens and spaces don't convert

### ISSUE THREAD

**Issue by atomicbird** [obsidian-html/obsidian-html#430]
I'm just getting started with this project-- thanks, it's exactly what I was looking for!

A few of my images are getting `Image {l} treated as external and not imported in html` while converting:

```
/home/pi/.local/lib/python3.9/site-packages/obsidianhtml/ConvertVault.py:887: UserWarning: Image John Spafford (d 1697 treated as external and not imported in html
  warnings.warn(f"Image {l} treated as external and not imported in html")
/home/pi/.local/lib/python3.9/site-packages/obsidianhtml/ConvertVault.py:887: UserWarning: Image Spofford Monument (back treated as external and not imported in html
  warnings.warn(f"Image {l} treated as external and not imported in html")
/home/pi/.local/lib/python3.9/site-packages/obsidianhtml/ConvertVault.py:887: UserWarning: Image John A. Tone (1836-1864 treated as external and not imported in html
  warnings.warn(f"Image {l} treated as external and not imported in html")
```

I noticed that this affected all images with parens in the file name, and no other images. Renaming images and updating the Markdown to match resolves the problem. For what it's worth, Markdown files with parens in their name work fine.

I'm using version 3.2.3 installed with `pip` yesterday.

**Comment by dwrolvink** [comment]
I've tracked it down to an issue mostly about spaces.

When the link was converted from obsidian format to proper markdown, the resulting image url was not urlencoded. This was added for normal links, but never done for image links. This causes spaces in the proper markdown link which is out of spec. The error message was mostly a red herring, it seems to me. Maybe you can confirm.

Anyways, it should be working now for any combination of spaces, parentheses, and the combination of the two.

You can test out the latest version by [installing the master branch](https://obsidian-html.github.io/Instructions/Install%20a%20different%20version.html#!install-master-branch).

**Comment by atomicbird** [comment]
That did it, thank you very much
