### ISSUE TITLE
"Address already in use" not detected

### ISSUE THREAD

**Issue by atomicbird** [obsidian-html/obsidian-html#441]
If I use `obsidianhtml run`, press enter to stop the server, then run it again quickly, the server sometimes can't start because the port is still reserved. That's normal for Unix systems, I think. However obsidianhtml doesn't notice this and still says the server is available for use.

When this happens, the `obsidianhtml run` output ends with:

```
OBSHTML: Started webserver at http://localhost:8888/ hosting from /private/tmp/output/html/notebook (Ctrl+C to exit)
Traceback (most recent call last):
  File "/usr/local/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/obsidianhtml/__init__.py", line 41, in main
    ServeDir()
  File "/usr/local/lib/python3.10/site-packages/obsidianhtml/Serve.py", line 51, in ServeDir
    httpd = socketserver.TCPServer(("", int(port)), Handler)
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use

Open your webbrowser and navigate to http://localhost:8888/notebook/ to view your website

Press enter to stop hosting website and exit obsidianhtml run.
```

I don't think there's anything obsidianhtml can do about the port being in use but it would be good if its messages reflected the situation better.

**Comment by dwrolvink** [comment]
Thanks for the issue. I had noticed this before, but focussed on avoiding this error upon quickly exiting and restarting. Apparently I was unsuccesful in that. But having a different process hogging the port is not to be avoided anyways of course.

Though jthis is a different point. I've added a check to see if the process is still running after 0.5 seconds, which is a good indicator of this error (it will exit immediately if the port is occupied).

So the confusing contradiction in output should now no longer occur.
