### ISSUE TITLE
Image scaling do not work

### ISSUE THREAD

**Issue by Spiralo-Idioide** [obsidian-html/obsidian-html#443]
I have tried to scale images and the feature do no seem to be working.
I have tried both `![100](img.png)` and `![[img.png|200]]`.

I have no configuration enabled, I don't have any custom css or anything, just a test vault with 2 notes.

I am not sure if I missed something in the documentation.

**Comment by dwrolvink** [comment]
This is correct, Obsidian notes are converted to proper markdown and then to html. Proper markdown does not support resizing. The resizing part in the documentation means that very large images are resized to the width of the page, not that defined widths are respected.

A "feature" that was implemented earlier is that obsidianhtml does not bork itself when a width is present in the image url. This fix just throws away this suffix.

Though proper markdown does allow html within it, so I might be able to add the images with a width suffix as an html tag. This will require some work though.

**Comment by dwrolvink** [comment]
So, it turns out that this change was way easier than expected, I've got the basic usecase of `![[bla.jpg|300]]` working.

[install the latest master version](https://obsidian-html.github.io/Instructions/Install%20a%20different%20version.html#!install-master-branch) to try it out. Let me know if this works for you.

**Comment by Spiralo-Idioide** [comment]
Just tested and it works perfectly. 

Except inside tables, but inserting non-scaled images inside tables is also not reliable (it's the same for notes).

**Comment by dwrolvink** [comment]
Hi Spiralo,
 
Try adding a backslash in front of the `|` when inside a table. 
So e.g. `![[wide-image.jpg\|300]]` instead of `![[wide-image.jpg|300]]`

**Comment by Spiralo-Idioide** [comment]
Yes you are right that makes total sense. But I still have some problems with tables, I'll open an other issue for that

Thank you a lot for being so fast to answer and everything and maintaining this awesome project.
