### ISSUE TITLE
Github Pages Deployment

### ISSUE THREAD

**Issue by zubayrali** [obsidian-html/obsidian-html#448]
Hello,

Thank you for making this tool, this is everything anyone will ever need for BASB/Digital Garden needs.

This is what my file tree looks like:

```
├── config.yml
├── deploy.sh
├── .gitignore
├── output
│   ├── archive
│   ├── areas
│   ├── favicon.ico
│   ├── .git
│   ├── inbox
│   ├── index.html
│   ├── md
│   ├── not_created.html
│   ├── obs.html
│   ├── projects
│   └── sources
├── serve.py
└── vault
    ├── archive
    ├── areas
    ├── bin
    ├── inbox
    ├── index.md
    ├── .obsidian
    ├── projects
    └── sources
```

I am using the [Auto push site using Git on Linux](https://obsidian-html.github.io/Automation/AutomationLinuxGit.html) script that you provided which looks like this: 

```bash
# Config
git_output="/home/igloo/example_vault/output"
obsidian_folder="/home/igloo/example_vault/vault"
root_folder="/home/igloo/example_vault/"

# Move to output folder and make sure it is up to date
cd $git_output
git pull

# Remove all files except .git/ and README.md
echo "Will delete previous output:"
find . ! -path "./.git/*" ! -name ".git" ! -name README.md
echo "Continue? (y/n)"
read yn

if [ "$yn" != "y" ]; then
    echo "Aborted"
    exit 0
fi

find . ! -path "./.git/*" ! -name ".git" ! -name README.md -delete


# Convert Obsidian to HTML
cd $root_folder
obsidianhtml -i ./config.yaml
# ^ the config file will output the html to $git_output

if [ $? -ne 0 ]; then
    echo "Python script failed. Exited."
    exit 1
else
    echo "Successfully created html code"
fi

# Push changes
cd $git_output
mv html/* ./
rm -rf html/

git add . --all
git commit -m "autopush"
git push 
```

Lastly, `config.yaml` looks like:

```yaml
obsidian_folder_path_str: vault
obsidian_entrypoint_path_str: vault/index.md
html_output_folder_path_str: output/html
md_entrypoint_path_str: output/md/index.md
md_folder_path_str: output/md
...other options
```
I've pushed the `output` dir  to a new GitHub repo: [zubayrrr/vault](https://github.com/zubayrrr/vault) and enabled GitHub Pages but for whatever reason, it is not working: [https://zubayrrr.github.io/vault/](https://zubayrrr.github.io/vault/).

Locally **it is working as expected**, I am running `python3 ./serve.py` that looks like this: 

```py
import os
import http.server
import socketserver
PORT = 8085

os.chdir('output')

Handler = http.server.SimpleHTTPRequestHandler
Handler.extensions_map.update({
      ".js": "application/javascript",
})

httpd = socketserver.TCPServer(("", PORT), Handler)
httpd.serve_forever()
```

Could you please share the `config.yaml` that you used for [https://obsidian-html.github.io/](https://obsidian-html.github.io/)

Also `obsidianhtml -i path/to/config.yaml` isn't working, it throws:

```bash
~/example_vault                                                                                                                                         
❯ obsidianhtml -i /home/igloo/example_vault/config.yaml -v

Could not locate the config file /home/igloo/example_vault/config.yaml.
  Please try passing the exact location of it with the `obsidianhtml -i /your/path/to//home/igloo/example_vault/config.yaml` parameter.
```

This could be because I am using `Python 3.8.10` - still trying to get Python 3.9 to work on my `Ubuntu 20.04.5 LTS x86_64` I will edit this issue once I resolve that.

A massive thank you once again.

Update: I fixed the Python version issue, it gives the same error when using `obsidianhtml -i` even for Python 3.9.15.

Update 2: IDK why I didn't try a relative path but `obsidianhtml -i ./config.yaml` seems to be working fine.

**Comment by dwrolvink** [comment]
Hi Zubayrrr,

Thanks for the kind words, and good news, you are almost there.

You posted this config.yml:
```
obsidian_folder_path_str: vault
obsidian_entrypoint_path_str: vault/index.md
html_output_folder_path_str: output/html
md_entrypoint_path_str: output/md/index.md
md_folder_path_str: output/md
...other options
```

This would work fork deploying to the root of the repo, so then the url would be: https://zubayrrr.github.io
But you are exporting your site to a folder, this means that all the links need to be updated.

This can be done via [html_url_prefix](https://obsidian-html.github.io/Configurations/Configuration%20Options.html#!html-url-prefix)

So that would mean your config.yaml should look like this:
```
obsidian_folder_path_str: vault
obsidian_entrypoint_path_str: vault/index.md
html_output_folder_path_str: output/html
md_entrypoint_path_str: output/md/index.md
md_folder_path_str: output/md
html_url_prefix: '/vault'

...other options
```

Let me know if that fixes it for you.

**Comment by zubayrali** [comment]
I was so close! Adding `html_url_prefix` fixed this.

Thank you :)
