### ISSUE TITLE
Limit depth for following links

### ISSUE THREAD

**Issue by wealthychef1** [obsidian-html/obsidian-html#453]
I'd like to tell obsidianhtml to parse the base file and its links to a certain depth and no further.  So a depth of 1 would mean only follow to the direct children of the root file.  Depth of 2 means go out to the children's children, and so forth. 
thanks!

**Comment by dwrolvink** [comment]
That should be exceptionally easy to implement, and a nice feature.

**Comment by dwrolvink** [comment]
``` yaml
# Number of links a note can be removed from the entrypoint note
# -1 for no max depth
# 0 means only the entrypoint note is processed
# 1 means only direct children are processed (and the entrypoint of course)
# and so forth. NOTE: DOES NOT APPLY TO INCLUSIONS!
max_note_depth: -1
```

That should do it.
Give it a go and let me know how this works for you.

**Comment by wealthychef1** [comment]
Perfect, works in my test case as I would want.  Thank you

**Comment by Gewerd-Strauss** [comment]
> ```yaml
> # Number of links a note can be removed from the entrypoint note
> # -1 for no max depth
> # 0 means only the entrypoint note is processed
> # 1 means only direct children are processed (and the entrypoint of course)
> # and so forth. NOTE: DOES NOT APPLY TO INCLUSIONS!
> max_note_depth: -1
> ```

Quick question, is it possible that this is not part of the documentation? Couldn't find it, and forgot that auto-created MOC's have the tendency of suddenly inserting my entire vault in an export :P

Addendum: How does one put into effect an edited yaml config file? The docs are not detailed on that regard.

**Comment by Gewerd-Strauss** [comment]
Quick question 2: Is it possible (/should I create a new issue?) to exclude any note containing a specific tag, or a specific frontmatter tag?  The aforementioned MOC's basically traverse the entire vault, but their naming scheme is irregular so I cannot easily target them. However, they are also the only notes containing the `#toc`-tags in the `tags:`-frontmatter field.
