### ISSUE TITLE
getting started with development

### ISSUE THREAD

**Issue by zubayrali** [obsidian-html/obsidian-html#477]
Hello,

I wanted to develop/experiment a custom layout but I don't know how to use this python package locally with the HTML/CSS I plan on writing.

Would really appreciate your help in getting started with this. I've forked this repo locally, I've a bunch of .md files, I need to know how to use this package locally.

Thanks in advance.

**Comment by dwrolvink** [comment]
Will post more tomorrow, but just to get you started, cd into the root of the cloned repo, then run:
``` bash
python -m obsidianhtml -i path/to/config.yml
```

That should then use the local files. You can run `pip uninstall obsidianhtml ` to be completely sure.

See https://obsidian-html.github.io/Configurations/Styling/Edit%20HTML%2C%20CSS%2C%20JS.html for starting with customizing html

Note also this setting: https://obsidian-html.github.io/Configurations/Tweaking/Export%20vault%20files%20to%20html%20output.html


Let me know what topics you would like more pointers on, or more specific questions that you might have.

**Comment by zubayrali** [comment]
Thank you so much, this should be enough to get me started.

**Comment by dwrolvink** [comment]
Good luck, I'm closing this issue.
If you have more questions a good place to ask them is here: https://github.com/obsidian-html/obsidian-html/discussions
