### ISSUE TITLE
How can you use create_index_from_dir_structure with a site generated from a sub-folder?

### ISSUE THREAD

**Issue by erikwestra** [obsidian-html/obsidian-html#479]
Hi, I've been looking at using ObsidianHTML to generate a couple of websites based on specific folders in my vault.  So far, I'm really liking what I see in ObsidianHTML, and would love to be able to use it, but I've hit a bit of a snag.

I've had no luck at all getting the `create_index_from_dir_structure` option working where the website is not at the root of the vault.  It seems that ObsidianHTML (or at least the "run" command) automatically searches for the vault and disregards the `obsidian_folder_path_str`, so the generated index tree starts from the root of my vault and contains entries that aren't relevant to the site I'm trying to generate.

I'm looking for some way to have the left sidebar only show subdirectories within the specified folder.  I use a single vault for everything, and want to generate a website (including the navigation sidebar) based only on the contents of one particular folder.  Is there some way of doing this?

Thanks!

**Comment by dwrolvink** [comment]
This has been implemented very recently, so to do this you'll have to install from git, but it is possible.

By the way, `obsidianhtml run` automatically updates obsidian_folder_path_str to the vault root because that should be its value. The run command was added to help users configuring the config.yml, so it enforces some values. I don't know what version you are on, but with older versions you can use `obsidianhtml convert -i config.yml` and set a different folder, but know that it is not officially supported so you might run into weird bugs when you do that. (On the newer versions this will give you an error when the configured value is not the root, also with convert.)

Coincidentally I've added a new filtering system because there were more people wanting to *only export certain folders*. 
For this first install the git code: https://obsidian-html.github.io/Instructions/Install%20a%20different%20version.html#!install-master-branch

``` bash
pip uninstall obsidianhtml
pip install git+https://github.com/obsidian-html/obsidian-html.git
```

To now only export folder 'A', you can add this to the config.yml that you use:
``` yaml
included_folders:
  - A
```

See [filtering notes](https://obsidian-html.github.io/Configurations/Modes/Filtering%20notes.html) for more information.

This will allow `obsidian_folder_path_str` to be correctly configured to the vault root and for you to still only export the notes under that one folder.

Let me know if this solves your issue. If not you can share your vault/an example vault with explanation on which folders you want to output to which site and I can test out/setup an example config that you can use.

**Comment by erikwestra** [comment]
[Sorry for the delay in replying...I was travelling over the weekend and only got to look at this again today]

Thanks, @dwrolvink -- unfortunately that makes no difference.  I did exactly what you suggested, and the result is exactly the same.  I created a test vault that only includes the folder structure I'm trying to get -- a subfolder for my websites with the various websites listed, and then a `config.yaml` file specifically for each site with a site-specific directory tree navigation down the side.

Here's what the generated website currently looks like:

![image](https://user-images.githubusercontent.com/515597/204702763-cc36eb3b-94a6-4746-a9e5-4cb598f349d4.png)

It looks like the directory tree is always starting at the root of the entire vault, rather than the specified sub-directory.  I don't want to see the **Websites**, **site-1** and **src** entries in my directory tree -- just the entries within the specified directory (ie, for this test site I only want to see **sub-page** and **index**).  As far as the generated website is concerned, it shouldn't matter whereabouts in my vault I place my website source files -- I don't want users seeing that I have a "Websites" folder, etc as that's just really confusing.

At present, it's almost as if I have to put my website's Markdown source files and directories at the root of my vault so that the directory tree only shows the website's contents without it being wrapped up in all the intervening folders.  But I'm trying to add my website to a large existing vault with tons of existing files and folders, so I want the websites in a subfolder rather than at the vault root.

If it helps at all, here's a copy of the Obsidian vault used to create this site:

[ObsidianHTML-test.zip](https://github.com/obsidian-html/obsidian-html/files/10119203/ObsidianHTML-test.zip)

To build it, I just "cd"d into the **site-1** sub-directory and typed `obsidianhtml run -i config.yaml`, then opened the browser to the suggested URL.

Any suggestions?

 - Erik.

**Comment by dwrolvink** [comment]
You say you added the obsidian vault used to create the site, but inside the zip I find this:

```
└── ObsidianHTML-test
    ├── Private Note.md
    └── Websites
        ├── site-1
        │   ├── config.yaml
        │   ├── output
        │   │   ├── html
        │   │   │   ├── favicon.ico
        │   │   │   ├── index.html
        │   │   │   ├── not_created.html
        │   │   │   ├── obs.html
        │   │   │   │   ├── data
        │   │   │   │   ├── dir_index.html
        │   │   │   │   ├── dirtree.html
        │   │   │   │   ├── rss
        │   │   │   │   ├── static
        │   │   │   │   │   ├── dirtree.js
        │   │   │   │   │   ├── dirtree.svg
        │   │   │   │   │   ├── encoding.js
        │   │   │   │   │   ├── external.svg
        │   │   │   │   │   ├── hashtag.svg
        │   │   │   │   │   ├── load_dirtree_footer.js
        │   │   │   │   │   ├── master.css
        │   │   │   │   │   ├── mermaid.9.0.1.min.js
        │   │   │   │   │   ├── mermaid.9.0.1.min.js.map
        │   │   │   │   │   ├── mermaid.css
        │   │   │   │   │   ├── obsidian_core.js
        │   │   │   │   │   ├── Roboto-Regular.ttf
        │   │   │   │   │   ├── rss.svg
        │   │   │   │   │   ├── SourceCodePro-Regular.ttf
        │   │   │   │   │   └── taglist.css
        │   │   │   │   └── tags
        │   │   │   │       └── index.html
        │   │   │   └── src
        │   │   │       └── The Geyserland Classic.html
        │   │   └── md
        │   │       ├── index.md
        │   │       └── src
        │   │           └── The Geyserland Classic.md
        │   ├── src
        │   │   ├── main.md
        │   │   └── sub-page.md
        │   ├── template-full.html
        │   └── template.html
        └── site-2
```

This is either not your vault, or something really weird happened.
Anyways, the site-2 folder is completely empty, so if you goal was to only output site-1 content then it seems like you've succeeded?

> **Edit:** I looked at it a bit better, and it's clear that the whole output folder should not be there. You shouldn't run obsidianhtml inside of your vault. Go to a folder **outside** of your vault and then run obsidianhtml there. I see now that the old default method does have [the warning not to do this](https://obsidian-html.github.io/Instructions/Quickstart.html#!convert-vault), but the run method above it doesn't. Will need to add a check in the run method to not allow this.

I've changed the example vault here: https://github.com/obsidian-html/example_vault/tree/main/vault
You can see there two folders, site1, and site2. I've put one internal link in each folder (link to another note in the same folder), and one link to the other folder.

Then see https://github.com/obsidian-html/example_vault/blob/7734dfe89165a00475922e29a46ba6911949c221/include_only_site1.yml#L1 :

``` yaml
# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Can be absent when toggles/compile_md == False
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: 'vault/Site1/Site 1 Homepage.md'

# When not an empty list, this setting will restrict the subfolders
# of the vault that will be included. This allows you to ensure that 
# only those folders are included in the output. Links pointing to notes
# outside of the included folders will be treated as non-existent.
# Note that the obsidian_entrypoint_path_str needs to be in one of these folders.
# Paths should be relative to the vault root.
included_folders:
  - Site1
```
 
This gives me an output folder with a `md` folder and an `html` folder.
Looking in the `md` folder we see what we want to see:
```
.
├── index.md
└── Site1
    └── Site 1 Page.md
```

To recreate this at home, go to a folder where you don't mind stuff being created, and then:
``` bash
# force reinstall obsidianhtml to newest version
pip uninstall obsidianhtml
pip install git+https://github.com/obsidian-html/obsidian-html.git

# post the output of this command in the issue, just to double check
obsidian version

# download the example vault and go into the folder
git clone git@github.com:obsidian-html/example_vault.git
cd example_vault

# convert the vault to md and html
obsidian convert -i include_only_site1.yml 

# show markdown output
tree output/md
```

Let me know if that brings you to where you have a working example at least.

**Comment by erikwestra** [comment]
Hi dwrolvink,

Thanks for that -- your example vault is useful, though of course my vault structure is more complicated than that.  The vault I gave you was a test one I created, as I can't send you my complete vault as it includes many thousands of files, 99% of which aren't relevant to the website and includes confidential work notes.

I did indeed only create the "site1" example, as I didn't need "site2" to show the issue.

It's easy enough to rejig my obsidianHTML config to store the generated output outside of the vault itself, but that doesn't fix anything, I'm afraid.

Using your test vault, I was able to build just the "site1" source files using `include_only_site1.yml` file you supplied -- and yes, that only includes that particular subset of files.  But unfortunately the directory tree is still showing the full path from the root of the vault down to the Markdown source files, and none of those directories are opened so you have to open the manually each time you go to view the site.

Here's what your example vault shows in the directory tree when first going to the site:

<img width="524" alt="Screen Shot 2022-12-05 at 5 42 56 PM" src="https://user-images.githubusercontent.com/515597/205551288-d3a9f910-dbc2-4d31-9729-a873650282c5.png">

The user has to click on the "Site1" item to open it and see the contents of the site:

<img width="524" alt="Screen Shot 2022-12-05 at 5 44 04 PM" src="https://user-images.githubusercontent.com/515597/205551357-8b4917ba-29fe-4974-862c-70f246347e8a.png">

This is confusing for users, as I want to use the directory tree as the central navigation for the site, and having to drill down to view the site's contents in the navigation sidebar is really confusing for users.

The thing is, it gets even worse if you put your site inside a subfolder.  I used your example vault to recreate the directory structure I have, with my vault containing a single "Websites" directory, and then the site-specific source files inside a sub-directory under the "Websites" directory:

```
My Vault
    <all the other contents of my vault, not related to the websites I want to generate>
    Websites
        Site1
            <site 1 source files>
        Site 2
            <site 2 source files>
```

(by the way, because of the complexity of my vault I'm actually thinking of storing the "Websites" directory in another sub-directory within my vault, like maybe `Resources/Websites/Site1`).

Because I placed my website source files further down the directory tree, your directory tree listing requires the user to drill down multiple times before they can view the contents of the website, ie:

<img width="524" alt="Screen Shot 2022-12-05 at 5 48 47 PM" src="https://user-images.githubusercontent.com/515597/205551918-1f72af5f-a97b-491d-b306-35e60f48e579.png">

then:

<img width="524" alt="Screen Shot 2022-12-05 at 5 48 53 PM" src="https://user-images.githubusercontent.com/515597/205551938-bf75cba1-c56a-4a87-89bf-6c627671fd62.png">

and then finally:

<img width="524" alt="Screen Shot 2022-12-05 at 5 49 01 PM" src="https://user-images.githubusercontent.com/515597/205551956-2c942b85-b99b-4470-9e80-b04821d7768a.png">

The user has to click twice just to see the contents of the website in the navigation sidebar.

To be able to make a publishable website from my Markdown sources, I really need some way of having the navigation sidebar how the website contents without even having to click once, let alone having to click twice.  I should be able to see my navigation options (like the "Site 1 page" in your example vault) immediately upon going to the site, without having to drill down.

It seems that your directory tree view is always hardwired to start at the root of the vault, regardless of where the user has placed the source files for the generated site.  Is there any way of having the navigation sidebar only show files within a particular sub-directory (I initially thought that was what the `obsidian_folder_path_str` setting would do, though clearly it doesn't)?

If the directory tree doesn't support this, is there some other way of providing a navigation sidebar for a website without all those intervening directory levels showing up?

Thanks!

 - Erik.

**Comment by dwrolvink** [comment]
Ooohh so everything works just fine, it is just very inconvenient. I thought it just didn't work at all.

Yes this is expected behavior. The `obsidian_folder_path_str` input only exists because I did not know when starting out how to figure out what the root of the vault was.

The usecase that you are describing sounds like this: "I want to take any subfolder of my Obsidian vault and export it like it is its own vault".

I can add this, though it will take some time to get right. This feature will mean that you can give a subfolder path, much like `include_folders`, but this feature will accept only one path. Only files in (and under) that folder will be loaded (just like include_folders), but all the paths will be rewritten so as to point to the root of the site. This should solve your issue I think?

Normally I would say to just create a second vault, but looking at the user requests I've been getting I'm pretty sure that you are not the only one that would like something like this, and I get the wish to have everything in one vault and then just to export a subset of it.

Funny how one feature begs the next. When I started out there was no directory structure view, that is actually pretty recent. So until then the note paths really didn't matter much.

**Comment by erikwestra** [comment]
Thanks @dwrolvink -- that's exactly what I need to be able to use ObsidianHTML with my setup.

Basically, I'd like to be able to replicate the type of left sidebar navigation structure used in [your documentation site](https://obsidian-html.github.io) but with having the source files embedded in a (possibly-nested) sub-folder.

Thanks!

**Comment by sevmonster** [comment]
I was surprised that this feature didn't exist. In my situation, I am [running `obsidianhtml` on `inotify`](https://github.com/obsidian-html/obsidian-html/discussions/582) for my vault, so any changes are immediately replicated. It was as simple as adding an empty `.obsidian` directory to the desired folder depth. Unless there are files being read in the `.obsidian` directory, I don't think adding an option for this feature is necessarily required, though my solution does feel hacky.

**Comment by dwrolvink** [comment]
That is a great idea actually. This does not give any issues within Obsidian?

**Comment by sevmonster** [comment]
Not that I can see, unless you were to try opening the subfolder as a vault of course.

**Comment by dwrolvink** [comment]
documentation added: https://obsidian-html.github.io/instructions/tutorials/converting-just-one-subfolder-in-your-vault.html

**Comment by sevmonster** [comment]
I would recommend adding some clarificarion that:
- ObsidianHtml does not read any data from the `.obsidian` folder, so the blank folder only serves to tell ObsidianHtml where to stop looking for the root folder;
- Obsidian desktop/mobile does not look into subdirectories for `.obsidian`, so it does not harm the normal user experience.

Both questions have come up so it would be good to make it clear.

**Comment by dwrolvink** [comment]
I can't promise that obsidianhtml will never look (or try to look) in the .obsidian folder because settings are normally stored there that now already inform the defaults of some of the settings. In the future we might start leaning more on that. So kind of gray area there.

I'll add the second point :+1:

**Comment by dwrolvink** [comment]
https://obsidian-html.github.io/instructions/tutorials/converting-just-one-subfolder-in-your-vault.html updated
