### ISSUE TITLE
Make a copy of the obsidian vault to a temp dir to avoid data loss in case of bugs

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#48]
I just overwrote a note of mine working on a new feature.

Now I can burn myself on my own stupidity, I don't want others to suffer the same fate.
(Edit: just found out I made a backup yesterday so all is fine!)

Should be pretty easy. OS specific troubles might be challenging potentially.

**Comment by dwrolvink** [comment]
Implemented, works very well on linux as far as I can tell, but I can't steal my girlfriends laptop to test this atm.

Might fetch my work laptop later to test this there.

**Comment by dwrolvink** [comment]
Tested on Windows, works like a charm when Onedrive is not slow like butter.
Had to copy it to a local drive, maybe that would've been fixed after the first access, but well. The feature is configurable if anyone has issues with it.

**Comment by jcolson** [comment]
interesting side note:  this changes the order of tagged entry-point content --- what used to be in order of creation date, is no longer.

**Comment by dwrolvink** [comment]
You say it is a side note, but you reopened the issue, is there something specific that you want to have tested/implemented?

There is a way to sort the files on creation date, but that doesn't work with `copy_vault_to_tempdir: True` because there isn't really a way to copy over creation time, at least not on Linux as far as I can tell. We can sort on last accessed/last modified time though.

Another option would be to use a tag like date, e.g. I have this in my template note:
``` yaml
---
tags:
- date/{{date}}
---
```
We could fetch those tags, and sort on that.

Otherwise, we could get it to work if you have `copy_vault_to_tempdir: False`. Atm the notes should be returned randomly, so interesting that it was sorted for you always until now.

In any case I think this should be a new issue.

**Comment by jcolson** [comment]
yeah, sorry, re-opened so that it would remind me to open a different issue to allow for sorting by date.

I, too, use date tags in my frontmatter:

ex:

```md
---
title: Green Staff
created: 2022-01-15T15:26:07+00:00
tags: [ dh-item ]
updated: 2022-02-06T22:59:26+00:00
---
```
(updated/created) ... so I'll add a different feature issue to allow for specifying frontmatter data to use as a sorting method
