### ISSUE TITLE
markdown tables to html?

### ISSUE THREAD

**Issue by welpdx** [obsidian-html/obsidian-html#483]
Hey bro,

Markdown tables aren't being converted to html or something. V 3.3.1

![img](https://i.imgur.com/zJwLZjy.png)

My current fix is to just put it in a `markdown code block` or converted to html using this [table generator](https://www.tablesgenerator.com/html_tables). 

(btw, I love your plugin, putting up an issue no hate all love)

**Comment by welpdx** [comment]
just noticed that the tables on your site is not working as well. Something happened!
https://obsidian-html.github.io/Configurations/Features/Features.html

**Comment by welpdx** [comment]
I uninstalled and reinstalled using `pip install obsidianhtml`. With this version V3.3.0, my tables are back in working order! 

So the problem is a change that happened between V3.3.1 and V3.3.0. 

![mah my tables are back!](https://i.imgur.com/M1wBZlg.png)

**Comment by dwrolvink** [comment]
Wowww I was working on a user story of this guy that wanted to allow newlines in a table, and I had to pause it so I disabled the custom table code, but I never reactivated the standard table code...

At least it was an easy fix. It should work now again for you.

**Comment by welpdx** [comment]
just ran the line `pip install git+https://github.com/obsidian-html/obsidian-html`
current obsidianhtml v3.3.1 doesnt have this update I guess.

Thanks for the quick reply! Can't wait for your next update!

**Comment by dwrolvink** [comment]
Apologies, busy at work, my brain is applesauce. I needed to run the PR, not just git push to my own branch.

**Comment by welpdx** [comment]
Hey no worries man! Thank you so much for updating it! (lol brain is applesauce)

<br><br><br>


<p><font size = "6">
I get how work can turn the brain into applesauce, <br>
bruise them like a peach you gotta need gauze<br>
Bro pushed to branch but forgot to PR<br>
my man's gotta hop in a car and chillax at at a bar<br>
 </font></p>

**Comment by dwrolvink** [comment]
:rofl:
