### ISSUE TITLE
Show name of entrypoint note in navigation sidebar

### ISSUE THREAD

**Issue by erikwestra** [obsidian-html/obsidian-html#486]
Sorry to pester you again...I can't figure out how to change the name of the index note in the navigation sidebar.  I've created a standalone vault for the time being for one of my sites.  The vault looks like this:

<img width="1196" alt="Screen Shot 2022-12-08 at 8 26 37 AM" src="https://user-images.githubusercontent.com/515597/206276905-8378bc99-1785-427a-906d-d868d726b67e.png">

I then compiled the site using ObsidianHTML, with my "Welcome" note as the entrypoint and using `create_index_from_dir_structure` to generate the left navigation sidebar.  Here's what it looks like:

<img width="767" alt="Screen Shot 2022-12-08 at 8 09 16 AM" src="https://user-images.githubusercontent.com/515597/206274225-76381ac9-6693-426f-b575-31aa861a01dc.png">

Am I right in guessing that the word "index" (circled in red in the above image) is hardwired?  My entrypoint note is called "Welcome" but in the navigation sidebar it appears as "index".

Is there some way of having ObsidianHTML use the name of the entrypoint note in the sidebar, or somehow specifying an alternative label for that entry in the sidebar?  Non-technical users of the generated website won't really know what "index" means and I'd rather call it something like "Welcome" or "Home" if possible.

Thanks!

**Comment by dwrolvink** [comment]
Good point.

I've added it in the latest PR.

1. [Install latest master code](https://obsidian-html.github.io/Instructions/Install%20a%20different%20version.html#!install-master-branch)
2. To set the value that you want, add this to your config yaml, making sure to merge it with possible existing config.

``` yaml
toggles:
  features:
    create_index_from_dir_structure:
      enabled: True
      homepage_label: "Welcome"
```

**Comment by erikwestra** [comment]
Wow, thanks -- that works perfectly!
