### ISSUE TITLE
Single-line callouts don't work

### ISSUE THREAD

**Issue by erikwestra** [obsidian-html/obsidian-html#488]
In Obsidian, it's possible to have a one-line callout with no additional text, like this:

```
> [!warning] This is a warning.
```

This gets rendered like this:

<img width="1357" alt="Screen Shot 2022-12-09 at 11 12 30 PM" src="https://user-images.githubusercontent.com/515597/206678607-67b7926c-07ea-490e-9d88-eed8f3a607f8.png">

In ObsidianHTML, it isn't recognised as a callout and is rendered like this:

<img width="1357" alt="Screen Shot 2022-12-09 at 11 14 31 PM" src="https://user-images.githubusercontent.com/515597/206679072-3fdf33c7-5f71-47f1-b504-dcb6af3b9ed8.png">

Could you possibly add support for single-line callouts at some stage?

**Comment by dwrolvink** [comment]
Should be a pretty easy fix.

**Comment by dwrolvink** [comment]
Try it now

**Comment by erikwestra** [comment]
This works perfectly now -- thank you!
