### ISSUE TITLE
image tags with alt text don't get parsed by the findall regex

### ISSUE THREAD

**Issue by jcolson** [obsidian-html/obsidian-html#49]
image isn't getting the path correct ...
```
[2022-02-07 15:38:33] ERROR `/media/D_D-DragonHeart-Dec-15,-2021-18-31-57-GMT-image1.png' not found.
```

```
<p><img alt="Cost Inspiration Points Eff ect Alter your roll by +1 Alter teammates roll by +1 Alter the DMS roll by+/- 1 " src="../../media/D_D-DragonHeart-Dec-15,-2021-18-31-57-GMT-image1.png" />   </p>
```

where the rest of the images are good:

```
<p><img alt="" src="/output/html/media/D_D-DragonHeart-Dec-15%2C-2021-18-31-57-GMT-image2.jpeg" />   </p>
<p><img alt="" src="/output/html/media/D_D-DragonHeart-Dec-15%2C-2021-18-31-57-GMT-image3.jpeg" />   </p>
```

**Comment by dwrolvink** [comment]
- does the image exist in the same folder as the others?
- are they all linked to by the same note, or different notes?
- is the discrepancy in the links already present in the markdown output, or only in the html?

Can't find the ERROR {url} not found. string in my code Is that something you've added in recently?

**Comment by jcolson** [comment]
> Can't find the ERROR {url} not found. string in my code Is that something you've added in recently?

no, sorry, this was from my webserver during testing

found the issue, was with meta text within `![ HERE ]()`causing the issue with the regex.

**Comment by dwrolvink** [comment]
I'll take your word for it :smile:
