### ISSUE TITLE
Add scroll bar to table of contents pane

### ISSUE THREAD

**Issue by hgrw** [obsidian-html/obsidian-html#496]
A lot of my documentation tends to have many headings. In many cases the table of contents pane ends up truncated. Would it be possible to have a scroll bar here? Without a scroll bar, the table of contents pane is not feasible in my use-case unfortunately.

**Comment by dwrolvink** [comment]
Vertical scrolling works as expected for me so I'm assuming you're talking about horizontal scrolling

There are multiple options, such as setting a max-width, that would have as effect that we go from

![image](https://user-images.githubusercontent.com/30291690/208269385-7598aefb-4349-4f51-b72a-c3c8a683246a.png)

to 

![image](https://user-images.githubusercontent.com/30291690/208269418-3a650994-0022-491e-b6e1-85a6378a9cb5.png)

Which, in my simple test, would work pretty well without a scrollbar.
Maybe you can share a screenshot if this is not what you'd like for your setup.

**Comment by hgrw** [comment]
Interesting. Scrolling on the right hand side pane works, but not on the left. I have flipped my panes to show TOC on the left. My toggles are
<pre><font color="#33C7DE"><b>toggles</b></font><font color="#FFD7D7">:</font>
  <font color="#33C7DE"><b>features</b></font><font color="#FFD7D7">:</font>
    <font color="#33C7DE"><b>styling</b></font><font color="#FFD7D7">:</font>
      <font color="#33C7DE"><b>add_toc</b></font><font color="#FFD7D7">:</font> <font color="#C061CB">True</font>   <font color="#33C7DE"> # add &quot;[TOC]&quot; (Table of Contents) when missing</font>
      <font color="#33C7DE"><b>toc_pane</b></font><font color="#FFD7D7">:</font> <font color="#C061CB">True</font>
      <font color="#33C7DE"><b>flip_panes</b></font><font color="#FFD7D7">:</font> <font color="#C061CB">True</font>
      <font color="#33C7DE"><b>accent_color</b></font><font color="#FFD7D7">:</font> <font color="#C061CB">&apos;#0c004b&apos;</font>
</pre>

Can confirm that when I set flip_panes to false I get both scroll bars back. Also, there is a clue. There is no minimise button (<,>) when scroll is missing.

**Comment by dwrolvink** [comment]
I am able to scroll on both sides.

**Comment by hgrw** [comment]
Hmm. I will look into it a bit more and report back during the week.

**Comment by dwrolvink** [comment]
Ah yes I can replicate it with `flip_panes: True` 
There is some js shenannigans going on, worked on different parts in different times, sure the culprit is in there somewhere.

**Comment by dwrolvink** [comment]
lmao

``` python
        # Set pane divs
        toc_pane_div = "right_pane_content"
        content_pane_div = "left_pane_content"
        if pb.gc('toggles/features/styling/layout') == 'documentation' and pb.gc('toggles/features/styling/flip_panes'):
            toc_pane_div = "left_pane"
            content_pane_div = "right_pane_content"
```

changed to 

``` python
        # Set pane divs
        toc_pane_div = "right_pane_content"
        content_pane_div = "left_pane_content"
        if pb.gc('toggles/features/styling/layout') == 'documentation' and pb.gc('toggles/features/styling/flip_panes'):
            toc_pane_div = "left_pane_content"
            content_pane_div = "right_pane_content"
```

Typical bug. 
Though this did fix the bug of not being able to scroll / missing folder, the alignment was pretty bad when flipping the panes over.

Did some fixing there too.
Works pretty well for me now.

**Comment by hgrw** [comment]
Nice, thanks!
