### ISSUE TITLE
Convert not including subfolder when converting md to html

### ISSUE THREAD

**Issue by dbraun31** [obsidian-html/obsidian-html#506]
I'm trying to convert a directory containing .md files to an html site structure using `obsidianhtml convert`. The .md directory contains a subdirectory, containing an image that's referenced in one of the .md files. Here's a little example of the file structure:

```
.
├── md
│   ├── experiment-2-theory.md
│   ├── figures
│   │   └── unnamed-chunk-1-1.png
│   ├── homepage.md
│   ├── measurement.md
│   └── stimuli.md
├── rmd
│   ├── bayes-play.Rmd
│   ├── experiment2-theory.Rmd
│   └── stan-file.stan
├── tmp.txt
└── to_html
    ├── compile.sh
    ├── config.yaml
    ├── links.txt
    └── output
```

`./md/experiment-2-theory.md` references `./md/figures/unnamed-chunk-1-1.png`. 

Inside `./to_html`, I'm running the command `obsidianhtml convert -i config.yaml`, and the contents of `config.yaml` are:

```
# The first folder that contains all obsidian files
# Use full path or relative path, but don't use ~/
obsidian_folder_path_str: '/home/dave/Dropbox (Lehigh University)/post_doc/professional/projects/gaita/ideation/structured/md/' 

# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: '/home/dave/Dropbox (Lehigh University)/post_doc/professional/projects/gaita/ideation/structured/md/homepage.md'

html_url_prefix: '/gaita/ideation/structured/html/'

toggles:
  process_all: True
```

The output of running the `obsidianhtml convert -i config.yaml` command is as follows:

```
> COPYING VAULT /home/dave/Dropbox (Lehigh University)/post_doc/professional/projects/gaita/ideation/structured/md TO /tmp/tmpaqunt9l5
running: 
	 rsync -a /home/dave/Dropbox (Lehigh University)/post_doc/professional/projects/gaita/ideation/structured/md/ /tmp/tmpaqunt9l5 --exclude /.obsidian/ --exclude /.trash/ --exclude /.DS_Store/ --exclude /.git/
Copy succeeded 0  b''
< COPYING VAULT: Done
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (/tmp/tmpaqunt9l5/homepage.md)
	> FEATURE: PROCESS ALL
	< FEATURE: PROCESS ALL: Done
> COMPILING HTML FROM MARKDOWN CODE (/home/dave/Dropbox (Lehigh University)/post_doc/professional/projects/gaita/ideation/structured/to_html/output/md/index.md)
		 File figures/unamed-chunk-1-1.png not located, so not copied. @ /tmp/tmpaqunt9l5/experiment-2-theory.md
	> FEATURE: PROCESS ALL
	< FEATURE: PROCESS ALL: Done
	> COMPILING INDEX FROM DIR STRUCTURE (/home/dave/Dropbox (Lehigh University)/post_doc/professional/projects/gaita/ideation/structured/to_html/output/html/obs.html/dir_index.html)
	< COMPILING INDEX FROM DIR STRUCTURE: Done
	> SECOND PASS HTML
	< SECOND PASS HTML: Done
< COMPILING HTML FROM MARKDOWN CODE: Done

You can find your output at:
	md: /home/dave/Dropbox (Lehigh University)/post_doc/professional/projects/gaita/ideation/structured/to_html/output/md
	html: /home/dave/Dropbox (Lehigh University)/post_doc/professional/projects/gaita/ideation/structured/to_html/output/html
```
If I'm interpreting the backend correctly here, it looks like the rsync copy to `/tmp` may not be copying the `./md/figures/` directory causing this error when trying to convert to html: ` File figures/unamed-chunk-1-1.png not located, so not copied. @ /tmp/tmpaqunt9l5/experiment-2-theory.md` ?

This is a really puzzling issue because this feature is working in this app in another Obsidian vault on my computer, and I could swear it was working earlier today and I'm not sure what would have changed.

Anything else I can provide to help you diagnose the issue?

**Comment by dwrolvink** [comment]
Interesting that it does not say the same when going from obsidian --> markdown. 
Does the file exist in `to_html/output/md/figures` ?
If so, what does the link to the image look like in `to_html/output/md/experiment-2-theory.md`?

If I understand correctly, you are exporting "normal" markdown to html here? Not obsidian markdown?

What does the link to the image look like in `md/experiment-2-theory.md`? And does your issue get solved when you change it to either of the types below?
``` md
![[unnamed-chunk-1-1.png]]
![](figures/unnamed-chunk-1-1.png)
```

If not, does adding a link to the image, like below, make the image appear in the html output?
``` md
[[unnamed-chunk-1-1.png]]
[link to image](figures/unnamed-chunk-1-1.png)
```

**Comment by dbraun31** [comment]
You are correct that the app Obsidian isn't involved in this workflow, For this application, I'm either manually making these `md` docs or knitting them from RMarkdown, but I'm trying to preserve Obsidian style in the `md` docs as much as possible so it'll be compatible with obsidian-html. 

After running the convert function in the way I specified above, there is no `figures` dir created in the `to_html/output/md` directory. Here's the tree of `output` after running the conversion:

```
.
├── html
│   ├── bayes-play.html
│   ├── experiment-2-theory.html
│   ├── favicon.ico
│   ├── index.html
│   ├── measurement.html
│   ├── not_created.html
│   ├── obs.html
│   │   ├── data
│   │   │   ├── graph.json
│   │   │   └── search.json.gzip
│   │   ├── dir_index.html
│   │   ├── dirtree.html
│   │   ├── graph
│   │   │   └── index.html
│   │   ├── rss
│   │   ├── static
│   │   │   ├── 3d-force-graph.js
│   │   │   ├── default_grapher_2d.js
│   │   │   ├── default_grapher_3d.js
│   │   │   ├── dirtree.js
│   │   │   ├── dirtree.svg
│   │   │   ├── encoding.js
│   │   │   ├── external.svg
│   │   │   ├── flexsearch.bundle.js
│   │   │   ├── graphers
│   │   │   │   ├── 2d.js
│   │   │   │   └── 3d.js
│   │   │   ├── graph.js
│   │   │   ├── graph.svg
│   │   │   ├── hashtag.svg
│   │   │   ├── load_dirtree_footer.js
│   │   │   ├── master.css
│   │   │   ├── mermaid.9.0.1.min.js
│   │   │   ├── mermaid.9.0.1.min.js.map
│   │   │   ├── mermaid.css
│   │   │   ├── obsidian_core.js
│   │   │   ├── pako.js
│   │   │   ├── Roboto-Regular.ttf
│   │   │   ├── rss.svg
│   │   │   ├── search.js
│   │   │   ├── search.svg
│   │   │   ├── SourceCodePro-Regular.ttf
│   │   │   └── taglist.css
│   │   └── tags
│   │       └── index.html
│   └── stimuli.html
├── md
│   ├── bayes-play.md
│   ├── experiment-2-theory.md
│   ├── index.md
│   ├── measurement.md
│   └── stimuli.md
└── summary.txt

9 directories, 45 files
```

So the file `md/experiment-2-theory.md` is the output of a knit function from RMarkdown. The link to the image changes depending on my settings during the knit. Currently that `md` file links to the image in html style:

`<img src="figures/unnamed-chunk-1-1.png" title="plot of chunk unnamed-chunk-1" alt="plot of chunk unnamed-chunk-1" style="display: block; margin: auto;" />`

Changing that link to `![[unnamed-chunk-1-1.png]]` is successful! I get `output/html/figures/unnamed-chunk-1-1.png`, and it displays correctly on my website after uploading.

Changing that link to `![](figures/unnamed-chunk-1-1.png)` creates a `figures` directory in `output/md` but not `output/html`.

Adding a link like this:

```
[[unnamed-chunk-1-1.png]]
[link to image](figures/unnamed-chunk-1-1.png)
```
again adds a `figures` dir in `output/md` but not `output/html`.

I should note that I made a workaround writing a shell script that just manually copies the `figures` folder to the output html, which works fine because the link to the image in the html file is intact. So for my purposes, this is no longer an issue. I'm happy to help you keep troubleshooting if you want to get to the bottom of it, but I realize that my use case of generating `md` from `.Rmd` is a non standard one and might not be one you're concerned about.

Either way, this is a super useful app and I really appreciate all the efforts you've put into it.

**Comment by dwrolvink** [comment]
Okay it makes a lot of sense that `<img src="figures/unnamed-chunk-1-1.png" title="plot of chunk unnamed-chunk-1" alt="plot of chunk unnamed-chunk-1" style="display: block; margin: auto;" />` is not being picked up correctly. 

There is no code to find img tags and handling the images linked in them. Though this should not be very difficult to add.

By the way, if you are just compiling from md to html, then you can skip the obsidian --> md step.
You can do that with this config:
``` yaml
obsidian_entrypoint_path_str: '' # this line can be absent when using most recent master code, otherwise it is expected

md_folder_path_str:  '/home/dave/Dropbox (Lehigh University)/post_doc/professional/projects/gaita/ideation/structured/md/'
md_entrypoint_path_str: '/home/dave/Dropbox (Lehigh University)/post_doc/professional/projects/gaita/ideation/structured/md/homepage.md'

html_url_prefix: '/gaita/ideation/structured/html/'

toggles:
  compile_md: False
  process_all: True
```

Your project is not that big yet, so hardly any time gain for you there, but nice for bigger projects, and maybe in this special case it will solve the weird bug when using `![](figures/unnamed-chunk-1-1.png)`.

This:

> `Changing that link to ![](figures/unnamed-chunk-1-1.png) creates a figures directory in output/md but not output/html.`

Is really weird. What does the link look like in the `to_html/output/md/experiment-2-theory.md` when you set that?

> I should note that I made a workaround writing a shell script that just manually copies the figures folder to the output html, which works fine because the link to the image in the html file is intact. So for my purposes, this is no longer an issue. I'm happy to help you keep troubleshooting if you want to get to the bottom of it, but I realize that my use case of generating md from .Rmd is a non standard one and might not be one you're concerned about.

This issue for me is that these are just standard markdown/html elements, and are thus expected to work. So even though you have a workaround, I would like to investigate this a bit further.

If the content of your vault is not private, then sharing the markdown code would help me to recreate the bug more quickly, so that would be nice if that is an option.

**Comment by dbraun31** [comment]
Okay so I retried the `![](figures/unnamed-chunk-1-1.png` (without any of your suggested additions to the config file) this morning and that worked- I get the `folders` dir in the output html and it displays correctly on my site.  It's possible that had forgot to add the exclamation mark on my last time testing it, but not sure.

> If the content of your vault is not private, then sharing the markdown code would help me to recreate the bug more quickly, so that would be nice if that is an option.

Yup, this is all on a public GitHub repo ([here's](https://github.com/dab414/risky-visual-search/tree/master/ideation/structured/md) the dir containing the `md`). The only thing in this workflow that's private is that shell script I mentioned that executes the convert and pushes to my website. And [this](https://davebraun.net/gaita/ideation/structured/html/experiment-2-theory.html) is how `experiment-2-theory.html` displays on my website after using the `![](figures/unnamed-chunk-1-1.png` link. This project right now is just me doing some small tests to prove the concept. It'll likely stay in its current state for a week or so, as I'll be away, so feel free to poke around. Starting in January I'll want to start developing it more for the project I'm working on.

**Comment by dwrolvink** [comment]
In that case we can probably reduce the issue you're having to just the fact that obsidianhtml doesn't process img tags, so I'll add that for sure.

Note that if you don't need obsidian at all, that mkdocs is also a nice, very mature software product that can probably do all that you need it to do. Though if obsidianhtml does exactly what you want then it's probably easier to just keep using obsidianhtml.

Looking at the output it's weird that the links contain the .md suffix, it shouldn't do that. But I'll convert your vault myself after Christmas and see what's going on there.

**Comment by dwrolvink** [comment]
ohh I think you can change `[[measurement.md]]` to `[[measurement]]`, that should remove the .md from the link text.

Note that you can use `[[note name|alias]]` to change the link text, should you want to.

**Comment by dbraun31** [comment]
>ohh I think you can change [[measurement.md]] to [[measurement]], that should remove the .md from the link text.

> Note that you can use [[note name|alias]] to change the link text, should you want to.

These are super great tips- I'll definitely incorporate, thank you! 

Yea I just generally rely more on RStudio and Vim than Obsidian for putting notes together, but I do like the Obsidian-like functionality of linking and visualizing the note graph. I haven't yet poked around Mkdocs, but I like that your software preserves the graph capability. And as I use this for my research I can send you other issues that pop up to help develop the software. I'm seeing a little issue with some latex conversion that I'll go ahead and open a new issue for.

**Comment by dwrolvink** [comment]
So to respond on the whole  `<img>` tag thing.
In obsidian there is no way to get an img tag to work, seeing how images are loaded with this horrendous path: `app://local/home/user/path/to/example_vault/vault/200w.gif?1671665320030`

One of the few rules I have is that I don't implement anything in the obsidian scope that is not valid in Obsidian, nothing in markdown that is not proper markdown, etc. Adding support for image tags in obsidian that are not external images (http(s) protocol) would break that. This all to avoid making a moloch of a system.

Can you explain why you are using the img tag as a workaround?
Because at the moment I'd just say use the correct image syntax for what you are doing, and then it should all work as far as I can tell.

**Comment by dbraun31** [comment]
So a bit of background on my Rmarkdown-->md workflow: This Rmarkdown-->md conversion is totally a function of an app called [knitr](https://yihui.org/knitr/) . Without going into too much detail about the RMarkdown world (apologies if you already know this world), I'm generating figures using R code and then, during conversion, knitr saves that image as a separate file and replaces the code from the `.Rmd` with a link in the `.md` to the image. In my limited messing around with knitr settings, it looks like the way this app links to the image depends on settings around how the image should display. Eg, when using the default settings, it'll use the markdown style image link, but when I ask for the image to be centered, it'll link to the image with the html line including the css parameters `display: block; margin: auto` to achieve centering. I could dig around in the knitr docs to see if there are ways to accomplish what I want while preserving the markdown style image links.

But all that aside, all I'd really need for a workaround in my case is whatever is happening in the current live version of the app that doesn't throw an error during conversion when it hits an `<img>` tag, but just omits the image directory in the resulting html output folder (like the behavior documented above). Because then I can simply run a script executing the conversion and then manually copying that folder over, which works fine. But when the obsidianhtml conversion throws an error then the rest of the pipeline breaks down.

**Comment by dwrolvink** [comment]
Alright now it always checks whether the file really exists or not before copying, that should fix your issue.
I've also just transplanted the img tag handling code from the md-->html function into the note-->md function and with some minor edits I got it to work for a simple usecase.

Not a supported feature but it might work for you now.

**Comment by dbraun31** [comment]
So running the app on master branch (version `3.3.1`) and everything worked perfectly. It parsed the `<img>` tags correctly without me needing to manually move over the `figures` directory, and both the equations and figures are displaying correctly in the html. Super awesome- thank you so much. I'll be sure to let you know if I run into anything else that seems buggy.
