### ISSUE TITLE
Allow the user to open/close tag entries in the 'tag_tree' side pane

### ISSUE THREAD

**Issue by erikwestra** [obsidian-html/obsidian-html#509]
At present, if you generate the index using `create_index_from_tags` and display it in one of the side panes using (eg) `side_pane/left_pane/contents: tag_tree`, a flat list of all tags and their occurrences is displayed.  This list can quickly become so long that the user has to scroll the side pane to find a desired note, and it becomes hard to find a desired note using tags.

The directory tree, which can also be displayed in a side pane using (eg) `side_pane/left_pane/contents: dir_tree`, the resulting list of folders is collapsed by default, and you have to click on a folder to drill down into it and see the contents.  It would be great if the tag view worked the same way: initially just showing a list of the tags and not their occurrences, and then allowing the user to click on a tag to open it up and see the occurrences (and sub-tags).

**Comment by dwrolvink** [comment]
Good request, I was planning on adding this at some point. Will get to this when all the buggy stuff is resolved. Might take some time.

**Comment by dwrolvink** [comment]
See also #500

Reusing the code of the generated tag page for the side pane code.
Should work fine now. Perhaps the styling can deserve some attention but I think it doesn't look too bad atm.
