### ISSUE TITLE
Add support for nested tags to the `tag_tree` side pane

### ISSUE THREAD

**Issue by erikwestra** [obsidian-html/obsidian-html#510]
At present, if you generate the index using `create_index_from_tags` and display it in one of the side panes using (eg) `side_pane/left_pane/contents: tag_tree`, only the top-level tags are displayed.  Sub-tags appear in the same entry as the top-level tag.  For example, imagine I have the following two notes with associated tags:

- `note-1.md` contains the tags `#travel/usa` and `#purpose/work`.
- `note-2.md` contains the tags `#travel/europe` and `#purpose/holiday`.

The `tag_tree` side pane would currently look like this:

```
    travel
        note-1
        note-2
    purpose
        note-1
        note-2
```

The nested tags are simply ignored.  It would be great if the `tag_tree` side pane supported nested tags, just like the `obs.html/tags/index.html` generated tag page does.  In other words, the above notes should ideally generate the following `tag_tree` side pane:

```
    travel
        usa
            note-1
        europe
            note-2
    purpose
        work
            note-1
        holiday
            note-2
```

**Comment by dwrolvink** [comment]
I cannot recreate this with the current code.
Probably mostly because now I reuse the obs.html/tags/index.html generated tag page instead of using the other code. See also #500. 

Closing this, as I will just assume it is fixed now.
