### ISSUE TITLE
Table column borders are inconsistent

### ISSUE THREAD

**Issue by erikwestra** [obsidian-html/obsidian-html#511]
I've noticed a minor quirk in the way tables are displayed in obsidian-html.  One of my notes includes the following Markdown table:

```
| Event                  | Distance | Duration | Dates           | Details                               |
| ---------------------- | -------- | -------- | --------------- | ------------------------------------- |
| The Geyserland Mini    | 138 km   | 2 days   | 20-21 May       | [[The Geyserland Mini\|More Info]]    |
| The Geyserland Classic | 239 km   | 3 days   | 9-11 September  | [[The Geyserland Classic\|More Info]] |
| The Geyserland Mega    | 577 km   | 5 days   | 17-21 November  | [[The Geyserland Mega\|More Info]]    |
| The Geyserland Family  | 34 km    | 2 days   | To be confirmed | [[The Geyserland Family\|More Info]]  |
```

In Obsidian, this table is rendered like this:

<img width="692" alt="Screen Shot 2022-12-31 at 5 35 31 PM" src="https://user-images.githubusercontent.com/515597/210125021-6c3a6f40-bd45-433a-937f-a71cbb3f5dc0.png">

This does look rather ugly, but it works.  The rendering in obsidian-html is much nicer:

<img width="615" alt="Screen Shot 2022-12-31 at 5 35 04 PM" src="https://user-images.githubusercontent.com/515597/210125028-1f43a5ee-8993-4484-8e1a-d9f2d09c762c.png">

It does look a bit odd, though, having vertical dividing lines only on every second column.  Is that deliberate?  Perhaps I'm just being OCD, but the missing vertical lines look a bit buggy to me -- I would have expected a vertical line between every column in the table.

(as I say, this is a minor cosmetic issue -- I just thought I'd mention it since it does look a little odd, but I wouldn't be at all worried if you just said it's not worth fixing or that you wanted tables to render this way).

**Comment by dwrolvink** [comment]
Lol I was looking on the website for any tables with three columns, and I couldn't find one. I guess that says enough.
Perhaps there was an alternating column border in the past, I don't remember, but there isn't anymore. So now they are all the same.

Thanks for the report!
