### ISSUE TITLE
Internal links with characters after are not processed correctly

### ISSUE THREAD

**Issue by Programmerino** [obsidian-html/obsidian-html#532]
In my vault I will often have a note with a singular name "actor", and reference it like `[[actor]]s` when it grammatically needs to be plural. This is supported in Obsidian, but causes my obsidian-html log to be filled with lines like:
```
File ./actor.md)s not located, so not copied. @ ...
```

I use the `process_all` toggle, so I still have the files in the HTML output, but the links to it end in `.md` which don't work.

This seems to be an issue for both the Wikilink and Markdown link formats.

**Comment by dwrolvink** [comment]
Can't replicate this

I have a note called `Blog/Cats` in obsidian, and in the index.md I have:
```
[[Cats]]s

[Cats](./Blog/Cats.md)s
```

this gets converted into:
``` md
[Cats](./Blog/Cats.md)s

[Cats](./Blog/Cats.md)s
```

And then on to functional html links.
Are you on the latest master code?

Looks like a regex bug that was fixed quite a long time ago.

**Comment by Programmerino** [comment]
My apologies, I wish I tested it a bit more first. The problem seems to only occur if the link comes right before a right parenthesis:
```
[[actor]]s)
```

The logs look like:
```
> COPYING VAULT /tmp/test/test TO /tmp/tmpwr12lg2a
running: 
	rsync -a /tmp/test/test/ /tmp/tmpwr12lg2a --exclude /.obsidian --exclude /.trash --exclude /.DS_Store --exclude /.git
Copy succeeded 0  b''
< COPYING VAULT: Done
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (/tmp/tmpwr12lg2a/file.md)
> COMPILING HTML FROM MARKDOWN CODE (/tmp/obshtml_m38_2jj7/md/index.md)
		File ./actor.md)s not located, so not copied. @ /tmp/tmpwr12lg2a/file.md
	> COMPILING INDEX FROM DIR STRUCTURE (/tmp/obshtml_m38_2jj7/html/obs.html/dir_index.html)
	< COMPILING INDEX FROM DIR STRUCTURE: Done
	> SECOND PASS HTML
	< SECOND PASS HTML: Done
< COMPILING HTML FROM MARKDOWN CODE: Done

You can find your output at:
	md: /tmp/obshtml_m38_2jj7/md
	html: /tmp/obshtml_m38_2jj7/html
```

**Comment by dwrolvink** [comment]
Ahh that makes a lot more sense.
I think I can write a phd thesis on the markdown link regex in a year with all these edge cases lmao.

Will fix this tonight, should be pretty easy
