### ISSUE TITLE
Bug: Exception thrown when parsing a block that contains a unique block identifier

### ISSUE THREAD

**Issue by jcoffa** [obsidian-html/obsidian-html#533]
I was trying to convert my vault for the first time, but it raised an exception when parsing one of my notes. I was able to create a test vault and re-create a minimal setup to reproduce the issue. Here's the output of the console, including the exception:

```
< COPYING VAULT: Done
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (C:\Users\Joseph\AppData\Local\Temp\tmpc92l25jg\INDEX.md)
> COMPILING HTML FROM MARKDOWN CODE (C:\Users\Joseph\AppData\Local\Temp\obshtml_rzq5nbnm\md\index.md)
Traceback (most recent call last):
  File "C:\Users\Joseph\AppData\Local\Programs\Python\Python310\lib\site-packages\obsidianhtml\ErrorHandling.py", line 59, in _decorator
    res = f(*args, **kwargs)
  File "C:\Users\Joseph\AppData\Local\Programs\Python\Python310\lib\site-packages\obsidianhtml\ConvertVault.py", line 1078, in ConvertMarkdownPageToHtmlPage
    html_body = markdown.markdown(md.page, extensions=extensions, extension_configs=extension_configs)
  File "C:\Users\Joseph\AppData\Local\Programs\Python\Python310\lib\site-packages\markdown\core.py", line 387, in markdown
    return md.convert(text)
  File "C:\Users\Joseph\AppData\Local\Programs\Python\Python310\lib\site-packages\markdown\core.py", line 268, in convert
    newRoot = treeprocessor.run(root)
  File "C:\Users\Joseph\AppData\Local\Programs\Python\Python310\lib\site-packages\obsidianhtml\markdown_extensions\FootnoteExtension.py", line 488, in run
    footnotesDiv = self.footnotes.makeFootnotesDiv(root)
  File "C:\Users\Joseph\AppData\Local\Programs\Python\Python310\lib\site-packages\obsidianhtml\markdown_extensions\FootnoteExtension.py", line 249, in makeFootnotesDiv
    self.parser.parseChunk(surrogate_parent, fn['text'])
  File "C:\Users\Joseph\AppData\Local\Programs\Python\Python310\lib\site-packages\markdown\blockparser.py", line 99, in parseChunk
    self.parseBlocks(parent, text.split('\n\n'))
AttributeError: 'NoneType' object has no attribute 'split'

        OBS.HTML EXTRA ERROR INFORMATION:
        ---------------------------------
        Current action              : Conversion of markdown notes to html notes
        Subroutine                  : ConvertMarkdownPageToHtmlPage
        Current note being processed: C:\Users\Joseph\AppData\Local\Temp\obshtml_rzq5nbnm\md\Test Block ID.md ()
```

To reproduce this example, I have the following two notes in a fresh vault:

**INDEX.md**
```
# INDEX

[[Test Block ID]]
```

**Test Block ID**
```
# Test Block ID

This is a normal block.

Here is another normal block.

This block has a unique block identifier associated with it.
^blockid

This block has an [[#^blockid|internal link]] to the previous one using its ID.
```

... where I pointed to `INDEX.md` as the root of the vault.

Block IDs are an [Obsidian feature to allow linking to a specific block in a note](https://help.obsidian.md/Linking+notes+and+files/Internal+links#Link+to+a+block+in+a+note), and it seems like it's confusing obsidianhtml somehow. They are not part of the official markdown spec and I suspect most people don't even know this feature exists, so I'm assuming this just wasn't taken into account when making this script.

I was able to fix the bug by changing the `blockparser.py` file's `BlockParser.parseChunk` method by adding a None check:

```python
    def parseChunk(self, parent, text):
        """ Parse a chunk of markdown text and attach to given etree node.

        While the ``text`` argument is generally assumed to contain multiple
        blocks which will be split on blank lines, it could contain only one
        block. Generally, this method would be called by extensions when
        block parsing is required.

        The ``parent`` etree Element passed in is altered in place.
        Nothing is returned.

        """
        if text is None:
            return
        self.parseBlocks(parent, text.split('\n\n'))
```

... but I highly doubt this is actually a good solution. It was just a quick workaround I found that let me continue converting my vault. It creates a very strange output in the actual HTML site generated:

![image](https://user-images.githubusercontent.com/35551680/211375302-6e660066-9002-4f44-8dcd-d197ba35c308.png)

**Comment by dwrolvink** [comment]
What happens is that 
- `This block has an [[#^blockid|internal link]] to the previous one using its ID.` 

gets converted into 
- `This block has an [^blockid](#blockid) to the previous one using its ID.` 

I think something is going wrong there, because even in the current case, where obsidianhtml does not support block-ids, it should be converted to `[internal link](#^blockid)`, or something like that.

In any case, the `[^blockid]` then gets recognized by the next markdown extension as a footnote marker, which of course has no corresponding footnote, because it wasn't one to start with, causing the error.

The correct spot to add the `is None` check is here: 
``` python
  File "C:\Users\Joseph\AppData\Local\Programs\Python\Python310\lib\site-packages\obsidianhtml\markdown_extensions\FootnoteExtension.py", line 249, in makeFootnotesDiv
    self.parser.parseChunk(surrogate_parent, fn['text'])
```

Because the goal of that call is to further process the footnote text and then put it into `surrogate_parent` (a div). If there is no text, then the div can just remain empty.

I've gone ahead and added the `is None` check, because users might make the mistake of not adding a footnote to their marker, and in that case you'd expect an empty footnote anyways, and not a fatal error :shrug:  

I'll keep this issue because the underlying issue here remains: implementing block id's, which I've touched up on some time ago, but never really implemented. It's kind of annoying because it is very close to the implementation for footnotes, *but not quite*.  So that will take some time and focus to get right, which I am lacking at the moment. So it might take some time before I work on this.

**Comment by jcoffa** [comment]
>  So that will take some time and focus to get right, which I am lacking at the moment. So it might take some time before I work on this.

I appreciate the quick reply. Just want to mention that getting block IDs working is not at all an important or pressing issue to me; I just noticed the bug and figured I should make an issue about it so that it's known and logged. I think most people do not even know about this feature, and my vault of over 500 notes only uses it in the one file. I imagine fixing the exception will be good enough until full support for this feature can be done.

**Comment by dwrolvink** [comment]
Great, thanks for that info. Suddenly got a lot of bug reports in one big wave to chew on, so this is valuable information.

**Comment by dwrolvink** [comment]
So I was looking at just fixing the weird behavior that I saw, but when I fixed that I saw that implementing this feature (at least a first version) was pretty simple from that point on.

Did not test beyond your example, but at least your example works.

**Comment by dwrolvink** [comment]
Be aware that you need to [install the master branch](https://obsidian-html.github.io/Instructions/Install%20a%20different%20version.html#!install-master-branch) to get these updates until I publish a new release:

**Comment by dwrolvink** [comment]
closing so that I get some better overview of what still needs attention, just respond here and I will reopen when needed

**Comment by jcoffa** [comment]
I've just confirmed that both the small example and the original (and much larger) file that I initially found this issue from in my real vault can now be parsed without any exceptions or complaints from obsidianhtml. I was inspecting the HTML and found that it does embed anchors and divs at the source and destination of the block links as well; which is exactly how I imagined this would work.

I did notice that the links don't actually work however; i.e. clicking the HTML equivalent of `[[#^blockid|pretty prose text]]` does not actually jump to where the block ID can be found. After some digging, I found that this is likely as simple as fixing a whitespace issue.

---

In my much larger note (where I originally found the issue in), it looks like the `<a>` tag is formatted correctly:

```html
<p>
  If I put my desk up against the
  <a class="anchor-link" href="#__LivingroomOutcropping">Living Room Outcropping</a>
  <!-- ... etc. ... -->
</p>
```

... but the destination div's ID has some trailing whitespace which prevents the link from working (because the IDs don't match):

```html
<div id="__LivingroomOutcropping   ">    <!-- notice the 3 trailing spaces at the end of the ID -->
```

I manually edited the div ID using inspect element to remove the trailing whitespace (i.e. `<div id="__LivingroomOutcropping">`) and the link started working properly immediately. Perhaps there's something causing extra whitespace to be embedded in only the div's IDs? This was a consistent problem across all block links in both my original note and the example note; this was not a one-off. Could this be solved with a call to `.strip()` somewhere in the code that is responsible for emitting these divs?

---

Again, I think fixing the exception getting thrown will be good enough for 99.9% of people and really the only reason I'm mentioning this is because I believe the issue would be simple to fix. If I'm wrong and this is actually some larger/more complex problem with the code that outputs the final HTML, then I am in no way suggesting that you need to fix this ASAP. I think obsidianhtml is awesome and the fact that you so quickly fixed that exception issue is fantastic; I just thought I would bring up this small issue I found so that you could be aware of it and get around to it whenever convenient.

**Comment by dwrolvink** [comment]
Aha, I had strict_line_breaks still turned off, because of another feature request.
This adds three spaces behind every line to mimick obsidian's default behavior.

Indeed adding the strip() will fix this. I.e. in this location: https://github.com/obsidian-html/obsidian-html/pull/544/files

Should work now in the master code
