### ISSUE TITLE
Published v3.4.1

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#543]
Anyone on the master branch for recent bugfixes/implementations can go back to the pip version if they so desire

[obsidian-html/3.4.0](https://obsidian-html.github.io/changelog/v3.4.0.html)

**Comment by dwrolvink** [comment]
[obsidian-html/3.4.1](https://obsidian-html.github.io/changelog/v3.4.1.html)

**Comment by aquatix** [comment]
> [obsidian-html/3.4.1](https://obsidian-html.github.io/Changelog/v3.4.1.html)

Those changelog pages do not exist (anymore)?

**Comment by dwrolvink** [comment]
Ah yes, this is related to #574 see also https://obsidian-html.github.io/configurations/features/slugify-html-links.html

I opted into this for the documentation site, which broke all the old links... Updated them in this thread.

**Comment by aquatix** [comment]
Ah, makes sense! Maybe an idea to at least fix the link to the changelog of the latest release tag.

I rather like slugifying the links, capitals in URL's are always a tad weird to me #unixnerd :)
