### ISSUE TITLE
HTML prefix should also be added to favicon href

### ISSUE THREAD

**Issue by camargomau** [obsidian-html/obsidian-html#546]
Hello!

First of all, amazing work with obsidian-html. Easily the best free Obsidian Publish alternative out there. Takes some time to properly setup, but once it's set up, it just works and it works very well.

Anyway, I found a minor issue that's preventing the favicon from working correctly when a custom HTML prefix is set (with the `html_url_prefix` option). After a bit of trial and error, I discovered that the favicon's href is missing the HTML prefix: it should be `{prefix}/favicon.ico` instead of `/favicon.ico`.

I discovered this issue while deploying [this site](https://psycake.github.io/lingkesto/). As you can see, its [latest commit](https://github.com/psycake/lingkesto/commit/fc4deb7bece6df3426678bade12d613a6cbc53f3) fixes the HTML.

**Comment by dwrolvink** [comment]
Thanks, glad you find it useful!
And yes config is kind of a chore, I've started on `obsidianhtml run` and even a GUI at some point to make configuration easier, but with the incredible diversity of configs that people use and the extra stuff that gets requested regularly the config tools are basically outdated before they are ever finished. Long story short: simplifying config is extremely time consuming and complex.

Weird issue, I remember handling this issue some time ago, but looking now it's not even a bug, it was just not implemented :thinking: 

Anyways, added it, tested it locally and this fixes it for me.
