### ISSUE TITLE
Dots, Square Brackets in image Titles are causing an include-error by script

### ISSUE THREAD

**Issue by Gewerd-Strauss** [obsidian-html/obsidian-html#550]
Hello,

Assume the following note:

```
---
creation date: "2023-01-15 13:00"
modification date: "2023-01-15 13:27"
tags: programming
---
NORMAL:  
![[200 University/04/BE22 Bioinformatics/Task 7 Phylogenetic Tree/GuideTree (actual Phylotree).png|Figure 22: Phylogenetic Tree of the sequences mentioned in 45 Similar sequences]]  
Quotes:  
![[200 University/04/BE22 Bioinformatics/Task 7 Phylogenetic Tree/GuideTree (actual Phylotree).png|Figure 22: Phylogenetic Tree of the sequences mentioned in "45 Similar sequences"]]  
DOT:  
![[200 University/04/BE22 Bioinformatics/Task 7 Phylogenetic Tree/GuideTree (actual Phylotree).png|Figure 22: Phylogenetic Tree of the sequences mentioned in 4.5 Similar sequences]]  

```

And its output:

```
---
creation date: 2023-01-15 13:00
modification date: 2023-01-15 13:27
tags:
- programming
---
   
NORMAL:     
<img src="200%20University/04/BE22%20Bioinformatics/Task%207%20Phylogenetic%20Tree/GuideTree%20%28actual%20Phylotree%29.PNG"  width="" alt="Figure 22: Phylogenetic Tree of the sequences mentioned in 45 Similar sequences" title="Figure 22: Phylogenetic Tree of the sequences mentioned in 45 Similar sequences" />     
Quotes:     
<img src="200%20University/04/BE22%20Bioinformatics/Task%207%20Phylogenetic%20Tree/GuideTree%20%28actual%20Phylotree%29.PNG"  width="" alt="Figure 22: Phylogenetic Tree of the sequences mentioned in "45 Similar sequences"" title="Figure 22: Phylogenetic Tree of the sequences mentioned in "45 Similar sequences"" />     
DOT:     
> **obsidian-html error:** Error including file or not a markdown file 200 University/04/BE22 Bioinformatics/Task 7 Phylogenetic Tree/GuideTree (actual Phylotree).png|Figure 22: Phylogenetic Tree of the sequences mentioned in 4.5 Similar sequences.
```

The first one will be converted correctly, the second one is also correct\*, but the third one is not converted at all.

It seems like dots and square brackets within titles will cause the script to fail. I have not tested all potential characters yet, but it might be the case.

Small test I could come up with so far:

[ObsidianHTML Special characters in Image titles.zip](https://github.com/obsidian-html/obsidian-html/files/10420307/ObsidianHTML.Special.characters.in.Image.titles.zip)

It should be noted that quotes break because my converison script's regex is not set up for that yet and I haven't come around to doing so yet.

---

I hope the provided sample is useful.

Thank you.  
Sincerely,  
~Gw

---

\* As far as I can say, at least. It breaks my utility which converts img src's into R-code chunks, but technically it's legal as far as I am aware.

**Comment by dwrolvink** [comment]
Hi Gewerd, thank you for the bug report.
I've found the bug and fixed it, try your example again with the latest changes.

I did not find any example with "square brackets in the image title" 
I tried the following:
```
![[200w.gif|test [vla]trtr]]
```
And that did not work, it is not recognized as an image.
I then made the second change, and now that image title works too.

**Comment by Gewerd-Strauss** [comment]
Jup. 

> I  did not find any example with "square brackets in the image title"

I mean the sample file had an example of it. granted, it was not a useful example, but I made it standardised across all character tests instead of attempting to make them look natural. This initially came up when converting an old paper of mine for test purposes - it's my standard quick test file as it has most stuff I care about, but it's not good for sharing. 


Try this:

    \[\]:  
    ![[200 University/04/BE22 Bioinformatics/Task 7 Phylogenetic Tree/GuideTree (actual Phylotree).png|Figure 22: Phylogenetic Tree of the sequences mentioned in 4[]5 Similar sequences]]  

Everything works for me (minus quotes, but yea that's not the fault of the python script ;P)
[ObsidianHTML Special characters in Image titles_Fixed.zip](https://github.com/obsidian-html/obsidian-html/files/10420793/ObsidianHTML.Special.characters.in.Image.titles_Fixed.zip)

**Comment by Gewerd-Strauss** [comment]
I'll try and get a more complete testset going, but it's not of high priority to me right now. So I suppose if something similar occurs I'll open another one. 


Thus, this should be closeable. 

Thank you.

**Comment by Gewerd-Strauss** [comment]
I'll try and get a more complete testset going, but it's not of high priority to me right now. So I suppose if something similar occurs I'll open another one. 


Thus, this should be closeable. 

Thank you.
