### ISSUE TITLE
Spaces added on all lines (notably List-entries)

### ISSUE THREAD

**Issue by Gewerd-Strauss** [obsidian-html/obsidian-html#555]
Hello,

took me ages to trace this back to OHTML.

I have attached a summary folder of the issue.

It seems like every line aside of the YAML-header (and notably list-entries) are not only appended a paragraph character but also three spaces when generating the `index.md`, compared to the raw copy `*_vault.md`. Also see the different docx-outputs that result from this change.

Relevant info:

- `strict_line_breaks=false`. I use the linter to autoformat paragraphs acc. to default md-spec with double-spaces at the end. This does not modify list items, as they don't need them. The linter only alters lines which are succeeded by a text-line immediately, and appends _two_ spaces to them.
	- Consequently, Obsidian's own `strict_line_breaks` is off as well.
- `Executionlog.txt` contains the contents of the custom config (badly parsed, I just add all lines containing `\=`, cannot be bothered to parse out the comments yet.) None of it should be relevant, but there it is just in case.
- `index.md` is the output of OHTML.
    - `index.rmd` is a copy with changed filesuffix, identical file. (I also converted the `index.md`-file to word via the same processor, there is truly no difference between the rmd- and md-copy.)
- `ObsidianHTML_List-entriesNewlines_vault.md` is the raw copy from the vault, showing that the lines of the original document do **only contain a newline**-character - and get correctly converted as a result.
	- and its rmd-copy was to make sure that copying it into a different filetype would not alter the contents. It does not.
- the `index_md.docx` and `index_rmd.docx` files are generated by converting standard markdown to docx with RMarkdown, just for the sake of completion.

---

This should be fixed, as it is not standard markdown behaviour to append ~~newlines to list entries, neither is the addition of~~ tripple-spaces relevant - and as we notice here it's nonostandard enough to confuse (R-)pandoc into giving out gibberish.

---

I hope this is enough information.

Thank you,  
Sincerely,  
~Gw

**Comment by Gewerd-Strauss** [comment]
Uuuh... _Somehow_ I managed to forget to include the files.
[ObsidianHTML_List-entriesNewlines.zip](https://github.com/obsidian-html/obsidian-html/files/10477780/ObsidianHTML_List-entriesNewlines.zip)

**Comment by dwrolvink** [comment]
I think you need to turn this off: https://obsidian-html.github.io/Configurations/Configuration%20Options.html#!strict-line-breaks

I think this is a usecase for #556

**Comment by Gewerd-Strauss** [comment]
Well, somehow I got myself confused here. That works. 
I swear I read somewhere you are supposed to keep that setting in match with Obsidian's setting, but I can't find that anymore :P

Seems resolved now.
Thank you.
