### ISSUE TITLE
Path errors for tags (and incorrectly parsed text) with illegal characters

### ISSUE THREAD

**Issue by DominikDoom** [obsidian-html/obsidian-html#559]
The current version falsely recognizes some text as tags, which leads to errors on creating the tag folders in `recurseTagList` if they contain illegal characters, or at the very least wrong paths if the tag (or false positive) includes slashes.

Some examples of what will lead to issues or a crash:
- Code blocks or inline code containing a comment for a language that uses # for them
   - This will most of the time lead to nonsense paths due to slashes or spaces in the comment, but for some cases it can crash, eg `#x<5` since < is illegal for Windows paths
   - Also, some programming languages like the Scheme family use #t #f and other notations starting with a #. In some cases this will crash too, e.g. `#:whatever` is the notation for named parameters in some scheme dialects and the : is illegal on Windows
- Tags including `/` (valid and rendered correctly in Obsidian)
	- Will lead to wrong path structure since it's interpreted as a subfolder by pathlib
	- But maybe this is intended? since in Obsidian it's listed as sub-tags as well. gets weird with empty slashes though, like #tag///abc
- Text without space after the # containing any other illegal characters, even if Obsidian doesn't render them as tags (e.g. #*), both inside and out of code blocks

I don't know if there's an easy way to find out what's an actual tag and what isn't, but at least in code it should definitely ignore #. Also, probably a good idea to add a safety check that filters out tags with illegal characters.

**Comment by dwrolvink** [comment]
Good find!

- Tags being parsed inside of codeblocks was just a massive oversight, fixed now by ensuring that `md.StripCodeSections()` is called before parsing the inline tags.
- Made an improvement to the regex for finding/replacing inline tags, based on this page: https://help.obsidian.md/How+to/Working+with+tags I think that should fix your remaining issues.

I've also started writing some unit tests, so these cases have been added to the unit tests:

```
"#test"       -->   ['test']
"#test "      -->   ['test']
"#test/sub"   -->   ['test/sub']
"#test.break" -->   ['test']
"#!invalid"   -->   []
```

**Comment by DominikDoom** [comment]
Just installed it from git and tried it out, I can confirm that this fixes the issue for me 👍.

One small thing: I'm not using them myself, but from the https://help.obsidian.md/How+to/Working+with+tags link it seems like tags that contain numbers are valid too:

> Numbers are allowed in the tag, as long as the tag is not purely numeric. For example, #1984 isn't a valid tag, but #y1984 is a valid one.

Since numbers are fine in paths too, I think the regex can include those as well instead of just a-zA-Z.
Something like this maybe:
```regex
(?<!\S)#[a-zA-Z][\w/\-]*
```

**Comment by dwrolvink** [comment]
Oh wow I totally forgot about that one, thanks.

Of all of these:
```
#1990
#19_90
#y1990
#1990y
#19y90
```

Obsidian thinks they are valid except the first, yours picks up only the third, so that is not a perfect match.

Bit inelegant, but this one seems to work for me (btw thanks for the reminder that `\w` exists :smile:):
``` regex
(?<!\S)#[\w/\-]*[a-zA-Z\-_/][\w/\-]*
```
- Can not be preceded by a non-space char (e.g. `test#test --> []`)
- Find `#`
- Find zero or more of all allowed chars
- Find exactly one non-numeric char
- Find zero or more of all allowed chars

**Comment by DominikDoom** [comment]
Ah yeah my bad, I only thought about the example from the help doc.
I don't think there's a more elegant way to do it for this specific case, at least not with regex alone.
