### ISSUE TITLE
Make search work with giant vaults

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#564]
localStorage can only store 5M in data. For very large vaults, this becomes an issue.

The change for now is to fetch the search data when the search pane is opened. When all the data is fetched and processed, it will try to do the following things, in this order:

- try to store the processed search data
- if this fails, try to store the zipped search data
- initFlexSearch

When the page is loaded, it will run PreloadSearchData, which will run `initFlexSearch()` on page load if the search_data is cached. 

When the search menu is opened, the following happen, in this order:

- If flex search is already initialized (by PreloadSearchData) then just search immediately `fin`
- If the search data hash is not present, or is outdated, fetch and proces search data (see above), init flex search, then search `fin`
- If search_data is cached, load this and init flex search `fin` 
- If zipped search data is cached, unzip this and init flex search `fin`

**Comment by zubayrali** [comment]
I installed the latest obsidianhtml with `pip install git+https://github.com/dwrolvink/obsidian-html` and built the website, although the search is working when I run the website locally its throwing the following error when pubished.

![image](https://user-images.githubusercontent.com/31969517/215299776-4d6f8fd7-d56e-4b87-8936-9b2107354264.png)

The error is shown when I try to search for something.

Thanks for this quick fix.

**Comment by dwrolvink** [comment]
could you try running `localStorage.clear()` in the web terminal and then refresh the page? 
I think the old data is still stored, which has a different encoding. 

This could also be fixed by changing your vault, as this should change the search_hash, which should force a reload of all the data, but seeing how that would take you 12 minutes or so, this would be a quicker way to check whether the code itself works at least.

**Comment by zubayrali** [comment]
I did this in incognito mode:

I didn't do `localStorage.clear()`, it just waited for a bit and then did this:

![image](https://user-images.githubusercontent.com/31969517/215340166-8d352792-8331-424d-8d2a-9c5ff309047d.png)

I also did `localStorage.clear()` and now its working as expected.

Btw, it takes me 12 mins because I've a potato PC.

**Comment by dwrolvink** [comment]
Yes regarding the slowness, see also #566
In that issue I'm also working on general performance improvements. Adding caching and the like. I went from a compile time of around 18 minutes (with profiling turned on) to 51 seconds, just by turning of the dir tree side pane and some caching implementations. 

Will keep you posted, need to do some checks whether the caching doesn't give any bugs, but I am optimistic about the gains that are possible with this and a rewrite of the dir_tree feature.

**Comment by dwrolvink** [comment]
Btw, for me your site became way less responsive with the search data preloading turned on, so I turned it off by default in the last PR, and made it configurable to turn on if one so desires:

``` yaml
toggles:
  features:
    search:
      try_preload: True
```  

Now when you open the search menu you just have to wait about 5 seconds (20 in your case it looks like). Not much I can do about that loading time at the moment, might look into it at some point in the future though.

**Comment by dwrolvink** [comment]
Closing this as I think we covered everything by now. 
Not much low hanging fruit left to optimize at least.
