### ISSUE TITLE
default to current directory for config.yml if `-i /some/path/to/it` isn't passed

### ISSUE THREAD

**Issue by jcolson** [obsidian-html/obsidian-html#57]
sorry @dwrolvink - sometimes I create issues just to track them and don't fully flesh out the thought!

the idea is that you should be able to run obsidianhtml with no parameters if the config.yml file is in your current directory.

I've created a PR for that, as well as printing the help info out when there are other issues as well.

**Comment by dwrolvink** [comment]
What do you mean with "default to current directory"?

I see it puts the value behind -i directly into open(), but I've used this with relative and absolute paths, and this has always worked for me at least.

**Comment by jcolson** [comment]
i haven't updated in a LONG time, just updated and ran `obsidianhtml convert`, but it's no longer finding my default config.yml in the current directory --- did the default name/location of the config.yml change to something else?

**Comment by dwrolvink** [comment]
Ahhhh. I added the run/convert/etc change yesterday and I thought it was stale code, the config.yaml default, as it wasn't described anywhere in the docs, so i removed it. Will add it back tonight!

**Comment by dwrolvink** [comment]
Reminder for me to setup a comprehensive feature request list.

**Comment by dwrolvink** [comment]
I want to focus on having less breaking changes, to have a way to guarantee that, or at least to know when something is a breaking change, and not sure how that should be accomplished. A unit test for every little thing seems too expensive. I guess a list would be a good first approach. Not sure.

**Comment by dwrolvink** [comment]
this should be fixed by https://github.com/obsidian-html/obsidian-html/pull/386

when no config is passed in it will first look in the current folder,
if it isn't there it will look in the appdir folder, e.g. `/home/user/.config/obsidianhtml/config.yml`
if it isn't there either it will fail

**Comment by dwrolvink** [comment]
tested pretty well on my side, closing for now, let me know if you are still experiencing issues
