### ISSUE TITLE
RSS doesn't work

### ISSUE THREAD

**Issue by sevmonster** [obsidian-html/obsidian-html#575]
Output:
```
> COMPILING RSS FEED
Traceback (most recent call last):
  File "/opt/obsidian-html/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/obsidian-html/lib/python3.11/site-packages/obsidianhtml/__init__.py", line 30, in main
    ConvertVault()
  File "/opt/obsidian-html/lib/python3.11/site-packages/obsidianhtml/controller/ConvertVault.py", line 82, in ConvertVault
    compile_rss_feed(pb)
  File "/opt/obsidian-html/lib/python3.11/site-packages/obsidianhtml/controller/ConvertVault.py", line 472, in compile_rss_feed
    feed.Compile()
  File "/opt/obsidian-html/lib/python3.11/site-packages/obsidianhtml/features/RssFeed.py", line 110, in Compile
    items, most_recent_publish_date = self.get_items(self.html_folder, most_recent_publish_date)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/obsidian-html/lib/python3.11/site-packages/obsidianhtml/features/RssFeed.py", line 196, in get_items
    if selector[0] == 'yaml':
       ~~~~~~~~^^^
IndexError: list index out of range
```
Config:
```yaml
features:
    rss:
      enabled: True
      host_root: 'https://blog.example.com'
      styling:
        show_icon: True
      channel:
        title: 'Blog'
        website_link: 'https://blog.example.com'
        description: 'description'
        managing_editor: 'sev'
        web_master: 'sev'
      items:
        selector:
          match_keys: []
          exclude_keys: []
          include_subfolders: []
          exclude_subfolders: []
          exclude_files: []
        description:
          selectors:
            - ['yaml', 'rss:description']
            - ['first-paragraphs', 2, '<br/><br/>']
            - ['first-header', 1]
        title:
          selectors:
            - ['yaml', 'rss:title']
            - ['first-header', 1]
            - ['path', ['parent',1], '/ ', ['stem']]
        publish_date:
          selectors:
            - ['yaml', 'rss:publish_date']
            - ['yaml_strip', 'tags', ['date/']]
          iso_formatted: True
          format_string: '' #'%Y-%m-%d'
```
I may look deeper into this this weekend.

**Comment by dwrolvink** [comment]
Latest PR should fix this.

In the current latest release the way to go about this should be to entirely remove the key
``` yaml
features:
    rss:
      items:
        selector:
          match_keys: []
```
Instead of having it have a value of an empty list.
Added a check to see if the value is a list with length 0, and then it will skip the match_keys code.

**Comment by sevmonster** [comment]
I removed the key from both my config and `src/defaults_config.yml` but wasn't able to get it to work. If the value is an empty list in the default config I get the same error. If I remove it from the default config it complains.

```
Exception: INTERNAL ERROR: Config setting 'toggles/features/rss/items/selector/match_keys' not found in config.
```

**Comment by dwrolvink** [comment]
Apologies, I did not look correctly.
You can restore both configs to what it was.

You can pull the latest changes or install the master branch via pip, depending on how you installed and are using obsidianhtml, to fetch the latest changes.

Alternatively you could open file `/obsidianhtml/features/RssFeed.py` and change `if` to `elif` on line `196`.

**Comment by sevmonster** [comment]
I installed from master and now am having an issue where files without a matching publish date selector are causing an error, despite it seemingly supposed to be an error.
```
RSS Feed: warning: no publish_date found for note file.html
Traceback (most recent call last):
  File "/opt/obsidian-html/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/obsidian-html/lib/python3.11/site-packages/obsidianhtml/__init__.py", line 37, in main
    ConvertVault()
  File "/opt/obsidian-html/lib/python3.11/site-packages/obsidianhtml/controller/ConvertVault.py", line 82, in ConvertVault
    compile_rss_feed(pb)
  File "/opt/obsidian-html/lib/python3.11/site-packages/obsidianhtml/controller/ConvertVault.py", line 473, in compile_rss_feed
    feed.Compile()
  File "/opt/obsidian-html/lib/python3.11/site-packages/obsidianhtml/features/RssFeed.py", line 110, in Compile
    items, most_recent_publish_date = self.get_items(self.html_folder, most_recent_publish_date)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/obsidian-html/lib/python3.11/site-packages/obsidianhtml/features/RssFeed.py", line 248, in get_items
    'publish_date': publish_date_str,
                    ^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'publish_date_str' where it is not associated with a value
```

**Comment by dwrolvink** [comment]
alright, another dumb bug

It's been a long while since I originally wrote the RSS feature, and you are the first person other than me that ever created an issue on it, so basically it has not been tested very well for many different config ever since it was written. Sorry for the bugs but that is the reason why.

Try again

**Comment by dwrolvink** [comment]
now if it can't find the value it will just be blank

**Comment by sevmonster** [comment]
Don't worry about it. This project is already pretty niche and few seem to use RSS/Atom anymore. I am already happy enough that someone has taken up the banner to support a local alternative to Obsidian Publish.

**Comment by dwrolvink** [comment]
Cool! Closing this as it seems that you are no longer having issues, if you find something else just post it here then I'll reopen.

**Comment by sevmonster** [comment]
I was actually testing just then and ran into an error when it attempted to recurse `obs.html`. I had removed everything from `exclude_subfolders` for testing and forgot :)

It looks like it successfully creates it now, but the default 'en-us' language appears to be duplicated.
```xml
<language>en-usen-us</language>
```

Additionally, I don't know if this is intentional or not, but the title has an errant space placed after the path separator.
```xml
<title>notes/ zettelkasten-notetaking</title>
```

**Comment by sevmonster** [comment]
Additionally, the order of posts without publication dates seems to be random with every invocation. They should probably be placed under the ones that have publication dates, in my opinion. If that's not possible/easily achievable with the current code, would it be possible to for example set a default publication date as a selector so that they can be pushed below everything else?

**Comment by dwrolvink** [comment]
Fixed the duplicate language code in the latest PR.

The space there is something you actually configured:
``` yaml
        title:
          selectors:
            - ['yaml', 'rss:title']
            - ['first-header', 1]
            - ['path', ['parent',1], '/ ', ['stem']] # this line, notice the space
```

**Comment by sevmonster** [comment]
Oops, you're correct. I was adding spaces after commas to placate my inner formatting demons.

**Comment by dwrolvink** [comment]
As far as I know RSS feed items are always sorted on date, so best practice would be to have date set to each note that you want to publish with RSS.

We've tried to use file created/last updated as a value, but that is pretty unreliable and hard to do well cross-platform.

Setting a default date value is extremely simple, give me a minute.

**Comment by dwrolvink** [comment]
``` yaml
toggles:
  features:
    rss:
      items:
        publish_date: 
          default_value: '1999-12-31'
```

Try adding that.
Tested it with an iso format string and with the default value (empty string)

It will try to convert the string that is given to RSS standard datetime format, in the example's case, and my system, it will set `<pubDate>Fri, 31 Dec 1999 00:00:00 CET</pubDate>`. If any step of the conversion fails, it will just use the string as configured.

Edit: and, needless to say really, this value is set before setting the publish date, so if any value is found the default will be overwritten.

**Comment by sevmonster** [comment]
Works great. Thanks for the effort.

I noticed that the `'/ '` is actually in the default config, I didn't add it.
