### ISSUE TITLE
Starting entrypoint in vault-root/sub/sub-folder generates html with the leading sub/sub-folders - don't want that

### ISSUE THREAD

**Issue by HKohlhoff** [obsidian-html/obsidian-html#577]
Hi,
I love the idea to have a web-page from obsidian. Thanks for your work !
I my case, the entrypoint is not the vaults-root, but some sub/subfolder. It works, but the generated file-structure has the upper/upper-folders also. 
e.g. vault-root/up1/up2/entryfolder/index.md  leads to up1/up2/entryfolder/index.html. 
But I want it to be entryfolder/index.html without the leading upper-folders.

I tried different settings, but am not able to convince obsidionhtml to do me the favor :-(

Is there a way to get this up and running?

**Comment by sevmonster** [comment]
See https://github.com/obsidian-html/obsidian-html/issues/479#issuecomment-1423319589

**Comment by HKohlhoff** [comment]
Thx for the quick reply. 
I read that putting an empty .obsidian-folder into the entry-folder could solve it. Well, I had the same idea but did not try it to not spoil the vault. But now I did and the structure looks right, and the breadcrumbs too :-)
So, I will work with this I think

**Comment by dwrolvink** [comment]
documentation added: https://obsidian-html.github.io/instructions/tutorials/converting-just-one-subfolder-in-your-vault.html
