### ISSUE TITLE
bug : dir_tree always collapses and does not show actual link highlighted

### ISSUE THREAD

**Issue by HKohlhoff** [obsidian-html/obsidian-html#583]
Hello,
I have run the Documentation-vault and the site looks like expected.
I run my subfolder-site and it works nearly perfekt, but the dir_tree a the left always collapses when a page is clicked. 

I compared the two config.yml and can not find a reason, tried different changes with no effect. 
(see my yml below made to *.txt to get it uploaded, German).

Any idea where I can look? what I can change to make it work as expected? Would be very appreciated :-) 

[config_yml.txt](https://github.com/obsidian-html/obsidian-html/files/10705803/config_yml.txt)

btw: I run 3.4.1

**Comment by HKohlhoff** [comment]
further information: now it gets a bug I think...

I found out: this behavior ist due to a html-prefix given. 
I changes this in the documentation-vault config.yml to A and (simple and no hash as in my example) - and the dir_tree collapses all the time :-( 

would be very nice, if this could be fixed...

**Comment by dwrolvink** [comment]
try installing the master branch code and running again
for me it's now fixed

**Comment by HKohlhoff** [comment]
love it. Any Yes, with the latest version it now does its job in my case also. 

I am impressed by the quick and valuable answers and help. Thank you!
