### ISSUE TITLE
Note title alway converts second and followed words to lowercase - wrong in German

### ISSUE THREAD

**Issue by HKohlhoff** [obsidian-html/obsidian-html#587]
Hello again,
the attached screenshot shows the problem:
the note title has uppercase second (and may be following) words, which need to be written that way to be proper German.
In the dir_tree, the breadcrumbs, the link all is fine, except in the note-title - which is the main think to look at and read.

I could not find a way to hinder that. Is there a chance to get that running? A toggle to allow case-changes in notes-title,... or something similar?
<img width="1289" alt="Question" src="https://user-images.githubusercontent.com/76616522/218254551-6760895f-9732-4094-b485-609a709d12b6.png">

**Comment by dwrolvink** [comment]
## fixed
There was a stray `title.capitalize()` in the code from an earlier iteration. As you demonstrated, the capitalization works correctly out of the box, so such a call does more harm than good.

I removed it, if you install the latest master code there should then be richtiges Deutsch in your html output.

## custom embedded title content
You were looking for some options in changing the embedded titles content. As of writing there are these options, which may prove valuable for more niche usecases:

- Add an h1 at the top of your note, with the correct spelling, this should overwrite the embedded title in the output.
  - Note that this will not happen if you have a table of content be placed at the top of your note (niche, but good to know).
- Add `graph_name: Lineare Gleichungen` to your frontmatter yaml, e.g.:
    ``` md
    ---
    Tags:
      - HAW
      - AlgeTut
    Typ: Projekt
    Status: Idee
    graph_name: Lineare Gleichungen
    ---
    
    Lineare Gleichungen sind die ...
    ```

**Comment by HKohlhoff** [comment]
woau... Your are great. Thanks a lot. Now it s perfect.

I really appreciate your work and the competent quick replies.

**Comment by dwrolvink** [comment]
np, glad I could help
