### ISSUE TITLE
Template file not being generated

### ISSUE THREAD

**Issue by MikeHigginbottom** [obsidian-html/obsidian-html#599]
When running `obsidianhtml export layout -o minimal.html -l minimal` it returns the error message `Provided layout name of minimal is unknown` and no output template file is generated. Works as expected for `tabs` and `documentation` layouts. However, the error message also states to `Use `obsidianhtml export -l <documentation/tabs/no_tabs>` to provide input.` (possibly an update to docs required here?) Trying that gave a file not found error for `/home/mike/.local/lib/python3.10/site-packages/obsidianhtml/src/html/layouts/template_no_tabs.html`. That folder *does* contain `template_minimal.html`though which leads me to believe the original command should have worked fine. A work-around is to grab a copy of the template file directly from that folder. This was on Ubuntu 22.04.1 LTS.

**Comment by dwrolvink** [comment]
Woops, good find.
Should be fixed now with the latest patch.

You can install the latest version like this: https://obsidian-html.github.io/instructions/install-a-different-version.html#!install-master-branch
