### ISSUE TITLE
Does html_template_path_str work?

### ISSUE THREAD

**Issue by quenelle** [obsidian-html/obsidian-html#603]
I tried dumping the template, editing it, and using it in html_template_path_str, but I can't get it to work.  I tried using a relative path and a full path.  Other changes to the config file are known to take effect.  Any ideas what I should check?

**Comment by dwrolvink** [comment]
Hi, I just tried this with the current master branch and it works for me, simplified config:

``` yaml
obsidian_entrypoint_path_str: '/home/dorus/git/example_vault/vault/Blog/Welcome to my Homepage!.md'
html_template_path_str: /home/dorus/git/obsidian-html/here.html
```

Have you tried putting single quotes around the full path?
What version are you on? (try `obsidianhtml version`)

Try installing the master branch and see if that fixes the issue: 
``` bash
pip uninstall obsidianhtml
pip install git+https://github.com/obsidian-html/obsidian-html.git
```

If not, please post the output the command that you run generates

**Comment by quenelle** [comment]
Got it, thanks!  I'll try that.

**Comment by quenelle** [comment]
Ah ha!  Sorry for the noise, it was pilot error.
I dumped the default template and then changed something that turned out to be invisible.  All is well.

**Comment by dwrolvink** [comment]
:laughing: 

good to hear!
