### ISSUE TITLE
a template variable for the note title?

### ISSUE THREAD

**Issue by quenelle** [obsidian-html/obsidian-html#605]
I'd like to add the note title into the HTML page title (instead of just the site name) so that bookmarks and dragged links show the page title.  I can do this in a manual template, but I need to know how to export a new template variable.

**Comment by dwrolvink** [comment]
This is the main function call to inject values into the html template:
https://github.com/obsidian-html/obsidian-html/blob/4d5c330ca1e06637c775848eeaee9950bcbae66a/obsidianhtml/md2html/__init__.py#L352

Here, node["id"] should be pretty much the name of the note.
If you want more control then the function/function call should be edited to add more information into the function.

The function itself is pretty straightforward, just add a replace statement to replace you placeholder of choice with your value:
https://github.com/obsidian-html/obsidian-html/blob/4d5c330ca1e06637c775848eeaee9950bcbae66a/obsidianhtml/compiler/Templating.py#L194

**Comment by dwrolvink** [comment]
Note that you can set the `title` argument in the function call, so replacing:
``` python
html = PopulateTemplate(pb, node["id"], pb.dynamic_inclusions, pb.html_template, content=html_body) 
```
with 
``` python
html = PopulateTemplate(pb, node["id"], title=node["id"], pb.dynamic_inclusions, pb.html_template, content=html_body) 
```

Should probably get you 90% there

**Comment by cquenelle** [comment]
I needed node["name"] instead of node["id"]
There were other replaces right after the call to PopulateTemplate, so I just added it there.

**Comment by cquenelle** [comment]
I did this:
```
--- a/obsidianhtml/md2html/__init__.py
+++ b/obsidianhtml/md2html/__init__.py
@@ -351,6 +351,7 @@ def convert_markdown_page_to_html_and_export(fo: "FileObject", pb, backlink_node
     # ------------------------------------------------------------------
     html = PopulateTemplate(pb, node["id"], pb.dynamic_inclusions, pb.html_template, content=html_body)
 
+    html = html.replace("{node_name}", node["name"])
     html = html.replace("{pinnedNode}", node["id"]).replace("{html_url_prefix}", html_url_prefix).replace("{page_depth}", str(page_depth))
     # [?] Documentation styling: Navbar
     # ------------------------------------------------------------------
```
which seems to get me what I'm looking for.
I looked into updating the default HTML page title to include the node title.  This seems traditional.  So you'd want something like:
```
<site title> - <page title> 
```
to show up in the title bar or when you drag a link.
But it looks like {title} is also used in other places, and I didn't want to mess up anything else.
