### ISSUE TITLE
Option to use links instead of copying files

### ISSUE THREAD

**Issue by sevmonster** [obsidian-html/obsidian-html#619]
On compatible filesystems, it would be best to use symbolic or hard links instead of copying files to the destination. This is especially important for vaults with lots of large files, like high-resolution images, videos, and the like. A new option could be added to specify the type of copy.

From glancing at the code this doesn't seem too difficult to implement and would vastly cut down on processing time and output filesize. I plan to try implementing this possibly this weekend.

**Comment by dwrolvink** [comment]
That'd be great. Be sure to make it togglable. I know that git does not get symlinks, at least not by default, so anyone writing to a git repo and then pushing is going to have symlinks in their repo instead of the actual files.

**Comment by sevmonster** [comment]
Yes, it should be disabled by default. Some filesystems may not support a particular type of link, for example `vfat` does not support any links. The webserver or proxy may also not have permission to access the files depending on how the OS implements its file permissions and security. If any, hardlinks would be the most compatible to set as default, but that might introduce permissions issues too.
