### ISSUE TITLE
show tab page title instead of "Notes"

### ISSUE THREAD

**Issue by huangziwei** [obsidian-html/obsidian-html#625]
Currently obsidian-html rendered tag pages with an tittle `<h1>Notes</h1>`.

https://github.com/obsidian-html/obsidian-html/blob/f933deb96f65069fc24e0db0b2fa2cbc0be8bb2a/obsidianhtml/compiler/HTML.py#LL109C9-L109C9

It'd be better if it shows the tag per se instead.

**Comment by dwrolvink** [comment]
Agreed, thanks for the report.
I've updated it, you can install the code in the master branch to use these changes, or wait for the release of version 4.
