### ISSUE TITLE
Question marks and hyphens in filenames not handled properly

### ISSUE THREAD

**Issue by blacklightpy** [obsidian-html/obsidian-html#627]
In my website, there is a file ending with ?. In the URL, when I click it, it shows ? instead of %3F, so the link is broken.

**Comment by blacklightpy** [comment]
It also removed - from a page link:
https://blacklightpy.github.io/vaultofknowledge/Motors%20To%20Read.html
instead of
https://blacklightpy.github.io/vaultofknowledge/Motors%20-%20To%20Read.html

For now I'm renaming them to make it work.

I'm using master from pip btw.

**Comment by dwrolvink** [comment]
Good find, there is probably a missing urlencode step somewhere. 
I'm happy that workaround was available to you.
Will keep this issue open until I get around to fixing it (bit short on time atm).

**Comment by dwrolvink** [comment]
I was able to reproduce an issue with the question marks. It now checks whether the link ends with `.md` and in that case it won't treat a question mark as a query delimiter, so it is properly encoded.

I found no issues with hyphens/spaces.
Could you provide me with a note path in your vault that contains hyphens, and the markdown links that you have in another note that are not working?

**Comment by dwrolvink** [comment]
To try out the updated code:

staying on version 3.5.x:
``` bash
pip uninstall obsidianhtml
pip install git+https://github.com/obsidian-html/obsidian-html.git@v3.5.x
```

Moving to version 4, tracking latest changes (might require some changes in your config.yml):
``` bash
pip uninstall obsidianhtml
pip install git+https://github.com/obsidian-html/obsidian-html.git
```

**Comment by blacklightpy** [comment]
I was busy for a while here.. I'll need to modify my config now because it has some deprecated flags.
I'll check in a few days.

**Comment by blacklightpy** [comment]
Question marks and hyphens are working now.

https://blacklightpy.github.io/vaultofknowledge/Motors%20-%20To%20Read.html
https://blacklightpy.github.io/vaultofknowledge/What%20are%20Codecs%3F.html

**Comment by blacklightpy** [comment]
> Could you provide me with a note path in your vault that contains hyphens, and the markdown links that you have in another note that are not working?

The note path with hyphens is working as I just said. There weren't any backlinks to that page, I was referring to the link from the index. So all seems OK.
