### ISSUE TITLE
Search not working properly

### ISSUE THREAD

**Issue by blacklightpy** [obsidian-html/obsidian-html#628]
In my site https://blacklightpy.github.io/vaultofknowledge/:

If I search the term "ric", it shows a file titled [Ricer Guide](https://blacklightpy.github.io/vaultofknowledge/Ricer%20Guide.html), but it does not find [Rices I want to try out](https://blacklightpy.github.io/vaultofknowledge/Rices%20I%20want%20to%20try%20out.html).

It seems to not be a problem of it only looking for text in the content, because it finds other files which only have the words in the title.

**Comment by blacklightpy** [comment]
It also removed - from a page link:
https://blacklightpy.github.io/vaultofknowledge/Motors%20To%20Read.html
instead of
https://blacklightpy.github.io/vaultofknowledge/Motors%20-%20To%20Read.html

**Comment by blacklightpy** [comment]
For now, I'm renaming them to make it work.

**Comment by blacklightpy** [comment]
This is now working, after I renamed to fix the issues in #627, although I don't know if it has any correlation.

**Comment by dwrolvink** [comment]
note to self: check search finding pages with `?` in the name

**Comment by blacklightpy** [comment]
It does not find the file 'What are Codecs?' in search. But the file link itself is working correctly. I'm on v4/master.

**Comment by blacklightpy** [comment]
> If I search the term "ric", it shows a file titled [Ricer Guide](https://blacklightpy.github.io/vaultofknowledge/Ricer%20Guide.html), but it does not find [Rices I want to try out](https://blacklightpy.github.io/vaultofknowledge/Rices%20I%20want%20to%20try%20out.html).

The original search query does work now even though I added back the files with question mark and hyphens.

**Comment by dwrolvink** [comment]
if you type "rices", does it find your page then?
the search engine that I am using uses some weird "advanced" tokenizer that I do not fully understand, and this is hard to test/fix...

**Comment by dwrolvink** [comment]
hmm seems fine to me
![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/ffb643f3-d2a0-4d0a-b087-dd4122ca4e3a)

not sure what you meant
Is your issue solved now?

**Comment by blacklightpy** [comment]
Yes, it works now. It was a weird issue that only appeared before I first removed the files with the question mark and hyphens.

I am not able to replicate this issue anymore.

**Comment by dwrolvink** [comment]
Good! Let me know if that changes.
