### ISSUE TITLE
ConvertObsidianPage list behavior does not match Obsidian

### ISSUE THREAD

**Issue by drewp** [obsidian-html/obsidian-html#660]
When I put no newline before list items:
* like
* this,
obsidian-html treats the stars as italics. Obsidian (and Github, right here) renders list items.

Please see https://bigasterisk.com/vault/test/close-list.md and https://bigasterisk.com/code/vaulterrific/files/7d8afecdf5af61d48873f4516d606990b4609253/doc_display.py

**Comment by dwrolvink** [comment]
So believe it or not, you are the first to request asterisk list items to be implemented, and I never noticed this missing.

The latest change adds this:
``` md
List with dashes:
- one
- two
Non list line

Lists with asterisks:
* one  
* two
Non list line

List with extra stray asterisk
* test*
Non list line
```

![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/01757bde-7b36-4c3d-ac9c-ba16488d6965)

The code responsible for this behavior can be found here:
https://github.com/obsidian-html/obsidian-html/blob/a7012753f4c5ff1729180dfaf53f04255400a771/obsidianhtml/parser/MarkdownPage.py#L247-L275

You call this function so installing the code in the master branch should fix this.
Alternatively, you could splice in the change above into your local MarkdownPage.py file without issue.

Closing this for now to clean up, if you have any remaining issues / follow up questions, feel free to post here regardless.

**Comment by drewp** [comment]
LG, thanks!
