### ISSUE TITLE
Embeded svg-images are broken

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#670]
In "7 Exkurs in http://localhost:8888/BBZ/Unterricht%20CTA%20SuS/Chemie%20-%20Formeln%20mathjax%20Unicode.html one doesn't see the embeded svg-image.

You wrote:

This is not yet supported, you can put the code in a separate svg image and use that.
You can also make an issue to request inline svg images to be implemented.

**Comment by dwrolvink** [comment]
Made a quick edit, didn't get around to testing its impact on the rest of the code yet, but I am cautiously optimistic.

In obsidian:
![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/a55cf75c-6426-4052-8398-bd681ee29a26)

In the browser:
![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/f50d6cce-05c8-49a5-8da6-ed7dc18cfe39)


There seems to be a general issue with text looking different, your example - for example:

In obsidian:
![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/84566417-1550-46d7-8701-5fdde965bf64)

In the browser:
![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/18332075-a123-4e80-90bb-e1494d1c64f8)


I don't know enough about svgs to debug this at the moment, to be continued.

**Comment by dwrolvink** [comment]
So regarding the sub-superscript, there is an open issue for firefox that is 18 years old, and still active :see_no_evil: 
https://bugzilla.mozilla.org/show_bug.cgi?id=308338

I guess that is not something that can be fixed. I did find `dy: 5px` but that resets the baseline to everything in the text field, which makes it really hard to do this as an add-on fix on standard svgs. It would work if you have a `<text>` for every char, but then the positioning becomes a real headache, so unless you have an svg tool that can make these changes for you, I guess you are out of luck on firefox at least.

For font-sizing, there is a fix that works for both firefox and chrome, rendering the svg above identically in chrome and obsidian:
``` html
<svg style="border: solid white 1px; fill: white;" xmlns="http://www.w3.org/2000/svg" width="190" height="80">
  <rect x="0" y="0" width="225" height="150" style="fill: #c81c80;" />
  <text x="10" y="25" style="font-size: 1rem;">Summenformel:</text>
  <text x="60" y="55" style="font-size: 1rem;">C<tspan baseline-shift="sub">6</tspan>H<tspan baseline-shift="sub">6</tspan></text>
</svg>
```
Note the moving of `font-size` from an attribute to the inline-css `style=""` section.

**Comment by merlinuwe** [comment]
A second font-size: 1.5rem gives exactly the result of the origin svg file:

```
<svg style="border: solid white 1px; fill: white;" xmlns="http://www.w3.org/2000/svg" width="190" height="80">
  <rect x="0" y="0" width="225" height="150" style="fill: #c81c80;" />
  <text x="10" y="25" style="font-size: 1.5rem;">Summenformel:</text>
  <text x="60" y="55" style="font-size: 1.5rem;">C<tspan baseline-shift="sub">6</tspan>H<tspan baseline-shift="sub">6</tspan></text>
</svg>
```

As long as the ghostscript tiger is perfect, see

http://localhost:8888/BBZ/Unterricht%20CTA%20SuS/Obsidian%20-%20Einzelthemen.html

embeded with

![[BBZ/Unterricht CTA SuS/Bilder - verschiedene Formate/Ghostscript_Tiger.svg|40]]

there is no need to investigate further.
