### ISSUE TITLE
Clicking on an image directly is showing it very big (not reproducable)

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#671]
If I click on an image in the folder "Bilder - Firmenlogos", the image was _once_ seen very big. Now it is normal. Have a look at it; not reproducable for me at the moment.

---

You wrote:

There has been a minor css change between 3.5.1 and 3.5.2, maybe you are experiencing that (if the image is in a table).

---

No, the image is not linked or included in a note.md file. I clicked on an image directly.

**Comment by dwrolvink** [comment]
I don't know what you are talking about and if it is not reproducible, I cannot work on this.
I will keep it in the back of my head, if I ever find something similar I will post here if I remember how to find this issue.
