### ISSUE TITLE
(Searching for non .md files is not possible

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#674]
Searching finds only .md files. But I have a lot of other files (more than .md).

**Comment by dwrolvink** [comment]
Works now for me:

![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/8598924b-e6dd-4bcc-9686-9c81283f8690)

![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/7a95b95b-8902-4196-8db8-386f4962da1a)

**Comment by merlinuwe** [comment]
.webp files are downloaded, not shown. Can you please consider to add .webp to be shown instead of downloaded?

Excitation: Unicode search (example: ⇄) is not possible. Could be interesting for chemistry, mathematics. Also: Greek alphabet, other languages and their signs/letters. 

Tested with a few file types (jpg, gif, png, svg, doc, docx, xlsx, accdb, ) - ok. This helps a lot, thank you very much.

**Comment by dwrolvink** [comment]
For me, in both FF and Chrome, the webp files are opened in a tab, not downloaded:

![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/d8b8ebf6-5903-46ae-92a5-78fc1fa3e757)
![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/4ad7fa59-8dc8-49ae-aee4-7f5030c3d984)

**Comment by dwrolvink** [comment]
Somehow, I can configure it to have greek chars be searchable: 
![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/62197da3-7e38-4bac-ad26-07df9daa332c)

I think this should already work in the current version.

But ⇄ remains unattainable.

It does show up in the content, the content is searchable, but there is something going on with the tokenization that throws soot into the water
![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/aa85b46a-6cbf-4387-bd6a-af2fef9c9aa3)

**Comment by merlinuwe** [comment]
Not perfect, but OK. Search for unicode is not so often used, but for files.
