### ISSUE TITLE
embedded pdf files not shown

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#676]
This is an issue which possibly affects a lot of users, so I'd suggest to give it a priority.

`![[Unicode Pfeile U2190.pdf]]`

Here you see what I see in the output:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/55f638ce-ca0d-4e25-bbc2-64cfc69cac18)

This is what I see in Obsidian:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/c17b9bc0-99e1-418d-abc1-84964f34fd12)

**Comment by dwrolvink** [comment]
Can you rightclick inspect and find the embed part?

For me, it looks like this, and works fine on firefox, chrome, and android.
![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/bc9bbdf8-83d4-412d-ab75-91eb20e4705f)


This sounds like a specific issue with your browser. Which one are you using?

Can you see the pdf at the bottom of section 1 here?
https://pspdfkit.com/blog/2021/how-to-embed-a-pdf-viewer-in-your-website/#_1-using-the-embed-tag

**Comment by merlinuwe** [comment]
I always use Google Chrome for testing. Now it is 

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/e59443f3-4e65-47b0-abc0-5aeff4f66e7c)

(Also tested in a new incognito window.)

Same result.

BUT: Tested on my portable Google Chrome: works: 

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/e616725d-0c32-4fa4-8c03-0091c5493471)

--> Must have anything to do with my installed release of Google Chrome (any idea?)

;-)


---

But in Firefox, I actually see this,

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/a52535a0-8538-44dc-b298-c0d73ce1fb69)

which is ok.

---
Edge is also ok:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/cf4560ce-4058-486f-8f18-b36e1448eb06)

---

**Comment by dwrolvink** [comment]
You might want to check the extensions that are installed on chrome, perhaps there is some outdated pdf extension that isn't working? Other than that, no idea.
