### ISSUE TITLE
Linking to a file type .docx

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#677]
Here you see the link to a docx file in Obsidian:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/7658f480-7595-41cd-928d-73416ffbaf92)

Here you see how it is shown in the output:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/e1ce1178-8edd-4610-81bf-908cdd5857e2)

(I want to be able to click on the link and download the file.)

**Comment by dwrolvink** [comment]
Okay, now when it recognizes an include, and it is not an `.md` file, nor an includable file: instead of writing an error,  it creates a download button.

Should work out of the box as long as you are on the master branch

![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/a2a36216-7caf-42de-88a3-d7a6f5d54417)

**Comment by merlinuwe** [comment]
(Updated a few minutes ago. "Successfully installed obsidianhtml-4.0.0a0")

I call this site:

http://localhost:8888/BBZ/Unterricht%20CTA%20SuS/MS365%20-%20Mathematische%20Formeln%20und%20Unicode.html

I see this (perhaps the path, shown at the bottom of the image is interesting you):

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/a28ec860-8894-4560-8d34-f55019d07888)

There is no button, only a link.

If I click on the link, I get this URL:

http://localhost:8888/BBZ/Unterricht%20CTA%20SuS/2023-04-09%20Alle%20mathematischen%20AutoKorrektur-Zeichen.docx%7C_obsidian_html_download_button_

and see this in the webbrowser (Google Chrome, latest)

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/c9e9ff46-90b9-499b-a99b-be5941b91789)


(Can you please give the 4.0.x alphas a trailing number or something so that I can be sure to test with the latest release?)

**Comment by dwrolvink** [comment]
I missed the url encoding, which means that it would create non-compliant markdown links, which in turn meant my regex was not picking up the links to be wrangled into a download button.

This specific issue should be fixed now.

> (Can you please give the 4.0.x alphas a trailing number or something so that I can be sure to test with the latest release?)

That is very cumbersome for me.

You can install obsidianhtml like this, then the version command will give you the commit:
``` bash
# uninstall obsidianhtml installed by pip to be sure we don't use it
pip uninstall obsidianhtml

# move to a folder where you want to install obsidianhtml
cd C:/Users/uwewe/Downloads

# git clone this project
git clone https://github.com/obsidian-html/obsidian-html.git

# move into the git folder
cd obsidian-html

# try out 
python -m obsidianhtml version
```

![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/ae4ecb7f-da54-48be-922d-4f6be7640d5f)

Then to get the latest changes, be sure to be in the git folder then run:
``` bash
git pull
```

That's all. Run all commands as normal, just prepend it with `python -m`

Note though that `python -m obsidianhtml` will only work when you are directly in that git folder.

**Comment by merlinuwe** [comment]
Works. I see the download buttons and they work.

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/122c71ce-8b80-44f4-9c8e-2af30f23f490)

To open or download them, one can activate/deactivate this on a per filetype base here:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/eca04011-7f70-4bb2-9cc0-7fe12cba69c8)


Thank you VERY much!

**Comment by dwrolvink** [comment]
You're welcome!
