### ISSUE TITLE
Special characters being removed by mermaid plugin

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#68]
> Okay, fixed in 0.0.8
> 
> Compare: https://obsidian-html.github.io/?path=%2FResources%2FExample%2520site%2FesMermaid.html/ (dynamically loaded) https://obsidian-html.github.io/Resources/Example%20site/esMermaid.html (loaded normally).
> 
> mermaid.init() was the solution here.

I tested it. Now it deletes all Russian symbols in files.

_Originally posted by @slavamirniy in https://github.com/obsidian-html/obsidian-html/issues/18#issuecomment-1032657371_

**Comment by dwrolvink** [comment]
Compare
``` python
html_body = markdown.markdown(md.page, extensions=['extra', 'codehilite', 'toc', 'md_mermaid'], extension_configs=extension_configs)
```
vs 
``` python
html_body = markdown.markdown(md.page, extensions=['extra', 'codehilite', 'toc'], extension_configs=extension_configs)
```

The first case retains russian characters, the second case removes them. So there is something wrong with the mermaid plugin.

For now a workaround/fix is making this change here: https://github.com/obsidian-html/obsidian-html/blob/af75811442d502e3fd32c7713591200fc3ba4ebf/obsidianhtml/__init__.py#L218

Though that will break mermaid support.

Will investigate if there is a solution. Perhaps use a different plugin/mermaid parse method.

**Comment by dwrolvink** [comment]
This is a known issue in md-mermaid https://github.com/oruelle/md_mermaid/issues/2

**Comment by dwrolvink** [comment]
@slavamirniy 
I found some lines that cause the issue in the dependency, will send them a pull request, but for now this is the workaround:

``` bash
pip uninstall md_mermaid
pip install git+https://github.com/obsidian-html/md_mermaid
# python -m obsidianhtml -i config.yml
```
or 
``` bash
git clone git@github.com:obsidian-html/obsidian-html.git
cd obsidian-html
pip uninstall obsidianhtml
pip install dist/obsidianhtml-0.0.9.tar.gz 
# obsidianhtml -i config.yml
```

Will upload a new package this weekend after testing well, so the normall installation will then also be available.
Let me know if this solves this issue for you.

**Comment by slavamirniy** [comment]
My knowledge of English is not so great to be able to express my gratitude to you. Yes, everything works and works great. Thanks!

**Comment by dwrolvink** [comment]
No problem! Happy it works for you now :smile:
