### ISSUE TITLE
Animated .svg is static

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#710]
This soccer ball spins in Obsidian.

![Fußball](https://github.com/obsidian-html/obsidian-html/assets/4138869/29b7879e-fea7-4845-b940-a46fe86df0ef)

But here, it is static.

[This soccer ball spins.](http://localhost:8888/BBZ/Unterricht%20CTA%20SuS/Grundlagen%20-%20Alle%20Bildformate.html)

(BTW: animated .gif works, animated .png not tested.)

**Comment by merlinuwe** [comment]
Runs now with 
animated .png, 
animated .gif, 
animated webp. 

Thank you SOOOO much. ;-)

**Comment by dwrolvink** [comment]
works for me in the latest version (tested in firefox).
Not clear whether this was fixed for you or not going by your latest comment, if not we can reopen this.
