### ISSUE TITLE
No scrolling to the top when chosing a link in the left pane (table of contents)

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#711]
If I click on a link in the left pane, I get the corresponding note. (Thats ok.)

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/aca20e63-451c-4fe3-896d-39e850fc30ed)

But the page refreshes and the left frame shows the top of the list.

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/0a91fd78-e8e7-4e48-b030-a8a4c9b1975b)

The user wants to see the file he had choosen without scrolling down again. (So he can better click one file after each other, for example.)

**Comment by dwrolvink** [comment]
Latest change implements this.

I also went pretty crazy with all your nonmd links in between your notes, so I made a change to identify clearly what is a file (that will be opened/downloaded) and which is a markdown note

Screenshot how the page looks directly after opening `MS365 - Mathematische Formeln und Unicode.html`
![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/71384acb-2bed-418a-a1c4-05f04879ef1a)
