### ISSUE TITLE
Position of images in callouts not under, but next to the last text

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#712]
I have this callout with an image:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/80f93145-28c2-4dba-907b-ec7fe3aa09bc)

It looks so:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/af753cb8-9041-4261-bf7c-b8f19b3ddbaa)

However, the picture is not _under_ the last text, but _next_ to it.

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/9ae7280a-fc1b-4abb-80a1-3542d4c7d1d7)

**Comment by dwrolvink** [comment]
Latest change fixes this for me.

This is done by putting three spaces behind every line, which is done everywhere else to get the markdown to be parsed very close to what Obsidian does. (enter = newline, etc)

The callout code stripped those three spaces out through, and I never put them back in, hence the difference in rendering.

![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/274a7e83-ba7f-437b-bdc3-b9202b4250d5)
