### ISSUE TITLE
Left and right pane are not shown when one clicks on a link to a non existing note

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#714]
I have these two links, but there exist _no_ notes for them:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/495cffe7-222c-4c42-9119-fa8757e002c1)

http://localhost:8888/BBZ/Unterricht%20CTA%20SuS/LABV%20INF.html

If I click on them in the output

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/925aaf2e-0130-4b85-b43e-bfd2e5f47c1f)

and I'm getting this:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/616251e8-6386-4430-b6b1-83936991ff6b)

The problem: Left pane and right pane are not shown.

**Comment by dwrolvink** [comment]
ah yes, I keep forgetting that this is broken, thanks for the issue!

**Comment by dwrolvink** [comment]
Is fixed now in master!
