### ISSUE TITLE
White screen when people switch between notes is blinding

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#723]
Every time I switch between files (left pane), there is a white screen (~ for a fracture of a second) in the browser. Is it possible to make this page black or show alternatively show the new page only when it is fully rendered?

This is stressing people who use dark themes. To much contrast in dark environments.

(This is no problem, when using the white theme.)

---

BTW: Have you eleminated one theme? I could swear there were three of them.

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/f7114d72-a249-4ea7-931a-48fc4496219e)

**Comment by dwrolvink** [comment]
Try setting this in your config:

``` yaml
toggles:
  features:
    styling: 
      loading_bg_color: '22, 22, 22'
```

And yes, I removed `light`, it was janky, obs-light and obs-dark are way cleaner.
I guess I could rename them now to just "light" and "dark" though.

**Comment by dwrolvink** [comment]
nb. you have to set the bg, as the loading takes long enough that any check for the current theme + setting the loading bg to the correct color for the theme is too slow, you still get the flashing then.

I guess I should just set the default value to this value, as it is way less obtrusive in the light theme than the other way around, better default.

**Comment by merlinuwe** [comment]
MUCH better. Thank you, from my eyes, too. ;-)
