### ISSUE TITLE
Show graph does not work anymore

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#726]
I have already seen this working. I think, this issue must be located in one of the last releases.

Clicking on it has no effect.

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/6ec6bbfe-0e65-40e2-bcb5-eb40310fd7a5)

**Comment by dwrolvink** [comment]
Works for me:
![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/44a5158f-38fe-4a02-9a77-bdaa383a9264)

If you press F12 and click on `console`, does it show errors?

**Comment by merlinuwe** [comment]
This is the last output of the script:

b'C:/Users/uwewe/AppData/Roaming/Python/Python311/Scripts/output/md/Privat/Kunst Lyrik/Zitate - Brand eins.md'
b'C:/Users/uwewe/AppData/Roaming/Python/Python311/Scripts/output/md/Privat/Kunst Lyrik/Zitate - Controlling.md'
b'C:/Users/uwewe/AppData/Roaming/Python/Python311/Scripts/output/md/Privat/Kunst Lyrik/Zitate - Quellen.md'
        > COMPILING INDEX FROM DIR STRUCTURE (C:\Users\uwewe\AppData\Roaming\Python\Python311\Scripts\output\html\obs.html\dir_index.html)
        < COMPILING INDEX FROM DIR STRUCTURE: Done
        > SECOND PASS HTML
        < SECOND PASS HTML: Done
< COMPILING HTML FROM MARKDOWN CODE: Done
> EXPORTING USER FILES


Is this config.yml correct?

[config.yml.txt](https://github.com/obsidian-html/obsidian-html/files/11525629/config.yml.txt)

**Comment by dwrolvink** [comment]
Does `custom.css` exist in the root of your vault?, ie at `H:/Syncthing/Obsidian/custom.css`?

> If you press F12 and click on console, does it show errors?

Can you answer this please.

**Comment by merlinuwe** [comment]
Has it to be exactly this name custom.css? Because now it works.

b'C:/Users/uwewe/AppData/Roaming/Python/Python311/Scripts/output/md/Privat/Kunst Maltechniken/Zeichnen.md'
b'C:/Users/uwewe/AppData/Roaming/Python/Python311/Scripts/output/md/Privat/Kunst Maltechniken/Zeichnen - \xdcbung zum Schraffieren.md'
b'C:/Users/uwewe/AppData/Roaming/Python/Python311/Scripts/output/md/Privat/Kunst Lyrik/Zitate - Brand eins.md'
b'C:/Users/uwewe/AppData/Roaming/Python/Python311/Scripts/output/md/Privat/Kunst Lyrik/Zitate - Controlling.md'
b'C:/Users/uwewe/AppData/Roaming/Python/Python311/Scripts/output/md/Privat/Kunst Lyrik/Zitate - Quellen.md'
        > COMPILING INDEX FROM DIR STRUCTURE (C:\Users\uwewe\AppData\Roaming\Python\Python311\Scripts\output\html\obs.html\dir_index.html)
        < COMPILING INDEX FROM DIR STRUCTURE: Done
        > SECOND PASS HTML
        < SECOND PASS HTML: Done
< COMPILING HTML FROM MARKDOWN CODE: Done
> EXPORTING USER FILES
        Writing C:/Users/uwewe/AppData/Local/obsidianhtml/obsidianhtml/tmpdir/input/custom.css to C:/Users/uwewe/AppData/Roaming/Python/Python311/Scripts/output/html/custom.css (utf-8)
< EXPORTING USER FILES: Done

You can find your output at:
        md: C:\Users\uwewe\AppData\Roaming\Python\Python311\Scripts\output\md
        html: C:\Users\uwewe\AppData\Roaming\Python\Python311\Scripts\output\html

uwewe@Uwe-PC-SSD MINGW64 ~/AppData/Roaming/Python/Python311/Scripts

**Comment by merlinuwe** [comment]
But the graph is not showing.

**Comment by merlinuwe** [comment]
F12 console gives this:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/9daf2fd4-ba8c-4a6d-b1e5-b296afcad37b)

**Comment by dwrolvink** [comment]
Does this happen on every page? I tested with your index page from unterricht, do you have this issue there?

> Has it to be exactly this name custom.css? Because now it works.

When I showed you the code for the custom.css, I did state that you had to create that file in the root of your vault **unless** you changed the paths in the config.yml, which you did not do, so yes, if you configure a file export, the file needs to exist at that specific location.

**Comment by merlinuwe** [comment]
Yes, I cannot see the graph, independend of the chosen file. Examples I currently tested:

http://localhost:8888/BBZ/Unterricht%20CTA%20SuS/Arbeiten%20-%20CTA.html

http://localhost:8888/BBZ/Unterricht%20CTA%20SuS/Chemie%20-%20Formeln%20mathjax%20Unicode.html

http://localhost:8888/BBZ/Unterricht%20CTA%20SuS/Chemie%20-%20Smiles%20Formeln.html

(I find no file, where the graph shows.)

...

**Comment by dwrolvink** [comment]
What command did you use to start the webserver?

![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/edb1696b-953d-4159-a716-262857eb7922)

I remember that error, but I don't get it anymore with `python -m http.server`
`obsidianhtml serve` has this code added though:
``` python
    Handler.extensions_map.update(
        {
            ".js": "application/javascript",
        }
    )
```

which ought to fix this issue, you might try `obsidianhtml serve --directory <directory path> --port 8080`
(Be sure to go to `http://localhost:8080` instead of  `http://localhost:8888`)

**Comment by dwrolvink** [comment]
Might try this fix on Windows also:
![](https://i.stack.imgur.com/DLBOS.png)

As per: https://stackoverflow.com/questions/64013643/failed-to-load-module-script-the-server-responded-with-a-non-javascript-mime-ty

(Make sure that key `Content Type` exists in that location as shown in the registry editor.)
Not sure if this is the issue though, Windows tires me.

Though as said in that thread, just restarting the server with port `8080` (or any other) might also work? :thinking:

**Comment by merlinuwe** [comment]
Njet. 

I see this:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/9adc371d-ec94-47e9-85ce-0d394a218cda)

Shall I change Content Type to "text/javascript"? I do it ... restart the webserver with

python -m http.server --directory output/html 8080

и большая улыбка пробегает по моему лицу

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/cfc12fb5-ccea-42c5-b3fb-3d44fd5323d9)

;-) 
Thank you again!

**Comment by merlinuwe** [comment]
(Your solution works with both ports, 8080 and 8888)

**Comment by dwrolvink** [comment]
nice!
