### ISSUE TITLE
Buttons plugin; call program

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#727]
In the head of a note i have this:

---
aliases: ekb, Klassenbuch
tags: Klassenbuch, eKb, wichtig
disabled rules: [ all ]
cssClasses: 
number headings: first-level 2, max 6, 1.1, auto, contents ^toc
erstellt: Mittwoch, 30. November 2022, 13:26:26 Uhr
geändert: Samstag, 14. Januar 2023, 17:17:02 Uhr
---

```search-bar
only search bar
show starred files
```

<span class="letzteAenderung">(Letzte Änderung: `=dateformat(this.file.mtime, "DDDD, HH:mm")` Uhr)</span>

[[Notizen]] [Hilfe](Hilfe.md)^[Bearbeiten/Lesen: `<Strg-e>`, Datum: `<Alt-d>`, Uhrzeit: `<Alt-t>`, Task: `<Strg-l>`, Linter: `<Strg-Alt-l>`, CSS: `<Strg-Shift-i>`, GPT3: `<Strg-f>`, Einstellungen: `<Strg-,>`, kursiv formatieren: `<Strg-i>`, fett formatieren: `<Strg-b>`, Verlinkung auf eine url []() einfügen: `<Strg-k>`.]

`button-mitteilungen` `button-telefonliste` `button-m` `button-m2` `button-m3` `button-gmail` `button-calendar` `button-dcp` `button-homepage` `button-hesk` `button-webuntis` `button-mv` `button-ov` `button-sus` `button-whatsapp`

[Excel](<file:///"C:\Program Files\Microsoft Office\root\Office16\EXCEL.exe">) [Access](<file:///"C:\Program Files\Microsoft Office\root\Office16\MSACCESS.EXE">) [Word](<file:///"C:\Program Files\Microsoft Office\root\Office16\WINWORD.EXE">) [PortableApps](<file:///"P:\PA\PortableApps\Start.exe">) [Everything 1.5β](<file:///"P:\PA\1111-Everything 1.5 64bit\Everything64.exe">) [Notepad++](<file:///"P:\PA\PortableApps\Notepad++Portable.exe">) [Verzeichnis P:\N](file:///"P:\N") [XMind](<file:///"C:\Program Files (x86)\XMind\XMind.exe">)

[Nachschreibtermine](https://bbz-dormagen.de/bildungsangebote-des-bbz-dormagen/weiterbildung/fachschule-fuer-wirtschaft-schwerpunkt-logistik/) [Nachschreiberliste etc.](<file:///P:\N\START.py>) [Etherpad](https://pads.domainepublic.net/p/Lokistick) %%[Telefonliste (lokal)](<file:///"P:\N\BG\tiddlywikilocations\Dokumente BBZ\Telefonliste\Telefonliste.pdf">) [Telefonliste in Moodle M](<https://m.bbz-dormagen-moodle.de/mod/resource/view.php?id=240>) %% [Meldeblatt Feueralarm](<file:///"P:\N\BG\tiddlywikilocations\Dokumente BBZ\Meldeblatt Feueralarm Verhaltensregeln.pdf">) [HH Zentrale Klausurtermine Q1](HH_Zentrale%20Klausurtermine_2022_2023_1.Quartal.pdf) [HH Zentrale Klausurtermine Q2](HH_Zentrale%20Klausurtermine_2022_2023_2.Quartal_071122.pdf)

<span class="fw">[FW20A WI](<file:///P:\N\2. FW20A US WI CTR 2020-23\START_WI.pyw>)</span>  <span class="fw">[FW20A CTR](<file:///P:\N\2. FW20A US WI CTR 2020-23\START_CTR.pyw>)</span>  <span class="fw">[FW21A WI](<file:///P:\N\5. FW21A US WI 2021-24\START_WI.pyw>)</span>  <span span class="fw">[FW22A WI](<file:///P:\N\6. FW22A US WI 2022-25\START_WI.pyw>)</span>  <span class="hh">[HH21AB INF](<file:///P:\N\HH21AB OS INF 2021-23\START_INF.pyw>)</span>  <span class="hh">[HH22C INF](<file:///P:\N\HH22C US INF 2022-24\START_INF.pyw>)</span> <span class="cta">[CT22A INF](<file:///P:\N\CT22A US INF 2022-23\START_INF.pyw>)</span>

[[eKb#2.1 [FW22A US WI](<file:///P: N 6. FW22A US WI 2022-25 START_WI.pyw>) (19 → 16) Ab, Be Di, 17:00 - 18:20 Uhr R304|FW22A US WI]] [[eKb#2.2 [FW21A MS WI](<file:///P: N 5. FW21A US WI 2021-24 START_WI.pyw>) (17 → 12) Gs, Tu Di, 18:30 - 19:50 Uhr R304|FW21A MS WI]] [[eKb#2.3 [HH22C US INF](<file:///P: N HH22C US INF 2022-24 START_INF.pyw>)(26 → 25) La, Le Mo, 7., 13:10 - 13:55 Uhr Mi, 3. - 4., 09:20 - 10:55 Uhr R304|HH22C US INF]] [[eKb#2.4 [HH21AB OS INF](<file:///P: N HH21AB OS INF 2021-23 START_INF.pyw>) (13 → 11) Gt, Fi; La, Mu Mo, 4., 10:05 - 10:50 Uhr Mi, 6. - 7., 13:10 - 13:55 Uhr R304|HH21AB OS INF]] [[eKb#2.5 [CT22A US INF](<file:///P: N CT22A US INF 2022-23 START_INF.pyw>) (23 → 23) Mh, Ch Mo, 4. - 5., 11:10 - 11:55 Uhr R304|CT22A IS INF]]
## 1 Klassen

Do you have an idea to get the buttons plugin running?

https://github.com/shabegom/buttons

Or to call a program which resides on the local pc?

**Comment by dwrolvink** [comment]
Running local programs is not possible within a static webpage, which is what the output is, so this is not possible.

You can use css to hide the button code block, if you wish to do so.
