### ISSUE TITLE
Links of files ending with question marks not generated in Breadcrumbs

### ISSUE THREAD

**Issue by blacklightpy** [obsidian-html/obsidian-html#730]
![image](https://github.com/obsidian-html/obsidian-html/assets/28739146/5b2e25e4-d983-4830-8e90-6fec539d08db)
No link is generated for this file, titled 'What is a codec?'

**Comment by dwrolvink** [comment]
Should work now in master.
Let me know if this fixes it for you!

**Comment by blacklightpy** [comment]
I actually noticed that question marks don't work in Windows.. So I ended up not using them because I switch OSes at times.

Haven't tried on Linux, but I'm sure it'll work now if you think so.
