### ISSUE TITLE
Request for using non-tag metadata in filter_on_metadata module

### ISSUE THREAD

**Issue by cquenelle** [obsidian-html/obsidian-html#733]
I realized a while back that if I use tags to control which notes are published, then those specific tags don't really belong in the rendered site.  If I tag some notes as "blog" then when I publish every single page would be tagged "blog", which is odd.  What I want to write in the metadata is: "publish: true".

So it would be nice to have a metadata filter like:
{ "flag": "publish" }

Where the metadata publish property is expected to be True or False (False if not present)

Since it's not a tag it wouldn't automatically go into the displayed output.

**Comment by cquenelle** [comment]
If there was a preexisting general purpose syntax (python?) for comparing metadata that would be a more general form, but possibly less user-friendly and harder to get right and debug?

Example:

{ "expression": "publish == True" }

That would also get me what I want, but I'm not sure it's a good idea.

**Comment by dwrolvink** [comment]
Yeah I only added the `tagged` option as it was very simple to implement for a first iteration. A very general syntax would be imo:

``` yml
# valid for all types
{ "present": "category" }
{ "present": "tags/blog" }

# valid for all types of form `key: value` (i.e. anything except for list items)
{"equals": {"key": "publish", "value": "any kind of value, even dicts and bools"}}
```

Any nested keys can be addressed using the `/`, as shown in the example.

I don't like the `==` operator, as that would either require parsing, which is a pain to do well, or some kind of eval, which is a big no-no in general.

I like the `flag` operator, thats a very succinct way to define "present and true"

**Comment by dwrolvink** [comment]
Added the present, flag, and equals filter options.
See for usage info here:
- https://obsidian-html.github.io/v4/configurations/modules/filter-on-metadata.html

Let me know if this works for you.
