### ISSUE TITLE
ESC not available on smartphones

### ISSUE THREAD

**Issue by eurobots** [obsidian-html/obsidian-html#737]
Dear developers:

an easy possibility to end a started search on a smartphone would be nice to have.

ESC is normally not available on smartphones.

I would propose, that a RETURN key ends the search if and only if the search field is empty.

Thanks for the great work!

With best regards,

Udo

**Comment by dwrolvink** [comment]
I think emptying the search field and then pressing enter again is a bit complex, and not very obvious. It would also make the code messy in an annoying way.

I've added a button that replaces the "esc to dismiss" text. Esc still works. I had the plan first to toggle based on screen width, but I'm guessing this is also a problem for tablet users, so there's just a button now always.

![Screenshot_2023-06-03-17-18-52-981_org mozilla firefox](https://github.com/obsidian-html/obsidian-html/assets/30291690/25c0a3c7-064c-43ec-aa50-3ad138112587)

**Comment by dwrolvink** [comment]
It will probably take a while before version 4 is published, in the mean time you can choose to install v4 via git:
- https://obsidian-html.github.io/v4/instructions/install-a-different-version.html#!install-master-branch

Note that moving from v3 to v4 might require some config changes. If you read the errors carefully that should give you a good idea of what you need to remove/replace in your config settings (if applicable).

**Comment by eurobots** [comment]
I've installed version 4 and adapted the config.yml: I've had to comment out "log_output_folder_path_str" and "extended_logging".

The button works smoothly. Thank you!
