### ISSUE TITLE
Text height calculation

### ISSUE THREAD

**Issue by eurobots** [obsidian-html/obsidian-html#739]
Dear developers:

depending on how high the navigation bar is at the top, the height of the text below is being calculated differently.

This has two effects:

1. You can use the scroll bar to scroll up or down in the text.

   If the navigation bar at the top shows only three dashes and you scroll all the way down, you will not see a larger part of the scroll bar. This is not disturbing.

   If the navigation bar at the top takes up several lines, you will not be able to reach the lower part of the text by scrolling.

2. When you click on an item in the right Table of Contents pane, the view jumps to the corresponding heading and lights it up briefly. This works correctly if the navigation bar at the top contains exactly one line of text.

   If the navigation bar at the top shows only three dashes, you jump a little too high. This is not disturbing.

   If the navigation bar at the top takes up several lines, you jump too low. Then you may not have the headline and part of the text below it on the screen after the jump.

This behavior is reproducible, tested with Chromium and Firefox under Linux and with Chrome under Android.

I am happy to be available for testing.

With kind regards

Udo

**Comment by eurobots** [comment]
Forgot to say: I'm using obsidianhtml version 4.0.0-alpha.

**Comment by iamsuperdev** [comment]
Hello
How are you? I am volodymyr dubok.
I checked and I can help you right now.
I need your project source code.
Thank you.

**Comment by dwrolvink** [comment]
Used the code from your PR that I closed earlier and put it in the correct place + in an observer object so that the container height is set correctly each time the header changes size (by whatever cause).

The links ending up scrolling too high/low required a different solution.

Closing as it works for me. If you still face issues let me know then I'll reopen.
