### ISSUE TITLE
Inline code nested in code- or latex-blocks is not restored properly

### ISSUE THREAD

**Issue by Gewerd-Strauss** [obsidian-html/obsidian-html#741]
Take the following example note:
    
    `r     paste(signif(FieldCapacity$models$Used$lm100_used$coefficients{{2}},digits = 3))`
    
    $$
    \begin{align}  
      Potweight_{100\% FC} = ``r paste(signif(FieldCapacity$models$Used$lm100_used$coefficients{{2}},digits = 3))`` \times m_{S} + `r paste(signif(FieldCapacity$models$Used$lm100_used$coefficients{{1}},digits = 3))` \ [g](\#eq:fieldcapacityequation1_a)
    \end{align}  
    $$
    
    
    
    $$
    \begin{equation}  
      Potweight_{0\% FC} = `r paste(signif(FieldCapacity$models$Used$lm0_used$coefficients{{1}},digits = 3))`\times m_{S} + `r paste(signif(FieldCapacity$models$Used$lm0_used$coefficients{{2}},digits = 3))` \ [g](\#eq:fieldcapacityequation2_a)
    \end{equation}
    $$
    
    $$
    \begin{align}  
      Potweight_{100\% FC} = 1,7414\times m_{S} + 127,15 \ [g](\#eq:fieldcapacityequation1)
    \end{align}  
    $$
    
    $$
    \begin{equation}  
      Potweight_{0\% FC} = 0,6184\times m_{S} + 54,119 \ [g](\#eq:fieldcapacityequation2)
    \end{equation}
    $$
    
    
 resulting in the output 
 
     `r paste(signif(FieldCapacity$models$Used$lm100_used$coefficients{{2}},digits = 3))`
    
    $$
    \begin{align}  
      Potweight_{100\% FC} = `%%%codeline-placeholder-5%%%` \times m_{S} + %%%codeline-placeholder-8%%% \ [g](\#eq:fieldcapacityequation1_a)
    \end{align}  
    $$
    
    
    
    $$
    \begin{equation}  
      Potweight_{0\% FC} = %%%codeline-placeholder-11%%%\times m_{S} + %%%codeline-placeholder-12%%% \ [g](\#eq:fieldcapacityequation2_a)
    \end{equation}
    $$
    
    $$
    \begin{align}  
      Potweight_{100\% FC} = 1,7414\times m_{S} + 127,15 \ [g](\#eq:fieldcapacityequation1)
    \end{align}  
    $$
    
    $$
    \begin{equation}  
      Potweight_{0\% FC} = 0,6184\times m_{S} + 54,119 \ [g](\#eq:fieldcapacityequation2)
    \end{equation}
    $$
    
I am not really sure what's going on here. I am running on master, and checked that my mods are not interfering. However, I have no clue why the inline code is not reinserted; which breaks multiple features on my personal end (aka: updating equations by hand sucks, thus I am trying to use RMarkdown the way it is supposed to be used)

I hope this is sufficient information, but I can provide further if required.

**Comment by Gewerd-Strauss** [comment]
I tracked the issue down to the fact that latex blocks may contain inline code. Currently, inline code gets replaced before latex blocks:

```python
    def StripCodeSections(self):
            """(Temporarily) Remove codeblocks/-lines so that they are not altered in all the conversions. Placeholders are inserted."""
            self.codeblocks = re.findall(r"^```([\s\S]*?)```[\s]*?$", self.page, re.MULTILINE)
            for i, match in enumerate(self.codeblocks):
                self.page = self.page.replace("```" + match + "```", f"%%%codeblock-placeholder-{i}%%%")
    
            self.codelines = re.findall("`(.*?)`", self.page)
            for i, match in enumerate(self.codelines):
                self.page = self.page.replace("`" + match + "`", f"%%%codeline-placeholder-{i}%%%")
    
            self.latexblocks = re.findall(r"^\$\$([\s\S]*?)\$\$[\s]*?$", self.page, re.MULTILINE)
            for i, match in enumerate(self.latexblocks):
                self.page = self.page.replace("$$" + match + "$$", f"%%%latexblock-placeholder-{i}%%%")
```
but the reverse is not true for the [reinsertion`RestoreCodeSections(self)`](https://github.com/obsidian-html/obsidian-html/blob/master/obsidianhtml/parser/MarkdownPage.py#L123-L130):

```python
   def RestoreCodeSections(self):
        """Undo the action of StripCodeSections."""
        for i, value in enumerate(self.codeblocks):
            self.page = self.page.replace(f"%%%codeblock-placeholder-{i}%%%", f"```{value}```\n")
        for i, value in enumerate(self.codelines):
            self.page = self.page.replace(f"%%%codeline-placeholder-{i}%%%", f"`{value}`")
        for i, value in enumerate(self.latexblocks):
            self.page = self.page.replace(f"%%%latexblock-placeholder-{i}%%%", f"$${value}$$")
```
The replacement parts are correctly stored in self.codelines, and everything is parsed correctly-ish.  So, to resolve this issue you just rearrange the order of operations when restoring code sections:


```python
   def RestoreCodeSections(self):
        """Undo the action of StripCodeSections."""
        for i, value in enumerate(self.codeblocks):
            self.page = self.page.replace(f"%%%codeblock-placeholder-{i}%%%", f"```{value}```\n")
        for i, value in enumerate(self.latexblocks):
            self.page = self.page.replace(f"%%%latexblock-placeholder-{i}%%%", f"$${value}$$")
        for i, value in enumerate(self.codelines):
            self.page = self.page.replace(f"%%%codeline-placeholder-{i}%%%", f"`{value}`")

```

---

However, in principle you could nest inline code into a codeblock the same way you do with a latex block. In that case, the above solution would fail for the same reason the master branch fails for in this issue. So, you could reorder both `RestoreCodeSections()` and `StripCodeSections()` to

```python
    def StripCodeSections(self):
        """(Temporarily) Remove codeblocks/-lines so that they are not altered in all the conversions. Placeholders are inserted."""
        self.codelines = re.findall("`(.*?)`", self.page)
        for i, match in enumerate(self.codelines):
            self.page = self.page.replace("`" + match + "`", f"%%%codeline-placeholder-{i}%%%")

        self.codeblocks = re.findall(r"^```([\s\S]*?)```[\s]*?$", self.page, re.MULTILINE)
        for i, match in enumerate(self.codeblocks):
            self.page = self.page.replace("```" + match + "```", f"%%%codeblock-placeholder-{i}%%%")

        self.latexblocks = re.findall(r"^\$\$([\s\S]*?)\$\$[\s]*?$", self.page, re.MULTILINE)
        for i, match in enumerate(self.latexblocks):
            self.page = self.page.replace("$$" + match + "$$", f"%%%latexblock-placeholder-{i}%%%")

    def RestoreCodeSections(self):
        """Undo the action of StripCodeSections."""
        for i, value in enumerate(self.latexblocks):
            self.page = self.page.replace(f"%%%latexblock-placeholder-{i}%%%", f"$${value}$$")
        for i, value in enumerate(self.codeblocks):
            self.page = self.page.replace(f"%%%codeblock-placeholder-{i}%%%", f"```{value}```\n")
        for i, value in enumerate(self.codelines):
            self.page = self.page.replace(f"%%%codeline-placeholder-{i}%%%", f"`{value}`")
```

Issue here again is that in theory, if you flip it upside down you could have code blocks containing latex blocks. Not sure if there's an actual application where that would be viable, especially as this would be extremely dependant on the markdown postprocessor used. 

I'd argue that especially codelines in latex blocks are a valid option to support, given that f.e. RMarkdown allows for it and is well-used by a shitton of people. <sup>Dynamic document generation is awesome, _yes I'll preach about it till my death :P_</sup>.

By design, the edge case of the first-replaced type containing the second- or third-replaced type leading to issues will always exist with this design - not that I would know a way of the top of my head how to circumvent that - so I would suggest to favour the most likely and most useful version.
And in my opinion, you're much more likely to have a latex block containing code in a markdown doc than a code block containing latex syntax . But I might be wrong there.



I guess this pit is deeper than I initially thought, and opens up to the _wonderful_ world of edge-cases. I suppose one could crawl the each document top to bottom and capture/restore it properly that way, just not sure if that is worth the hassle. 

Thank you again for this amazing tool.

Sincerely,   
~Gw

**Comment by Gewerd-Strauss** [comment]
> However, in principle you could nest inline code into a codeblock the same way you do with a latex block. In that case, the above solution would fail for the same reason the master branch fails for in this issue. So, you could reorder both `RestoreCodeSections()` and `StripCodeSections()` to

Welp. Guess my brain was dead, cuz that solution is utter bogus. This would annihilate code blocks as the first two \` would be consumed to create inline code, and leaving a malformatted codeblock. So the overall order should be:


1. Strip codeblocks
2. Strip codelines
3. Strip latexblocks
4. Restore latexblocks
5. Restore codelines
6. Restore codeblocks

._.

**Comment by dwrolvink** [comment]
Did not test this as I am a bit short on time lately, but I agree with your analysis.
And if it works for you than I guess it's tested enough :)

Thanks for working this out and the PR!

**Comment by Gewerd-Strauss** [comment]
I can say at least that for me, running on that branch since opening this issue and PR I have not encountered an issue so far. Obviously I will be biased because I wrote the code pertaining to this; but so far I can not attest to any issues.
