### ISSUE TITLE
question: Customizing navigation panel on left-hand side of a website?

### ISSUE THREAD

**Issue by p-o-seidon** [obsidian-html/obsidian-html#763]
Obsidian sorts folders and notes alphabetically. Is there a possibility to override this behaviour when exporting to a Website using a TOC- or navigation file as MkDocs does?

Cheers
Paul

P.S.: How could I have labeled this post as question?

**Comment by dwrolvink** [comment]
The only option for ordering yourself is to create a navigation note and to use that as your left-hand navbar. 

https://obsidian-html.github.io/configurations/features/side-panes.html#!html_page

You can't label your own issues, only developers can do that. There is also the option of posting under [discussions](https://github.com/obsidian-html/obsidian-html/discussions)
